### PR TITLE
Gems page order by downloads count.

### PR DESCRIPTION
**Pull request by huacnlee**
Current it order by name, that not useful.

### CODE REVIEW

**Comment by sferik** [comment]
I’ll leave this one up to @qrush. I tend to agree that the extremely long alphabetical list is not so useful. Search results are ordered by popularity, so maybe browsing should be too. ¢¢

**Comment by qrush** [comment]
That's a good reason. :) It'll go out next deploy.

**Comment by farukaydin** [comment]
:+1: thanks @huacnlee

**Comment by sferik** [comment]
I just deployed this but it doesn’t seem to have worked. I believe the issue is that [the `letter` method sorts rubygems by name](https://github.com/rubygems/rubygems.org/blob/53ef78bb1e85530a3d138d39e90c6338d1d84bf7/app/models/rubygem.rb#L72-L74).

@farukaydin Can you give this another try please…preferably with tests this time?

Related: We were unable to verify this on staging before deploying to production because we don’t have any download stats there. @dwradcliffe has added at TODO to fix that issue.

**Comment by huacnlee** [comment]
😃

**Comment by farukaydin** [comment]
@sferik I can do that but I guess you comment it for @huacnlee  

I came to pr just for thanks :smile:

**Comment by huacnlee** [comment]
I will push another PR again, I'm sorry, I just edit on GitHub not have a test.

**Pull request merged**
