### PR TITLE
add blacklist for reserved gem names

### PR DESCRIPTION
**Pull request by dwradcliffe**
I started with the list from that issue. Are there any other names we want to add to the list?

Fixes: #1155 

review: @indirect @qrush @sferik @arthurnn

### CODE REVIEW

**Comment by sferik** [comment]
:+1:

**Comment by qrush** [comment]
May I also suggest:

* rbconfig
* rubygems
* ubygems :unamused: 
* unicode_normalize
* tk
* win32ole

Pulled a few of these from some greps of `lib` in [ruby trunk](https://github.com/ruby/ruby/tree/trunk/lib).

Also need to `#destroy` any of these that exist, could use a little task for that. Or could just do it console after deploy, your call!

**Comment by dwradcliffe** [comment]
Added a few more. I'm going to ship this as is and we can remove the existing gems in a second PR.

**Comment by arthurnn** [comment]
👍

**Comment by ajb** [comment]
Looks like this is the cause of https://github.com/rubygems/rubygems/issues/1474.

I understand the impetus behind this PR, but as a gem maintainer, it would have been nice to have a heads-up. [We're aware](https://github.com/chrismccord/sync/pull/162#issuecomment-68098811) that `Sync` is already a module in the stdlib, but nobody has been able to dedicate the effort to renaming the gem.

> we can remove the existing gems in a second PR.

This obviously hasn't happened yet... but are there any details on what this will look like? Will folks' deployments start breaking suddenly?

**Comment by arthurnn** [comment]
@ajb thanks for letting us know about the issue. I will talk to the team and get back to you with a solution.
Sorry about that

**Pull request merged**
