### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by laserlemon**
Hey @rubygems/owners, this is just a little pull request to losslessly optimize the repo's images. In this case, it's only one, so nice work! If you want to automatically optimize new images via pull request going forward, public repos are free at [Inchworm](https://inchworm.io). I'm including Inchworm's original pull request body below. Let me know if you have any questions!

---

## Inchworm Image Optimization Summary

Inchworm optimized 1 image for a total savings of 22.7 KB (36.8%).

| Image | Original | Saved | % |
|:--- | ---:| ---:| ---:|
| public/sponsors.png | 61.7 KB | 22.7 KB | 36.8% |

### CODE REVIEW

**Comment by acacheung** [comment]
lgtm :)

**Comment by laserlemon** [comment]
Just think of all the extra milliseconds that people will see the sponsors' logos! :stuck_out_tongue_winking_eye:

**Comment by arthurnn** [comment]
thanks

**Comment by laserlemon** [comment]
:+1:

**Pull request merged**
