### PR TITLE
Check for toxic email domain only when present.

### PR DESCRIPTION
**Pull request by simi**
fixes https://app.honeybadger.io/projects/40972/faults/74640394

### CODE REVIEW

**Comment by simi** [comment]
Ci would need restart probably

**Comment by sonalkr132** [comment]
I had tried restart, it failed on the second run. is this passing locally?

**Comment by simi** [comment]
Yup, specs are green locally. :pray: https://github.com/rubygems/rubygems.org/pull/2627 will fix CI for now.

**Comment by simi** [comment]
@sonalkr132 looks fine now.

**Comment by sonalkr132** [comment]
Thanks @simi I wish there was a way to order validation. This validation should ideally run after email format validation.

**Comment by simi** [comment]
Indeed @sonalkr132, I tried to move validations around, but it is a little unpredictable still.

**Pull request merged**
