### PR TITLE
Load rails 7.0 defaults

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by segiddins** [comment]
0 clue why this would cause test failures, it should be no functional change

**Comment by martinemde** [comment]
That's strange. Could it be that other gems are relying on the old api? For example, what's with the deprecation all the sudden?

```
DEPRECATION WARNING: `Rails.application.secrets` is deprecated in favor of `Rails.application.credentials` and will be removed in Rails 7.2. (called from call at /home/runner/work/rubygems.org/rubygems.org/lib/clearance_backdoor.rb:9)
```

Either I'm crazy or that code doesn't have a reference to secrets (I'm going to double check again now but I did already look and it's quite boring code).

**Comment by segiddins** [comment]
I believe the warnings are unrelated

**Comment by simi** [comment]
@segiddins @martinemde something in this list https://github.com/rails/rails/blob/4d3e2910c680baad7c14d2797a53a6b72405149b/railties/lib/rails/application/configuration.rb#L219-L268 causes `find_by_sql` calls to be cached and sadly there is code calling `UPDATE` clauses with `find_by_sql` which are not executed sometimes due to this change.

There were 2 places using `find_by_sql`, I have refactored them to use `update_all` or `update_column`. See each individual commit message for more details.

**Pull request merged**
