### PR TITLE
Mark Version#sha256 as not nullable

### PR DESCRIPTION
**Pull request by kbrock**
DO NOT MERGE UNTIL after rake script populates all `sha256` values in `Version` records.

just run this first:
```
rails runner "puts Version.where(:sha256 => nil).count == 0 ? 'GOOD TO GO' : 'NOT SO FAST BUDDY'"
```

This is a follow up for #872

### CODE REVIEW

**Comment by dwradcliffe** [comment]
I think the tests need to be updated too... see the Travis failure.

**Comment by kbrock** [comment]
@dwradcliffe thanks. looks like I didn't run the migration in test before testing.

Feeling guilty about deleting a test, I added a test on `recalculate_sha256!` for good measure.

**Comment by arthurnn** [comment]
I am not sure if we will be able to do that at all.
We have a few gems on the DB that the .gem file was missing, so we were not able to generate the sha.

I think it is fine to have the sha columns as nullable. 
thanks anyways.

**Comment by kbrock** [comment]
@arthurnn thanks

**Pull request closed without merging**
