### PR TITLE
"Run just one file's tests" documentation

### PR DESCRIPTION
**Pull request by kevinlinxc**
Running all the tests is quite lengthy, most people who have experience probably know how to run just one file's tests, but for everyone else, I think it wouldn't hurt to have it in the CONTRIBUTING.md.

### CODE REVIEW

**Review by bettymakes — COMMENTED** [review]
That's a good suggestion Kevin 💯 ! 
+1, I don't think it'd hurt adding that in. I have a small NIT on language ... I think this would read better: `Run a single test file:`

**Comment by simi** [comment]
Actually you can just follow Rails guides (https://guides.rubyonrails.org/testing.html#your-first-failing-test).

`bin/rails test path/to/some_test.rb` is enough in here now.

**Comment by kevinlinxc** [comment]
i replaced the bundle exec rake with bin/rails commands - perhaps I should keep both e.g. 
`bin/rails test OR bundle exec rake`

**Comment by simi** [comment]
I think instead of maintaining custom documentation it should be enough to link to Rails testing docs. We can keep the

> * Run the tests: `bin/rails test`

part and mention to see rails testing guides for more details.

**Comment by kevinlinxc** [comment]
done

**Comment by simi** [comment]
Cool, this seems like good balance to make clear starting instructions and link to 3rd party resource we don't need to maintain.

**Review by simi — APPROVED** [review]

**Pull request merged**
