### PR TITLE
Consolidate duplicate sidebar links keeping the first of the duplicates in the list

### PR DESCRIPTION
**Pull request by etherbob**
## What problem are you solving?
In #2375 it was noted that duplicate links add clutter to the sidebar on the gems show route.

## What approach did you choose and why?

Decided to hook in at Link#each as it seemed like  a decent spot to filter out duplicate values.

## What should reviewers focus on?

This is my first PR against rubygems.org and I'm not certain if there are enough calls to this path during render that it might be worth memoizing or if that itself would have undesired effects. There's probably also a question to be asked about gem author intent with the duplicate links and whether or not someone might get confused if they don't see a specific link to "source code" for instance if it's been superseded by the "home page" link.

## Testing

I used jekyll-exif-data as one example of a gem with multiple metadata links pointing to the same uri. But visiting any gem with duplicate links should now only show the first link in the order specified in Link::LINKS

before-after

### CODE REVIEW

**Comment by simi** [comment]
Hello! Thanks for the PR! I'll take a look in detail later. Looks good at first sight. Can you please fix rubocop warning for now?

>  There's probably also a question to be asked about gem author intent with the duplicate links and whether or not someone might get confused if they don't see a specific link to "source code" for instance if it's been superseded by the "home page" link.

It is possible to raise a warning on the other side (during `gem build`). Feel free to check https://github.com/rubygems/rubygems/blob/ffad5e639fb21131b9285c4cb3f4798e53687ee9/lib/rubygems/specification_policy.rb class.

**Comment by segiddins** [comment]
Thanks for the PR! Do you mind adding some before/after screenshots so reviewers can understand the impact of the change?

**Comment by etherbob** [comment]
> It is possible to raise a warning on the other side (during `gem build`). Feel free to check https://github.com/rubygems/rubygems/blob/ffad5e639fb21131b9285c4cb3f4798e53687ee9/lib/rubygems/specification_policy.rb class.

@simi good idea! I started a [discussion](https://github.com/rubygems/rubygems/discussions/6654) to gauge interest before continuing.

**Comment by etherbob** [comment]
> Hello! Thanks for the PR! I'll take a look in detail later. Looks good at first sight. Can you please fix rubocop warning for now?

rubocop is happy now

also added before/after screenshots.

**Review by simi — APPROVED** [review]

**Comment by simi** [comment]
Sorry for the delay. Looks good!

**Comment by etherbob** [comment]
not much movement on that discussion but I opened PR if there's still interest in having a warning.

**Pull request merged**
