### PR TITLE
Bump ruby version to 2.6.6

### PR DESCRIPTION
**Pull request by colby-swandale**
Ruby 2.6.6 fixes 2 security issues. See [release page](https://www.ruby-lang.org/en/news/2020/03/31/ruby-2-6-6-released/)

### CODE REVIEW

**Comment by sonalkr132** [comment]
> Requested binary installation but no rubies are available to download, consider skipping --binary flag.
Gemset '' does not exist, 'rvm ruby-2.6.6 do rvm gemset create ' first, or append '--create'.

lol. I think we can remove rvm from build and run tests using docker images.

**Comment by dwradcliffe** [comment]
Need to bump the Dockerfile

**Comment by colby-swandale** [comment]
@dwradcliffe The Dockerfile is selecting the ruby version only by the minor version or am i missing something?

**Comment by sonalkr132** [comment]
>  The Dockerfile is selecting the ruby version only by the minor version 

Yes, correct. I feel we should pin the minor version too.

**Comment by dwradcliffe** [comment]
Oh yes you're right. So I don't object to merging as is. But I would like to pin the exact docker image, so feel free to include that. This is my preferred method:
https://github.com/rubygems/shipit/blob/3c2e9ec4da5c31307fbe63a286e0563331b92d53/Dockerfile#L1-L2

**Comment by colby-swandale** [comment]
I'm going to merge this as is and then look at pinning the image to a specific hash in another PR.

**Pull request merged**
