### PR TITLE
add yaml option to api profiles endpoint

### PR DESCRIPTION
**Pull request by farukaydin**
Like the title says, it adds yaml respond option in addition to json.

cc: @sferik @arthurnn @qrush

### CODE REVIEW

**Comment by dwradcliffe** [comment]
:-1: We have actually talked about removing yaml. We can't remove a lot of the yaml responses because the rubygems client depends on it, but I'd rather not add more yaml that people might start to depend on.

**Comment by farukaydin** [comment]
@dwradcliffe I didn't know the team thinks remove it. Why you consider removing yaml although it's used by rubygems client ?

**Comment by dwradcliffe** [comment]
@farukaydin The idea is that JSON is better for the api in general. It's not a big deal though, so let's just leave this merged even if we end up removing yaml later. :) thanks!

**Comment by farukaydin** [comment]
@dwradcliffe thanks for clarification. :+1:

**Pull request merged**
