### PR TITLE
Update ruby version in the contributing docs

### PR DESCRIPTION
**Pull request by zamith**

### CODE REVIEW

**Comment by dwradcliffe** [comment]
We are still using 2.2 in production and 2.4 isn't even released yet.

**Comment by zamith** [comment]
Right, I meant 2.2.4, which is what is mandated by the `.ruby-version` file. Any reason for that file and the contributing docs to differ?

**Comment by dwradcliffe** [comment]
They should be the same, I think they are only out of sync because it was forgotten. We're about to upgrade to 2.3.1 so if you want to change the .ruby-version to match we can merge this as soon as that is complete.

**Comment by sonalkr132** [comment]
I should be apologizing for confusion. I updated it #1289 when I was updating the rubygems version, since we already had a PR #1283 for update and we were going to update it in prod soon enough. Sorry :sweat:

**Comment by zamith** [comment]
It seems like #1283 normalizes this, so I'm closing this in favor of that.

**Pull request closed without merging**
