### PR TITLE
Update to Ruby 1.9 hash syntax

### PR DESCRIPTION
**Pull request by sferik**
There have been [a](https://github.com/rubygems/rubygems.org/pull/996#discussion-diff-33690900) [few](https://github.com/rubygems/rubygems.org/pull/997#discussion_r33747580) [recent](https://github.com/rubygems/rubygems.org/pull/999#discussion_r33825437) pull requests that got dinged for not updating to Ruby 1.9 hash syntax. If that is going to be a requirement for new code, I think we should use it consistently throughout the existing code, to set a good example.

We should also enforce that requirement automatically during CI build, via RuboCop, so we are not manually giving the same feedback over and over again. **Note:** I’m not using RuboCop to enforce any other coding style, only the new hash syntax. We could decide to use it more liberally in the future for other style choices we wish to enforce.

### CODE REVIEW

**Comment by Ch4s3** [comment]
That's funny, I didn't see this before I put up #1002

**Comment by arthurnn** [comment]
:+1: on my side.. I like rubocop for those type of catches. I am not a big fan of hooking this into CI tho, as for me, CI should be only tests. (I am actually building something to fix this). Anyways for now, hooking into the CI is our best option. :shipit:

**Comment by arthurnn** [comment]
Maybe squash the `Update hash syntax ...` commits in one, so we only genarete one entry on git history.

**Comment by dwradcliffe** [comment]
On one hand, this ads a commit to hit history that makes it harder to track down changes through history.

On the other hand, if we do it as we go, we already have changes on every single commit that have nothing to do with the real changes, which also makes it hard to track down changes.

I like using Rubocop to enforce this and cleaning up the codebase is great.

:+1:

**Comment by arthurnn** [comment]
Git history is important, but a healthy and easier to follow code base is more important in my option.

**Comment by qrush** [comment]
-1 on committing the RuboCop log. Seems like it doesn't belong.

**Comment by dwradcliffe** [comment]
Rubocop log?

On Monday, July 6, 2015, Nick Quaranto <notifications@github.com> wrote:

> -1 on committing the RuboCop log. Seems like it doesn't belong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubygems/rubygems.org/pull/1001#issuecomment-119051662>
> .
>


-- 
---
David Radcliffe

**Comment by qrush** [comment]
This huge file -

https://github.com/rubygems/rubygems.org/blob/hash-syntax/.rubocop_todo.yml

I'm fine with using code cleaning tools locally/in dev. It seems like another weird step to commit it and force everyone else to see it and deal with it. It's like you left the vacuum cleaner out after cleaning up the room.

**Comment by dwradcliffe** [comment]
Those are the Rubocop rules, necessary so that we don't enforce anything
other than hash style.

On Monday, July 6, 2015, Nick Quaranto <notifications@github.com> wrote:

> This huge file -
>
> https://github.com/rubygems/rubygems.org/blob/hash-syntax/.rubocop_todo.yml
>
> I'm fine with using code cleaning tools locally/in dev. It seems like
> another weird step to commit it and force everyone else to see it and deal
> with it. It's like you left the vacuum cleaner out after cleaning up the
> room.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rubygems/rubygems.org/pull/1001#issuecomment-119052529>
> .
>


-- 
---
David Radcliffe

**Comment by qrush** [comment]
From https://github.com/rubygems/rubygems.org/blob/hash-syntax/.rubocop_todo.yml#L3-L4:

> The point is for the user to remove these configuration records
> one by one as the offenses are removed from the code base.

Maybe I'm just new to seeing this - but it does not feel like it belongs in the repo. I haven't been a fan of any coverage/etc tools for a long time, but it just seems weird to keep dragging this along. It's highly unlikely we will ever fix all of these issues. It's clear this tool was used for a specific reason/purpose. We don't need to keep this log around for everyone, or have a tool in general to enforce syntax. That's what reviews + PRs are for.

**Comment by dwradcliffe** [comment]
I'd rather see this all directly in `.rubocop.yml`, but I do think it belongs in the repo. I see this file as no different than a ruby version file or a travis config file. RuboCop ships with a default set of rules, taken from the [ruby style guide](https://github.com/bbatsov/ruby-style-guide). We need to specify which of those rules we want to use and define exactly what our project style should look like. We may enforce additional things later or we might not, either way is fine. It's super helpful for new (or old!) contributors to have a tool to help catch syntax errors before they even submit a PR.

**Comment by qrush** [comment]
I'm not a fan in general of a tool that enforces syntax. Maybe if it was built into the language like `gofmt` I'd feel differently. I'd rather have a style guide or try to adhere to an existing one.

**Comment by sferik** [comment]
Normally, I suppose it’s bad form to merge one’s own pull request, but since this one is so prone to conflicts, I’m about to do that, so I don’t need to rebase again. I was able to convince @qrush that RuboCop is worth using to enforce syntax during CI build, as long as I continue to maintain it. Here is our abridged Slack conversation on the topic:

> @sferik: Why don’t you like enforcing syntax programmatically?
> @qrush: basically i’m not convinced we want to keep that big rubocop generated file because i’m not convinced everyone will use it
> @sferik: That’s why I put it in CI: to force everyone to use it. :stuck_out_tongue_winking_eye: Do you prefer telling people “please use the new hash syntax” manually? I’d rather rubocop do that for us by failing the build with a helpful error message.
> @qrush: i’d rather have a styleguide than a strict tool to run
> @sferik: why?
> @qrush: i’ve never seen a tool work out in practice
> @sferik: rubocop has saved me hours upon hours of telling people to read the style guide
> @qrush: Do we have to check that huge file in?
> @sferik: RuboCop has default rules, defined here: https://github.com/bbatsov/rubocop/blob/master/config/default.yml. We only want to enforce one of those rules (for now), the rule about hash syntax. That giant file just disables all the other rules.
> @qrush: Ah.
[…digression about our CI configuration…]
> @qrush: i’m fine with merging it.

All open pull requests will probably need to rebase from `master`.

**Comment by nikolas** [comment]
why doesn't rubocop allow you to override just one rule at a time instead of including that big file?

**Comment by sferik** [comment]
> why doesn't rubocop allow you to override just one rule at a time instead of including that big file?

Good question. I actually just discovered the `DisabledByDefault` configuration option which allows exactly this. However, we decided to use RuboCop for more than just hash syntax, so starting with `.rubocop_todo.yml` makes sense. For what it’s worth, I’ve already reduced the size of that file from 453 lines down to 122 by making the codebase more consistent.

**Pull request merged**
