### PR TITLE
Fixes #863 - Upgrades the RubyGems blog to match the rest of the site.

### LINKED ISSUE #863: Update blog style
https://github.com/rubygems/rubygems.github.com/ (blog) needs to use the new style from rubygems.org .

### PR DESCRIPTION
**Pull request by chasecoolman**
Fixes #863 

Integrates ButterCMS (https://buttercms.com) into the repo improving the blog by bringing it into the same layout design as the rest of Rubygems. Butter integrates into the rest of the main Rails app so the blog is no longer relegated to being a separate disconnected app. This also means that anytime RubyGem's header / footer / overall design changes, the blog will automatically stay in sync. This PR also moves the blog to `rubygems.com/blog` for better SEO as well as adds additional built-in features of Butter such as blog sitemap.xml and rss + atom feeds.

The purpose of this PR is to get review and approval on design / layout. Note that this is completely flexible and I encourage feedback from the design team. It's quite easy to make updates. I've imported a couple blog posts from the old blog to demonstrate what the new blog will look like. Once the design is approved, I'll port over all old content into the new blog, set up accounts + provide instructions for how to contribute to the blog. 

ButterCMS is normally a paid service but we're happy to provide RubyGems community with a completely free instance. Adding Butter also means that blog posts can published with no deploy required.

Here are some previews.

**Blog Home**
image

**Blog Post**
image

**Author Profile**
image

### CODE REVIEW

**Comment by arthurnn** [comment]
I like having the blog as a separate app TBH.

**Comment by acacheung** [comment]
Hey @chasecoolman! Sorry about doubling up on work for this. DockYard did the design for this a while ago and it was kinda forgotten about. https://github.com/rubygems/rubygems.github.com/pull/22

**Comment by chasecoolman** [comment]
Hey @acacheung thanks for sharing those mocks! They look pretty close to the v1 I've put together in this PR. Would you like me to update this PR to more closely match those designs? Should be easy to do.

**Comment by acacheung** [comment]
@chasecoolman that pr includes the changes for css too!

**Comment by chasecoolman** [comment]
Oh I see. Yeah, that's the problem I'm trying to help solve. With this PR, we'll never have to go through this "update blog to match main site" cycle again. Problem with Jekyll blog is it won't be long before the blog diverges in design from the main site. It's inevitable. Also, user authentication doesn't carry over into the Jekyll blog. With this PR it's seamless across both main site and blog. Just shedding light on some advantages to consider with this PR :)

**Comment by simi** [comment]
IMHO it will be better to keep blog in https://github.com/rubygems/rubygems.github.com and content versioned in public git repository.

**Comment by arthurnn** [comment]
> IMHO it will be better to keep blog in https://github.com/rubygems/rubygems.github.com and content versioned in public git repository.

👍

**Comment by chasecoolman** [comment]
Ok thanks for the feedback. Will close this PR

**Comment by arthurnn** [comment]
thanks a lot @chasecoolman for working on this. ❤️

**Comment by chasecoolman** [comment]
np @arthurnn :+1:

**Pull request closed without merging**
