### PR TITLE
use pluralize method for licenses header, fix #1006

### LINKED ISSUE #1006: License field should be plural when only one license exists
For example on https://rubygems.org/gems/phish:

screen shot 2015-07-07 at 12 11 47 am

`Version#licenses` is already an array so this should be pretty straightforward. https://github.com/rubygems/rubygems.org/blob/master/app/models/version.rb#L12

### PR DESCRIPTION
**Pull request by farukaydin**
fixes #1006 

cc: @qrush

### CODE REVIEW

**Comment by dwradcliffe** [comment]
Test? :smile:

**Comment by farukaydin** [comment]
I have no idea why I don't add test when I submit pr  :smile:  I'll add it.

**Comment by farukaydin** [comment]
@dwradcliffe I modified code and added tests. I didn't use localization for tests since it's not used in any test. Feedbacks are very welcome. :tada: :rocket:

**Comment by qrush** [comment]
:ship: :ok_hand:

**Comment by dwradcliffe** [comment]
:+1: Thanks!!

**Pull request merged**
