### PR TITLE
Order profile page gems by downloads

### LINKED ISSUE #4540: Has the sorting on rubygems.org profiles been changed recently?
Not sure if this is a bug or not - has the sorting algorithm been changed?

It now looks like this:

https://i.imgur.com/Y1aNmAF.png

Since a few days.

Before that it was sorted by total number of downloads, so the most downloaded
gem appeared first, on top. Instead, now it seems random where it appears. Also I got
quite a lot of unicorn errors in the last days, so not sure what is going on or if
this is related to anything.

IF the sorting was changed, could the reason be explained in the changelog or
monthly progress report? Right now I don't know why it is different; it is less
useful compared to the prior variant for sure, as my most downloaded gem now
appears in the middle rather than on top as before.

### PR DESCRIPTION
**Pull request by dancristianb**
This PR targets updating the profile page gems order so that the gems are ordered by the total number of downloads, the most downloaded gem appearing first. Fixes #4540

#### Before the updates

Screenshot 2024-03-19 at 16 56 13

#### After the updates

Screenshot 2024-03-19 at 16 55 53

### CODE REVIEW

**Comment by dancristianb** [comment]
It looks like this was last updated in https://github.com/rubygems/rubygems.org/pull/4520/files#diff-7a47d335107fc35c2e79cc9c2b0a195c863594dd2343bcd48a4c770ac4af673cR11 🔬 Looking at https://github.com/rubygems/rubygems.org/pull/4520, are there any other updates we'd want to scope in? 🤔

**Comment by simi** [comment]
Hello! Thanks for the PR. I did some cleanup in controller to make it simpler at https://github.com/rubygems/rubygems.org/pull/4553. Once that is merged, I think this can be fixed by changing controller to something simple like:

```ruby
@user = User.find_by_slug!(params[:id])
@rubygems = @user.rubygems_downloaded.includes(%i[most_recent_version gem_download]).strict_loading
```

I'll ping you once PR is merged.

**Comment by dancristianb** [comment]
Sure thing, thanks @simi! Let me know and I'll send out the updates 😀

**Comment by simi** [comment]
@dancristianb merged, feel free to rebase and update.

**Comment by dancristianb** [comment]
> feel free to rebase and update.

@simi updated, hope that's OK - let me know what you think, thanks! 🙏

**Review by simi — APPROVED** [review]

**Comment by simi** [comment]
> > feel free to rebase and update.
> 
> @simi updated, hope that's OK - let me know what you think, thanks! 🙏

Looks amazing. @segiddins can you please check also this is ok since you're author of the original change?

**Review by segiddins — APPROVED** [review]

**Comment by simi** [comment]
Thanks a lot for keeping this updated @dancristianb!

**Pull request merged**
