### PR TITLE
Locales cleanup

### PR DESCRIPTION
**Pull request by spk**

### CODE REVIEW

**Comment by spk** [comment]
@dwradcliffe is this question for me or for the rubygems.org team ? because for me if it's not used, the better it's to remove them.

**Comment by dwradcliffe** [comment]
Question was for everyone :) @qrush @evanphx @sferik

**Comment by qrush** [comment]
There's a few translations in place - I think if you request it with an Accept header it should just "work" right? In any case any app I've worked on with i18n becomes a nightmare to maintain copy changes for.

**Comment by dwradcliffe** [comment]
True, we don't need more things to update. If someone has a specific need we can look again.

**Pull request merged**
