### PR TITLE
test rails 4.2.5rc1

### PR DESCRIPTION
**Pull request by arthurnn**
testing rails rc

@rafaelfranca can you add this repo to the list of notified repos for RC versions?
thanks

### CODE REVIEW

**Comment by sferik** [comment]
Is the point here to just see that tests pass or do we actually want to merge and deploy an RC? I’d suggest we wait until Rails 4.2.5 final is released.

**Comment by arthurnn** [comment]
I'd prefer shipping this to production, i better we find errors as soon as we can

**Comment by sferik** [comment]
Seems risky. I’d rather let those errors be caught by apps whose availability is less critical to the Ruby ecosystem. This site does not make a good guinea pig.

**Comment by rafaelfranca** [comment]
Why is it more risky that wait the final release just to found out that it broke Rubygems in a way that the test suite didn't catch? I'd not rely in "apps whose availability is less critical to the Ruby ecosystem" to catch these errors too.

**Comment by sferik** [comment]
> Why is it more risky that wait the final release just to found out that it broke Rubygems in a way that the test suite didn't catch?

Pre-release software tends to buggier and less stable than post-release software, almost by definition, since the only changes between a release candidate and a final release are bug fixes. I suppose it’s possible that fixing one bug introduces a new bug into the final release that wasn’t present in the release candidate, but in my experience this very rare. It’s much more common the bugs are found in pre-release software and fixed before the final release. Any diff between the first release candidate and the final release is evidence of this happening. For example, for Rails 4.2.0, there were three release candidates ([88 commits](https://github.com/rails/rails/compare/v4.2.0.rc1...v4.2.0)). For Rails 4.2.1 there were four ([18 commits](https://github.com/rails/rails/compare/v4.2.1.rc1...v4.2.1)). Not all of those commits were bug fixes but the majority are.

In my opinion, RubyGems.org is too critical of a service to be a testing ground for Rails (or any other dependencies).

Once the maintainer of a project has the confidence to ship a final release, then I am all for updating to the latest version.

**Comment by arthurnn** [comment]
thanks all for the thoughts

**Pull request closed without merging**
