### PR TITLE
Fixes flash banners persisting for too long

### PR DESCRIPTION
**Pull request by americodls**
Fixes https://github.com/rubygems/rubygems.org/issues/3149

### CODE REVIEW

**Comment by americodls** [comment]
Even though the issue has been created for another workflow, but this problem happens where the verify step is invoked. I've chosen this test file because the context was easier to it (I guess).

Happy to change anything if is needed.

I also have found other parts of the application where the same problem would occur.
I would be happy to fix all of them and apply the test guidance I get in this PR.

**Review by simi — APPROVED** [review]

**Comment by simi** [comment]
@americodls can you please fix Rubocop violation at https://github.com/rubygems/rubygems.org/runs/8053686977?check_suite_focus=true?

**Comment by americodls** [comment]
> @americodls can you please fix Rubocop violation at https://github.com/rubygems/rubygems.org/runs/8053686977?check_suite_focus=true?

Done!

**Comment by simi** [comment]
Thanks @americodls. Feel free to submit PR fixing more cases. If I understand it well (per https://guides.rubyonrails.org/action_controller_overview.html#flash-now), `flash.now` should be used if followed by `render`. Sadly there is no `rubocop-rails` rule for this.

**Comment by americodls** [comment]
@simi I am gonna try to create a custom cop to enforce `flash.now` before `render`.
That will help me to find and fix all the other occurrences on this project.
Thanks for the feedback here!

**Comment by simi** [comment]
@americodls that was just an idea, I have no idea if that's actually good idea. :)

**Pull request merged**
