### PR TITLE
disable Version set_info_checksum

### PR DESCRIPTION
**Pull request by dwradcliffe**
fyi @sonalkr132 @indirect @segiddins @fotanus 

https://app.honeybadger.io/projects/40972/faults/30180687

`RuntimeError: BUG: different size of reqs and dep_names.`

### CODE REVIEW

**Comment by sonalkr132** [comment]
This should have failed tests..

**Comment by dwradcliffe** [comment]
Yup, let's look at adding tests for it before we re-enable.

**Comment by fotanus** [comment]
I can't access the honeybadger

> Sorry. That Github account isn't on file, so we couldn't log you in.

The error is a explicit throw [on this line](https://github.com/rubygems/rubygems.org/blob/ee059a0b45433ec6d63d1b8f4975db31144c0f36/app/models/rubygem.rb#L306) and I'm not sure how to handle. Seems like we have a dependency without requisites or extra requisites for a dependency? Any chance the character '@' or ',' can appear on one of those fields?

I'm making some time to see this on the weekend, but I think the problem is smaller than I expected

**Comment by sonalkr132** [comment]
@fotanus Please checkout: https://github.com/rubygems/rubygems.org/pull/1300#discussion_r66801004

I am pretty sure that it is the case. It would great if you could confirm/crosscheck.

**Comment by fotanus** [comment]
Right, so you already got to the next question in this chain :-)

**Comment by sonalkr132** [comment]
@segiddins said that we should skip the `dep_name` like we doing it on bundle-api.

As of now, I can't think of anything else other than to replace the complete query with raw sql. It is not possible to determine in strings separated by `@` and `,` which requirement belongs to which `dep_name `in case of mismatch.

**Comment by fotanus** [comment]
I can't figure out a way to do this without nested or multiple queries. So I'm with you for raw sql on this. Not sure if people will be happy with that, because sql is ugly. Not that the current query is great.

**Comment by fotanus** [comment]
@dwradcliffe do you have anything against raw SQL for complex queries? Would you prefer two queries in a row or raw SQL?

**Comment by dwradcliffe** [comment]
We already have raw SQL in a few places where it is necessary. At this scale if it makes a performance difference I think it's ok.

**Comment by fotanus** [comment]
thanks!
@sonalkr132 can you do this without multiple or nested queries? I'm not known for my great SQL skills :-)
If you need nested queries I can do it! I have a scratch for this sql somewhere in my house

**Comment by sonalkr132** [comment]
Actually I had found a smaller solution which required very little change what was already there, so I went with that. I have already proposed the change (of using [coalesce](https://www.postgresql.org/docs/9.5/static/functions-conditional.html#FUNCTIONS-COALESCE-NVL-IFNULL) ) in https://github.com/rubygems/rubygems.org/pull/1327/commits/e82e9b318d7c20c1bc3e54e5c4c701825e91f9a9 . @fotanus I have made a few other changes as well, it would nice if you had a look at #1327 in general.

> At this scale if it makes a performance difference I think it's ok.

I had benchmarked current implementation (of using aggregation for dep_name and req) against what we had in bundler-api (raw nested sql select) and there was no measurable difference.

**Comment by fotanus** [comment]
TIL of coalesce, thanks! So we can close this?

**Comment by sonalkr132** [comment]
> Is the set_info_checksum enabled already?

No. I have enabled it in the PR which is not merged yet.

**Comment by fotanus** [comment]
ok, thanks! Can you please @ me on compact index stuff? I have a lot on my plate right now, but I'm a bit curious about this project

**Pull request merged**
