### PR TITLE
Use summary when possible

### PR DESCRIPTION
**Pull request by stirlhoss**
This change addresses issue #3439. 

gem_info now looks for summary before it looks for description. 

Unit test added to make sure this is functioning correctly.

### CODE REVIEW

**Comment by simi** [comment]
Thanks for the PR @stirlhoss. I have invited other maintainers to approve this change. If you can add also screenshots before/after, it will make review smoother per my experience.

**Review by segiddins — APPROVED** [review]

**Review by hsbt — APPROVED** [review]

**Comment by indirect** [comment]
Sorry, maybe I missed something... why do we want to do this? Personally I would be fine if we stopped having two separate things and just treated them as the same, but I'm not clear on why preferring the shorter one on the gem info page is better than preferring the longer one.

**Comment by stirlhoss** [comment]
This is only intended to change the information that appears on the gem list/search results. As far as I can tell, this change is only affecting gems that have a summary that can be displayed in the search list in favor of the truncated description. 

I am having a hard time figuring out what is being displayed on the gem info page. It doesn't make sense to show the short_info since there is no need to truncate on that page and I can't see that gem_info is getting called in any of the views. I would imagine we are just printing the information in the order of: description, summary, message about not having any information.

I agree that it seems a bit extra complicated to have both things but it seems like there is no consistency in which of the fields get filled out in the gemspec so we need to make some kind of concession. I am new to this codebase though so I could be missing something big here.

**Comment by indirect** [comment]
@stirlhoss oh! that is what I was missing, this is only for the list in search results. 🤦🏻 well, that makes sense. thank you very much!

**Pull request merged**
