### PR TITLE
Correct incorrect semicolon placement.

### PR DESCRIPTION
**Pull request by knappe**

### CODE REVIEW

**Comment by knappe** [comment]
A simple change to correct accidental global declaration.  However, the better fix would be to:

1) Fix this to use multiple var declarations [0]
2) Use cameCase naming conventions [1]

0 - http://benalman.com/news/2012/05/multiple-var-statements-javascript/
1 - https://github.com/airbnb/javascript#naming-conventions

**Comment by knappe** [comment]
If desired, I can put together a followup PR to fix both issues.

**Comment by arthurnn** [comment]
thanks..
I dont care much about your first point. But number 2 would be good to go i think.

**Comment by knappe** [comment]
@arthurnn I can build a second PR for 2), but the entire reason this mistake crept into the code was because of 1).

**Comment by arthurnn** [comment]
Yeah, you're right.. I dont write much JS these days, so dunno what is good code style.

**Pull request merged**
