### PR TITLE
include SHA256 checksum in versions

### PR DESCRIPTION
**Pull request by cstrahan**
While useful in general, checksums are an absolute _must_ for packaging gems in [NixOS](http://nixos.org/) (see my original issue at https://github.com/rubygems/rubygems.org/issues/712 for more details).

This PR:

* adds a `sha256` column to `versions`
* the hash is strict-base64 encoded ([RFC 4648](http://tools.ietf.org/html/rfc4648))
* the hash is returned in the api queries and is also stored in the index

I will write some tests shortly, but I'm opening this PR now to get feedback as soon as possible.

At a high level, does this seem like a reasonable approach?

### CODE REVIEW

**Comment by davefp** [comment]
@cstrahan As a result of #610 a large chunk of the repo's history was re-written. Please rebase your PR so that it will merge cleanly. Thanks!

(There are further details on the blog: http://blog.rubygems.org/2015/02/01/rewriting-history.html)

**Comment by kbrock** [comment]
Is the general consensus that we want to continue forward on this? I'm more than happy to rebase and fix the rake tasks.

**Comment by arthurnn** [comment]
IMO, yes, we should have a checksum. A few questions tho, I think bundler-api is generating a checksum  on their side, if thats true, could we move that all to rubygems.org ? (I could be totally wrong here, not sure).
cc @indirect

**Comment by dwradcliffe** [comment]
@kbrock yes, we would like to get this done. I think we just need to split the migration into two steps.

**Comment by indirect** [comment]
Yup, what @dwradcliffe said. Thanks for your work on this! :)

**Comment by kbrock** [comment]
@arthurnn Please close if this is fully covered by #872?

**Comment by arthurnn** [comment]
thanks all

**Pull request closed without merging**
