### PR TITLE
Lossless img/svg compression with ImageOptim and SVGO

### PR DESCRIPTION
**Pull request by nateberkopec**
Just about 5% savings on the PNGs, but the SVGs are about 50% smaller.

Does anyone have the original artwork for the sea_floor.png and sea_level.png? It seems like that was vector artwork to begin with, we should just be using that.

### CODE REVIEW

**Comment by nateberkopec** [comment]
side comment: I tried tracing sea_floor.png with Inkscape, and the SVG that came out was 50% smaller than the PNG. It looked OK but the colors were all messed up.

**Comment by dwradcliffe** [comment]
@acacheung should have it

**Comment by nateberkopec** [comment]
@acacheung if you want to, you can just email the files to me at the address on my github profile and I'll turn it into a PR

**Comment by acacheung** [comment]
Yup! I have them. I'll take a look over the weekend

**Comment by acacheung** [comment]
Emailed you @nateberkopec!

**Comment by nateberkopec** [comment]
Check out the savings on converting these PNGs to SVG:

| Image  | PNG size (gzip) | SVG size (gzip) | Savings |
| ------------- | ------------- | ------------- | ------------- |
| `gem_wrench` | 110 kB  | 10kB | 91% |
| `sea_floor`  | 1.1 mB | 35kB | 97% |
| `sea_level` | 357 kB | 22kB | 94% |

And of course, the SVGs are still lossless *and* can be infinitely resized, improving their appearance on retina/4K displays. [SVG is supported on all browsers except IE8.](http://caniuse.com/#feat=svg) We can also animate them directly, rather than overlaying PNGs on top of other PNGs.

The SVGs compress *far* better with gzip than the PNGs do. `sea_floor.svg`, for example, is 75% smaller when gzipped, but the PNG is basically the same size after gzip.

My workflow, given the `.ai` files from @acacheung was:

1. Convert to plain `.svg`
1. Change `img` tags to `object`
3. Remove pngs that were used for animation, animate the SVG directly. This removed a few more kB from each page.
2. Upload to [SVGOMG](https://jakearchibald.github.io/svgomg/)
1. Change height/width on SVG to viewBox, add `preserveAspectRatio="xMinYMin meet"` to `svg`

**Comment by indirect** [comment]
thanks!

**Comment by sonalkr132** [comment]
@acacheung svg doesn't seem to be the same?

[staging 404](https://staging.rubygems.org/404) and [production 404](https://rubygems.org/404)
[staging maintenance](http://rubygems.org/maintenance/index) and [production maintenance](http://staging.rubygems.org/maintenance/index)

**Comment by nateberkopec** [comment]
@sonalkr132 I think you got the second set of links backwards there

**Comment by sonalkr132** [comment]
Thanks @nateberkopec :grin:

**Comment by acacheung** [comment]
I think what's happening is that the gradients were created with Illustrator effects rather than SVG filters within Illustrator :/

**Comment by acacheung** [comment]
I could look into how to update, but I'm not really familiar with how to solve it.

**Pull request merged**
