### PR TITLE
Remove unused javascript file

### PR DESCRIPTION
**Pull request by nateberkopec**
Not sure what was going on here, but this JS looks like [ancient whale legs](https://upload.wikimedia.org/wikipedia/en/archive/5/51/20070602133507!Whale_legs.png). Could be wrong, but I can't find that ID (or anything like it) anywhere in the project.

### CODE REVIEW

**Comment by arthurnn** [comment]
Seems like this was added here https://github.com/rubygems/rubygems.org/commit/7dbf529a77fa50aa09e4b88e65fc76ca3c5d33f5#diff-4c41fd9d87681858794942152fadb045R30 . Which was the old stats-by-day page.. 
So I think this is safe to be removed.
thanks

**Comment by arthurnn** [comment]
The way I found that commit SHA was:
- I got the first version of the file, which was 9f0c284991e9f236c604cb04e221da70970fcbdd
- I saw that file used to be `public/javascripts/application.js` before that commit, so I opened it up that with the url:
https://github.com/rubygems/rubygems.org/blob/9f0c284991e9f236c604cb04e221da70970fcbdd^/public/javascripts/application.js
- Now I do a blame on the file, and see that who added the `$('#version_for_stats').change(function()` line was 7dbf529.

**Comment by nateberkopec** [comment]
@arthurnn 

> I saw that file used to be public/javascripts/application.js before that commit, so I opened it up that with the url: https://github.com/rubygems/rubygems.org/blob/9f0c284991e9f236c604cb04e221da70970fcbdd^/public/javascripts/application.js

How did you know to open it at *that* particular blob? This was the step I missed.

**Comment by arthurnn** [comment]
I know the file was changed on `9f0c284991e9f236c604cb04e221da70970fcbdd` , So I use `9f0c284991e9f236c604cb04e221da70970fcbdd^` in the URL, to point to the parent commit.(note the `^` on the URL)

**Comment by nateberkopec** [comment]
>  in the URL, to point to the parent commit.(note the ^ on the URL)

Ding! Nice. Github has a damn powerful Web UI.

**Comment by olivierlacan** [comment]
@nateberkopec @arthurnn A nifty little keyboard shortcut would be neat to access this but in the meantime I find @chancancode's Blame Parent extension way easier to use: https://github.com/chancancode/blame_parent

**Comment by dwradcliffe** [comment]
So many good tips in this thread. :100: Thanks guys!

**Pull request merged**
