### PR TITLE
Changing CSS from wordbreak to overflow-x. #941

### PR DESCRIPTION
**Pull request by jdax**
I changed the css in org.css for the profile_header_name from wordbreak to overflow-x: scroll;

Please let me know if you would like something different!

### CODE REVIEW

**Comment by jdax** [comment]
And I found a browser this doesn't work well in. Will be submitting with a fix this evening.

**Comment by jdax** [comment]
screen shot 2015-07-08 at 1 22 34 pm
screen shot 2015-07-08 at 1 22 48 pm
screen shot 2015-07-08 at 1 22 57 pm

This fixes it. It is putting in a horizontal scroll for the username.

**Comment by qrush** [comment]
:+1: What's going on with the header and your avatar?

**Comment by qrush** [comment]
Ah ha, same issue up there too if your username is long enough. Up for fixing that too @jdax?

screen shot 2015-07-14 at 3 15 00 pm

**Comment by jdax** [comment]
I'll be on it!

**Comment by qrush** [comment]
We can fix that in a separate issue. Merging this in for now! @jdax thanks again.

**Pull request merged**
