### PR TITLE
fix missing dependency name bug

### PR DESCRIPTION
**Pull request by farukaydin**
Fixes https://github.com/rubygems/rubygems.org/issues/948

@sferik @arthurnn @qrush

### CODE REVIEW

**Comment by qrush** [comment]
A few thoughts:

1. Nice work!
2. How many dependencies do we have in this state? Should be able to check from the [db dump](https://rubygems.org/pages/data).
3. Can we reject gems in the future if the dependency name is blank, and consider adding a non-null/blank requirement to that column?

**Comment by farukaydin** [comment]
@qrush thanks for comment. I checked with current db dump and there are 49 dependencies in this state among 2992340 others. I'm not sure about rejecting gems in the future because of low volume, but either way I'll be happy to contribute.

**Comment by arthurnn** [comment]
I think this fixes the problem right now, only for the UI, which is a win. 
However I agree with @qrush , we should add should add a not null constraint for that in the db. For that we will need to fix those 49 cases and add the migration. @farukaydin if you are interested go ahead and work on it, otherwise I will open an issue for it, let me know

thanks

**Comment by farukaydin** [comment]
@arthurnn thanks.

Okey I will send PR for the changes you mentioned.

**Comment by sferik** [comment]
> However I agree with @qrush, we should add should add a not null constraint for that in the db.

Does that mean if someone tries to yank a gem that another gem depends on, yanking would fail? If so, I don’t think that’s a good idea.

**Pull request merged**
