### PR TITLE
Fixes layout in navigation bar

### PR DESCRIPTION
**Pull request by davydovanton**
### Description

Fixes layout in navidation bar (referer #797), namely:
- Remove dropdown arrow to right (now this arrow is located beside profile link for mobile version)
- Deleted excess `span` html tags in the profile link (it's need for alignment links in navbar)
- Replaced all hash rockets in file to the new hash style

#### Before
screenshot 2015-02-10 10 34 41
screenshot 2015-02-10 10 35 15

#### After
screenshot 2015-02-10 10 35 27

**P.S.:** Sorry, but i can check this changes only in Chrome, Firefox and Safary on mac (mac os 10.10.2 version)
**P.P.S.:** If you want i can push this PR to stage server :innocent:

### CODE REVIEW

**Comment by davydovanton** [comment]
@acacheung sorry, but what about this PR?

**Comment by acacheung** [comment]
will review by tomorrow :smile:

**Comment by davydovanton** [comment]
okay, i'll be waiting :blush:
thanks! :tada:

**Comment by acacheung** [comment]
@davydovanton seems like the rest of the app still uses the hash rocket syntax. if you are going to change it, you should do it all in another pr and change it app-wide for consistency. Other than that the changes look good

**Comment by davydovanton** [comment]
@acacheung Thanks for review my code :tada: 
About hash rokets: okey, I can create another PR where fix this in all files.

**Comment by davydovanton** [comment]
@acacheung and i revert last commit :smiley:

**Comment by davydovanton** [comment]
thank you very much :star2: :tada: :star2:

**Pull request merged**
