### PR TITLE
Replace rr gem with mocha mock

### PR DESCRIPTION
**Pull request by u2**

### CODE REVIEW

**Comment by sferik** [comment]
Can you say a bit more about why this is an improvement?

It looks like `rr` was [abandoned](https://github.com/rr/rr/commit/885885ca0cd426ea5c35fa3851abefe3d3a78428) by Elliot Winkler in December 2014 but has since been [adopted](https://github.com/rr/rr/commit/de7172967b8c0a0fc32ae3d6c0b6b1be3980804d) by @kou. There hasn’t been an `rr` gem release in almost two years, but the last `mocha` gem release was also over a year ago.

Anyway, it’s not clear to me that this is an improvement. If you’d like this pull request to be accepted, please make a case for it because it is not self-evidently better, just from looking at the code.

**Comment by sferik** [comment]
Sorry, I just noticed https://github.com/rubygems/rubygems.org/issues/981. In the future, please cross-reference issues with their corresponding pull requests. Thanks for submitting this patch!

**Comment by arthurnn** [comment]
why did we have to add `bourne` gem?

**Comment by simi** [comment]
@arthurnn to get `assert_received` method for tests.

**Comment by farukaydin** [comment]
@arthurnn without using bourne, lets say we can test ```Download.count``` method is called like
```ruby
should "load up the downloaded gems count" do
  Download.expects(:count).once
  get :index
end
```
However, in such cases we generally use index request inside of setup block, and we have to duplicate index request to every single test that have ```assert_received``` or I'm not sure but we can use something like before should or before test.

**Pull request merged**
