### PR TITLE
Reject blacklisted gem on API

### PR DESCRIPTION
**Pull request by aycabta**
[Blacklisted gem's web page says "This namespace is reserved by rubygems.org."](https://github.com/rubygems/rubygems.org/blob/e6e0bff13eb1ac2955daaa34df6b0cd385c85b29/test/functional/rubygems_controller_test.rb#L466-L475), but API not yet. So you can install a gem what has the same name as built-in library. For example, RubyGems.org has [`fileutils` gem](https://rubygems.org/gems/fileutils/versions) what has no relation with built-in library, so `gem install fileutils` breaks your Ruby system. This Pull Request is for rejection blacklisted gem on RubyGems.org API.

You can use force mode to access blacklisted gem with GET `force=true` parameter. I think it's necessary for `gem` command.

### CODE REVIEW

**Comment by dwradcliffe** [comment]
Why do we need the force param?

**Comment by aycabta** [comment]
RubyGems.org [doesn't show a blacklisted gem page](https://rubygems.org/gems/fileutils), but [shows its versions page](https://rubygems.org/gems/fileutils/versions/). I think this is not absolutely removed from RubyGems.org. So I added force param.

What do RubyGems.org team think about this?

**Comment by aycabta** [comment]
The goal of this Pull Request is just byapassed auto-dependencies resolution for what have the same name with built-in libraries. I think the gems what have the same name with built-in libraries don't be destroyed *at this time*, it's yet another matter.

**Comment by sonalkr132** [comment]
@aycabta Thank you for bringing this up. Generally, we blacklist gem name after the original one was yanked(if one existed). Following names seem to be marked *reserved* before the hosted gem was yanked: 
```
coverage
digest
english
etc
expect
fiber
fileutils
logger
matrix
monitor
observer
prettyprint
prime
profile
profiler
ruby
sync
thread
timeout
un
webrick
```
I think filtering with regex is only a temporary solution. Those gems need to be yanked.

**Comment by hsbt** [comment]
Hi, I'm extracting standard library to RubyGems on development branch on Ruby core. So Ruby 2.5 will host many gems extracted standard libraries. I hope to transfer ownership of [these gems](https://github.com/rubygems/rubygems.org/pull/1568#issuecomment-281579226) to me.

@dwradcliffe Could you make me to a new owner of these gems? Do I need to ask original authors of these gems?

After that, I will create pull request remove these gems from blacklist of rubygems.org.

**Comment by hsbt** [comment]
See details: https://bugs.ruby-lang.org/issues/5481

**Comment by aycabta** [comment]
> I hope to transfer ownership of [these gems](https://github.com/rubygems/rubygems.org/pull/1568#issuecomment-281579226) to me.

I think this Pull Request is very workaround, so it's great!

**Comment by dwradcliffe** [comment]
> Could you make me to a new owner of these gems? Do I need to ask original authors of these gems?

@hsbt Yeah I think we need to talk to the owners of those gems first.

**Comment by greysteil** [comment]
Any update on this? Just bit me on `sidekiq-pro`...

**Comment by aycabta** [comment]
I think what this Pull Request is already unnecessary because [almost reserved gems are gemificated](http://rubykaigi.org/2017/presentations/hsbt.html). I'll close after what I talk about this with @hsbt at RubyKaigi.

**Comment by aycabta** [comment]
OK, this was [for Gemification](https://bugs.ruby-lang.org/issues/5481) and it almost finished. So this Pull Request is already unnecessary.

**Pull request closed without merging**
