### PR TITLE
Remove reserved names for Ruby 2.8/3.0

### PR DESCRIPTION
**Pull request by hsbt**
The ruby core team have a plan to extract stdlib to rubygems as `the default gems`.

I removed 1st group for the Ruby 2.8/3.0 from the reserved names. 

Can anyone merge this? And Can you notify me before deploy it? Because I must push the same time for reserving them on the rubygems.org.

Thanks!

### CODE REVIEW

**Comment by hsbt** [comment]
I'm happy to deploy this between UTC 0:00 to 10:00(JST 9:00 to 19:00).

**Comment by dwradcliffe** [comment]
Assigning to @colby-swandale due to timezone.

**Comment by hsbt** [comment]
@dwradcliffe Thanks!

@colby-swandale Can you work this?

**Comment by colby-swandale** [comment]
I will merge this now and push it to staging. Let me know what time works.

**Comment by hsbt** [comment]
Thanks! I'm waiting now.

**Comment by colby-swandale** [comment]
@hsbt apologies, we currently can't deploy to production due to an issue with Shipit. I will try again tomorrow.

**Comment by hsbt** [comment]
I see. No problem. I'm also waiting the same time. Thanks for your work.

**Comment by hsbt** [comment]
@headius I'm going to release the default gems after deploying this.

**Comment by colby-swandale** [comment]
@hsbt we've resolved our issue with Shipit if you want me to deploy the changes now.

**Comment by hsbt** [comment]
@colby-swandale Thanks! Can you deploy it with daytime at tomorrow?

**Comment by colby-swandale** [comment]
Sure! 👌 Just ping me here/slack when you're ready.

**Pull request merged**
