### PR TITLE
lets just use git for Travis

### PR DESCRIPTION
**Pull request by joshk**

### CODE REVIEW

**Comment by dwradcliffe** [comment]
Thanks @joshk!

**Comment by sferik** [comment]
@joshk Is the tarball strategy broken? That seemed to be much faster for us.

**Comment by dwradcliffe** [comment]
@sferik All the builds were erroring, possibly from rate limiting. See: https://twitter.com/roidrage/status/553212064802828289

**Comment by joshk** [comment]
And using git clone vs tarball seems to be the same.




Do you have some example of the faster builds?

**Comment by sferik** [comment]
If it’s the same, then no problem.

**Comment by arthurnn** [comment]
maybe related to https://github.com/rubygems/rubygems.org/tree/master/vendor folder been huge, and git commits that touch there are big too.

**Comment by arthurnn** [comment]
actually if travis do a clone using `--depth 1` everything should be the same size.

**Pull request merged**
