### PR TITLE
Show some links after all versions are yanked

### PR DESCRIPTION
**Pull request by aycabta**
Currently, some links in gem page (owner, homepage and others) are not shown when the message <q>This gem is not currently hosted on RubyGems.org.</q> (`not_hosted_notice`) or <q>This namespace is reserved by rubygems.org. Contact rubygems team if you would like to take over this namespace</q> (`reserved_namespace`) is shown. I think it is problem bacause nobody can know who the owner is.

### CODE REVIEW

**Comment by indirect** [comment]
@aycabta I am not sure this makes sense. When either of those messages are shown, the gem has no owner at all.

**Comment by aycabta** [comment]
@indirect

> When either of those messages are shown, the gem has no owner at all.

No, `not_hosted_notice` or `reserved_namespace` is shown [when `@rubygem.public_versions.count.zero?` is true](https://github.com/rubygems/rubygems.org/blob/50aa7dc8bd27eb5305da2a10664e9136f1bbe3da/app/views/rubygems/show.html.erb#L13-L21).

You can reproduce it on development environment:

1. [Setup](https://github.com/rubygems/rubygems.org/blob/master/CONTRIBUTING.md#development-setup) and `bin/rails s`
1. Sign up on `localhost:3000` and get authorization key: `curl -u username https://localhost:3000/api/v1/api_key.yaml`
1. Make ready test gem and release it to local:3000
1. Yank (delete) the version, example: `curl -X DELETE -H 'Authorization:key_what_is_got_above' -d 'gem_name=testgem' -d 'version=0.0.1' https://localhost:3000/api/v1/gems/yank`

The gem has one owner and no versions. In this case, `@rubygem.public_versions.count.zero?` is true, so `not_hosted_notice` is shown at first (`Rubygem#pushable?` is true), `reserved_namespace` is shown after 100 days later. Please check [`Rubygem#pushable?`](https://github.com/rubygems/rubygems.org/blob/2646bea5e81012270d42988b957778f9f9606318/app/models/rubygem.rb#L184-L186) and [`Rubygem#not_protected?`](https://github.com/rubygems/rubygems.org/blob/2646bea5e81012270d42988b957778f9f9606318/app/models/rubygem.rb#L270-L272).

**Comment by indirect** [comment]
@aycabta sorry I wasn't clear—technically in the database the gem does have an owner, but that owner is not able to do anything. New versions of the gem cannot be pushed by anyone, including that owner. Later, after the namespace has been released, anyone can push a new version of that gem and become the new owner, without permission from the previous owner. That is why I don't understand how it is useful to show the owner listen in the db.

**Comment by aycabta** [comment]
First, the gem what all versions are yanked shows only `not_hosted_notice` (within 100 days) or `reserved_namespace` (after 100 days later). There are no links about the gem.

All versions are yanked

The owner(s) can push new version in this status. So I want to join in the owners of the gem, but I have no way to know who the owner is, so I can not contact the owner.

All versions are yanked and show some links

This branch shows the owner (and other some links), so I can contact existing owners. If the owner add me to new owner, I can take over the gem and push new versions.

**Comment by sonalkr132** [comment]
Hi @aycabta,

Thank you bringing this up. I have opened #1413. I hope it correctly describes the situation you are trying to explain :smiley:

**Comment by indirect** [comment]
Hi @aycabta! After thinking about it some more, it actually seems okay and maybe even good that the original owner can still push new gems or add owners to a reserved gem. I would like to update the language to clarify, rather than remove the ability of an owner to make changes:

> This gem previously existed, but has been removed by its owner. The RubyGems.org team has reserved this gem name for X more days. After that time is up, anyone will be able to claim this gem name using `gem push`.
> If you are the previous owner of this gem, you can change ownership of this gem using the `gem owner` command. You can also create new versions of this gem using `gem push`.

**Comment by aycabta** [comment]
@indirect OK. Anyway, I created [new other branch about new messages](https://github.com/aycabta/rubygems.org/commits/new-messages-for-all-versions-are-yanked) (that is added [08738e1](https://github.com/aycabta/rubygems.org/commit/08738e1ed636ce086da923dcccda72740927d67d) and [f3ca3d6](https://github.com/aycabta/rubygems.org/commit/f3ca3d655855e92d2533cf30bd819f0504f45f37)). If this has no problem, I'll merge it to this Pull Request's branch.

I roughly grasped [the policy of support team that abandoned gem don't be deleted](http://help.rubygems.org/discussions/problems/21676-id-like-to-take-over-an-unused-gem-name-dj). So I agree to delete contact link from the message.

**Comment by sonalkr132** [comment]
@aycabta Why did you have to move so many things around? My instinct says it won't need 124 lines :sweat_smile:  of change.
If you had unrelated reason for the changes made can you please open a new issue or even better send another PR :heart:

**Comment by aycabta** [comment]
@sonalkr132 Because indent depth of many lines are changed. I think it's very helpful for readability.

**Comment by sonalkr132** [comment]
I would like to suggest that instead of using
```Ruby
if @latest_version && @latest_version.indexed
```
everywhere, you can refactor it in partials and use a new template for reserved namespace. rubygems show page is complex enough, I would prefer not to add anymore :exclamation:

**Comment by aycabta** [comment]
The first goal of this Pull Request is that some links are shown after all versions are yanked. I think `app/views/rubygems/show.html.erb` is complex enough too. New template idea sounds good.

**Comment by aycabta** [comment]
I pushed [a commit](https://github.com/aycabta/rubygems.org/commit/fafb665cad2bb5b6682afee1b3441f130f943100) to [new messages branch](https://github.com/aycabta/rubygems.org/commits/new-messages-for-all-versions-are-yanked) because [I mistook](https://github.com/aycabta/rubygems.org/commit/08738e1ed636ce086da923dcccda72740927d67d#commitcomment-18962698).

**Comment by aycabta** [comment]
This branch is dirty because there are some reverts as a result of the discussion (and I pressed "Update branch" button by mistake). I cleared up and create new Pull Request: https://github.com/rubygems/rubygems.org/pull/1419.

**Pull request closed without merging**
