### PR TITLE
Upgrade Ruby (3.2), RubyGems (3.4.3), Bundler (2.4.3) and Nokogiri (1.14.0)

### PR DESCRIPTION
**Pull request by simi**

### CODE REVIEW

**Comment by simi** [comment]
@jchestershopify :ping_pong:

**Review by jchestershopify — COMMENTED** [review]
Thanks for the assist on Nokogiri! LGTM.

**Comment by simi** [comment]
:information_source: merging for staging testing

**Comment by jchestershopify** [comment]
Looked good in some manual testing that @jenshenny and I did last week. I think we'd be safe to go to production.

**Comment by simi** [comment]
Let's do that @jchestershopify :muscle:.

**Pull request merged**
