### PR TITLE
Addressing issue #536 but w/ another question.

### PR DESCRIPTION
**Pull request by elight**
Also begs the question: if we're including *some* version information in the response,
and the response previously contained a JSON-ified Rubygem, should we just augment
the response to contain a :version key containing a JSON-ified Version object
representing the latest update?

Paired w/ Bryan Schoeff

### CODE REVIEW

**Comment by davefp** [comment]
@elight As a result of #610 a large chunk of the repo's history was re-written. Please rebase your PR so that it will merge cleanly. Thanks!

(There are further details on the blog: http://blog.rubygems.org/2015/02/01/rewriting-history.html)

**Comment by elight** [comment]
@davefp Will it get merged if it's rebased? I made this PR so long ago I don't even remember it...

**Comment by elight** [comment]
@davefp Sorry. Not intended to be snarky. Just don't want to invest in something unless its valuable.

**Comment by davefp** [comment]
@elight good question. I added that comment to all open PRs (regardless of age) since it would be impossible to merge them without a rebase. @qrush @bf4 @envygeeks any thoughts?

**Comment by envygeeks** [comment]
I can't even get github to give me the PR patch to begin with to see if I could even rebase it myself and how many merge problems I would have to solve to help out.

**Comment by bf4** [comment]
I think it's just https://github.com/rubygems/rubygems.org/commit/a33a1631c5031204e91fbd654cee18d10ba04b1b the one commit

**Comment by arthurnn** [comment]
This is inactive for a while now. Please open a new PR if you are still interested in implementing this patch.

thanks

**Pull request closed without merging**
