### PR TITLE
Gems page sort by downloads again, fix scope, and add index on downloads.

### PR DESCRIPTION
**Pull request by huacnlee**

### CODE REVIEW

**Comment by huacnlee** [comment]
Ref: #1050

**Comment by dwradcliffe** [comment]
@sferik

**Comment by sferik** [comment]
Looks good to me. Do we have space to add the index?

**Comment by huacnlee** [comment]
What index?

**Comment by qrush** [comment]
That column is just an integer. Should be a pretty small index, no?

**Comment by huacnlee** [comment]
Or I remove the Index first? But I can't ensure that fast.

We can try it, if it slow, add Index after.

**Comment by huacnlee** [comment]
@qrush @sferik I have removed the index changes. let us try it.

**Comment by arthurnn** [comment]
thanks for the pr @huacnlee  . I am taking a look this weekend.

**Comment by huacnlee** [comment]
@arthurnn :smile: 1 month passed, would you please check it when you have a time.

**Comment by dwradcliffe** [comment]
Downloads count in the database isn't updated, so I don't think this will work. We're working on fixing this in https://github.com/rubygems/rubygems-infrastructure/issues/35

**Comment by arthurnn** [comment]
yeah, the downloads count on the db is out of date, as @dwradcliffe pointed out.
I will come back to this once we fix the downloads count pipeline.

thanks and sorry for the delay

**Pull request closed without merging**
