### PR TITLE
Fix admin login with same-site: strict cookies

### PR DESCRIPTION
**Pull request by segiddins**
Signed-off-by: Samuel Giddins <segiddins@segiddins.me>

### CODE REVIEW

**Comment by simi** [comment]
Is this something RubyGems.org specific @segiddins? Any idea?

**Comment by segiddins** [comment]
It's specific to using `same-site: strict` cookies with an oauth provider on a separate origin, where the oauth provider requires user interaction before redirecting to the application

**Comment by simi** [comment]
Worth to report upstream? Any chance to test? Seems easy to break again.

**Comment by segiddins** [comment]
I'm not sure how to test this bit, since it relies on https and multiple different hosts

**Review by simi — APPROVED** [review]

**Comment by simi** [comment]
> I'm not sure how to test this bit, since it relies on https and multiple different hosts

Yes, I was afraid of. Let's move forward, to unblock login.

**Pull request merged**
