### PR TITLE
Send all email using activejob

### PR DESCRIPTION
**Pull request by segiddins**
Will delete those mailer structs after deploying

### CODE REVIEW

**Comment by simi** [comment]
I have alternative take on this (I shared on Slack I'm working on this :thinking:). I'll open PR, let's decide which one to merge later.

**Comment by segiddins** [comment]
@simi I think this is green now -- do you object to us shipping it and then making other changes incrementally?

**Comment by simi** [comment]
What's wrong with https://github.com/rubygems/rubygems.org/pull/3542 @segiddins?

**Comment by segiddins** [comment]
What's wrong with this PR?

**Comment by simi** [comment]
> What's wrong with this PR?

It doesn't send all emails using activejob per my understanding. https://github.com/rubygems/rubygems.org/pull/3542 partly combines this and adds other cases.

**Comment by segiddins** [comment]
Can't we just do that in followups though?

**Review by simi — APPROVED** [review]

**Comment by simi** [comment]
> Can't we just do that in followups though?

ok, let's do that

**Pull request merged**
