### PR TITLE
Ruby 2.1.5 we are!!!

### PR DESCRIPTION
**Pull request by arthurnn**
Now that we fixed the YAML patch, we can safely upgrade to ruby 2.1.5 ! 
all tests are :green_heart: 

review @evanphx @qrush @sferik @drbrain @dwradcliffe

### CODE REVIEW

**Comment by arthurnn** [comment]
Of course, this will need to change cookbooks too. But I will leave this to you @dwradcliffe :cat:

**Comment by dwradcliffe** [comment]
Might as well remove ruby 2.0 from the travis config.

**Comment by arthurnn** [comment]
> Might as well remove ruby 2.0 from the travis config.

Thats right, done

**Comment by dwradcliffe** [comment]
:+1: Good to go on this. The servers have been updated to use 2.1.5 and everything is running smoothly!

**Comment by arthurnn** [comment]
:tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada::tada:

**Pull request merged**
