### PR TITLE
Fix some translations in ja

### PR DESCRIPTION
**Pull request by tnir**
Updates #1708

Signed-off-by: Takuya Noguchi [takninnovationresearch@gmail.com](https://github.com/sponsors/tnir)

### CODE REVIEW

**Comment by tnir** [comment]
@m1kit @igaiga Thoughts?

**Comment by tnir** [comment]
@sonalkr132 What do you think?

**Comment by simi** [comment]
Maybe @hsbt can help here as well :pray:.

**Review by hsbt — APPROVED** [review]
It's more meaningful changes. Thanks.

**Pull request merged**
