### PR TITLE
Some cleanup

### PR DESCRIPTION
**Pull request by fabianrbz**
Hi guys,

This pull request removes some unused helpers and before_filters and brings back the stats_controller_test.

### CODE REVIEW

**Comment by arthurnn** [comment]
Make sense to me :+1: .
Would like more :eyes: before merging this tho, @qrush , @sferik ?

**Comment by qrush** [comment]
None here. I miss the stats :cry:

**Comment by fabianrbz** [comment]
guys l don't know what happened, but for some reason l had to rebase this... was master force pushed?

**Comment by qrush** [comment]
Yes, as part of #610.

**Comment by fabianrbz** [comment]
nice!

**Comment by fabianrbz** [comment]
rebased!, @arthurnn @qrush l think this should be ready now.

**Comment by arthurnn** [comment]
merging this in. Thanks
If we implement back the stats per gem, we can probably revert https://github.com/fabianrbz/rubygems.org/commit/6de166eb89458edea589ffe2bd83d83e02e81d1d . 
Anyhow, the code is not used anymore, so no need to have it.

**Comment by fabianrbz** [comment]
thanks! @arthurnn why were the stats removed in the first place? and do we want them back? in that case maybe we can open an issue or add it to trello and someone can take care of it...

**Pull request merged**
