### PR TITLE
Keep original page title when GH button is rendered.

### PR DESCRIPTION
**Pull request by simi**
fix for https://github.com/rubygems/rubygems.org/pull/3118/files/e360b5b735a196fa0753472ea0a91fab505af086#diff-acf734494695689a08a046f2de07f50d018ebcc460081e28562f9bd4d8604824

/cc @tnir @jhawthorn

### CODE REVIEW

**Comment by tnir** [comment]
@simi Thanks for following up my mistake. Like #3144, we had better to add it to modifications on comments.

**Comment by simi** [comment]
@tnir comment added

**Review by tnir — COMMENTED** [review]
Looks good to me.

**Comment by simi** [comment]
:information_source: deployed

**Comment by sonalkr132** [comment]
Can someone please also look into why the arrow thingy linking the star count and star button is missing?
Screenshot-20220714172851-161x58

**Pull request merged**
