### PR TITLE
Precompile assets on CI before running tests.

### PR DESCRIPTION
**Pull request by simi**
- trying to fix https://github.com/rubygems/rubygems.org/actions/runs/6123118617/job/16620328677?pr=4055, not sure if that's related, but maybe it timeouts on precompiling assets during system tests (I wasn't able to reproduce locally)

### CODE REVIEW

**Comment by segiddins** [comment]
Are we concerned about this leading to CI having a different behavior than most people running tests locally?

**Comment by simi** [comment]
> Are we concerned about this leading to CI having a different behavior than most people running tests locally?

TBH I'm not sure. Feel free to close this if you're not 100% sure about the impact. Splitting the CI at https://github.com/rubygems/rubygems.org/pull/4059 would make it easier to detect the original problem later if merged anyway.

**Comment by martinemde** [comment]
I've done this same thing to avoid timeouts during capybara tests. Is that what this aims to fix?

**Comment by simi** [comment]
> I've done this same thing to avoid timeouts during capybara tests. Is that what this aims to fix?

Yes

**Review by martinemde — APPROVED** [review]

**Review by segiddins — APPROVED** [review]

**Pull request merged**
