### PR TITLE
Add recent uploads page

### PR DESCRIPTION
**Pull request by tadityar**
This PR adds a recent uploads page as suggested in #1217.

Continuing from #1238 by adding a new page instead of displaying the recent uploads in the stats page.

Recent Page Screenshot
screen shot 2016-09-11 at 1 04 57 pm

Link from the Stats page
screen shot 2016-09-10 at 4 19 01 am

### CODE REVIEW

**Comment by sonalkr132** [comment]
Hi @tadityar. Thanks for PR :heart_decoration: 
Can you please remove 70ec5ac?

**Comment by simi** [comment]
Hello! Nice feature!

I have few notes and ideas about this.

Since this is not statistic, I think it can be moved to own controller. Also `@recent_uploads` in controller can be cached easily, but I'm not sure if that's worth it.

Since this was moved to own page maybe the limit can be a little bigger (25?) and IMHO it will be interesting to show upload time.

**Comment by tadityar** [comment]
Hi @simi! Thanks for the feedback, yeah since 'recent uploads' is not really statistic I'll move it to another controller. I don't know about the rate new gems are being uploaded to rubygems so I have no opinion about caching.

Showing upload time crossed my mind when doing this PR but since the original issue thread mentioned it being simple I didn't do it. It was before they decided to move this to a separate page though! So maybe now that we have a page just for this might as well!

**Comment by simi** [comment]
@tadityar to get idea how often are gems pushed you can inspect https://twitter.com/rubygems. I'm not sure how performing the current SQL query is. Let me try to find out using [real data set](https://rubygems.org/pages/data).

**Comment by arthurnn** [comment]
I don't know how real time those pages need to be.
If the query is a bit slow, but we still can execute it, I am OK with this, and we could push that page under a cached version with a expiring time of 5 minutes?

**Comment by jvanbaarsen** [comment]
@tadityar Are you still working on this? I think it would be a nice feature to have!

**Comment by sonalkr132** [comment]
closing because of inactivity.

**Pull request closed without merging**
