### PR TITLE
add ping endpoint

### PR DESCRIPTION
**Pull request by dwradcliffe**
Adds a ping endpoint that can be used by internal and external monitoring.

r: @evanphx @qrush @arthurnn

### CODE REVIEW

**Comment by anoldguy** [comment]
Hey, you might be interested in Easymon: https://github.com/basecamp/easymon

I wrote it for just this scenario. We use it for load balancer health checks.

**Comment by qrush** [comment]
Any thoughts on easymon, @dwradcliffe ? Been using it for years at Basecamp. If we just want to stay small to start that's fine too.

**Comment by dwradcliffe** [comment]
Looks like a nice gem but I think I'd rather start small and add that if we need it later.

**Comment by arthurnn** [comment]
:ship:

**Pull request merged**
