### PR TITLE
Add Rack-UTF8Sanitizer

### PR DESCRIPTION
**Pull request by dwradcliffe**
Supersedes #1254 

@bf4 @indirect @segiddins

### CODE REVIEW

**Comment by sonalkr132** [comment]
Invalid utf-8 in GET request is fixed on rails 5 https://github.com/rails/rails/commit/59ab2d1ee5995d9ea27ca60e92576518c1898c59. I was yet to verify what goes wrong in POST request :postbox: They even have a [test for invalid utf-8 in POST request](https://github.com/rails/rails/blob/59ab2d1ee5995d9ea27ca60e92576518c1898c59/actionpack/test/dispatch/request_test.rb#L993-L1005).
Also, to be noted.. Rack-UTF8Sanitizer lets the request through (probably after sensitization), when convention (and what rails does) is to [respond with BadRequest](https://github.com/rails/rails/commit/d59a24d543b4fd34d453e8209caae5fef315ea78#diff-3179d24efacadd64068c4d9c1184eac3R296).

**Comment by dwradcliffe** [comment]
I'm ok changing this later, I just wanted to get something out that silences the errors. And I think I'm ok with either approach. We can revisit when we're ready for Rails 5.

**Comment by bf4** [comment]
@dwradcliffe Thanks for bring this home

**Comment by bf4** [comment]
@sonalkr132 deciding if it should be a BadRequest is definitely and interesting discussion. I'd make the case that it's better to try to accept data coming in than be strict in rejecting it.

One difference, I think, in Rack-UTF8Sanitizer compared to other similar middlewares or libraries, is that it is very specific about what it looks at and what it changes.

**Pull request merged**
