### PR TITLE
Improving pt-BR translation

### PR DESCRIPTION
**Pull request by lucianosousa**
Add couple missing translations

### CODE REVIEW

**Comment by lucianosousa** [comment]
@nettofarah can you take a look, please?

**Comment by lucianosousa** [comment]
@nettofarah updated. let me know if looks good! ;) thanks for the review

**Comment by lucianosousa** [comment]
@sonalkr132 reviewed

**Comment by sonalkr132** [comment]
Thanks @lucianosousa @nettofarah :world_map:

**Pull request merged**
