### PR TITLE
Enable announcements only when table exists

### PR DESCRIPTION
**Pull request by spk**
With production dump from [data] this table does not exist.

[data]: https://rubygems.org/pages/data

### CODE REVIEW

**Comment by dwradcliffe** [comment]
:-1:

I understand why you want this, but I'd rather not add conditionals like this all over the place. I would however, love to see better seed data for development. Even a rake task to fill in the missing tables might be ok.

**Comment by spk** [comment]
Yes you are right @dwradcliffe, it is not a good idea.
Do you know why also the table `SchemaMigration` is not present in this dump ?

**Comment by spk** [comment]
I document a way to have a usable production database locally.

**Comment by dwradcliffe** [comment]
I bet there are changes to those tables since the original migrations. I think a better plan would be to run `./script/setup` and then import the production dump over top of it. I just tested that and although I did get some errors, it seemed to work. Can you try that?

**Comment by spk** [comment]
Yes it work fine in this way! Thanks for your help!

**Pull request closed without merging**
