### PR TITLE
Replace quiet_assets gem with sprockets-rails 3.1.0 config

### PR DESCRIPTION
**Pull request by kmcphillips**
@sonalkr132 @dwradcliffe 

You can rebase https://github.com/rubygems/rubygems.org/pull/1341 over this to simplify it a bit. Part of the Rails 5 upgrade.

Replaces `quiet_assets` with config in `sprockets-rails`. Bumps the `sprockets-rails` version to `3.1.0` to include the feature. https://github.com/rails/sprockets-rails/pull/355

### CODE REVIEW

**Comment by dwradcliffe** [comment]
👍

**Comment by sonalkr132** [comment]
This doesn't work in rails 4 :sweat:

**Comment by kmcphillips** [comment]
I should have waited for `4.2.7`. There's a bug in `ActiveSupport::Logger#silence` that prevents this from also silencing the console (it silences the log file) that has been backported to `4-2-stable`.

**Comment by kmcphillips** [comment]
https://github.com/rails/rails/pull/25341

**Pull request merged**
