### PR TITLE
Remove SimpleSSLRequirement and replace with force_ssl.

### PR DESCRIPTION
**Pull request by nateberkopec**
* Remove unneccessary ssl requirement lines from Clearance controllers.
* force_ssl adds HTTP Strict Transport Security (HSTS)
* Adds ActionDispatch::SSL middleware, which will short-circuit HTTP requests slightly faster than doing it at the Rails application level.
* force_ssl automatically sets cookies to secure where required.

*As far as I can tell*, this shouldn't change anything except adding the HSTS header.

### CODE REVIEW

**Comment by dwradcliffe** [comment]
@nateberkopec Thanks for working on this!

We can't currently enable HSTS because we don't force ssl for every request to rubygems.org. It's definitely not clear from looking at the application code, but we still allow http requests to download gems without forcing a redirect to https.

Is there a way to disable HSTS?

**Comment by nateberkopec** [comment]
@dwradcliffe Can you be clear about what requests to this application don't require https? The problem is that HSTS is a "domain-level" setting basically right? If I understand HSTS correctly, we're telling the client, hey, don't ever request stuff from rubygems.org insecurely. Which doesn't sound like it's true.

In any case, I can disable HSTS.

**Comment by dwradcliffe** [comment]
The simplest answer is `http://rubygems.org/gems/*.gem` although there are other urls as well. And yes, HSTS is domain level - all or nothing.

**Comment by nateberkopec** [comment]
@dwradcliffe Dropped HSTS. This will still redirect all requests to this application to the HTTPS url, which, as far as I can tell, was exactly what it was doing before (since everything inherits from ApplicationController).

**Comment by dwradcliffe** [comment]
Cool thanks. I'll review tomorrow but I think this looks good.

**Comment by arthurnn** [comment]
I will do some local tests with this before merging it.. but as far as I can tell it looks good.
thanks for the PR

**Comment by dwradcliffe** [comment]
@nateberkopec Can you rebase on master? I think you might need to adjust this because of this commit https://github.com/rubygems/rubygems.org/commit/60eb5c85ec00087648935d45854641a9525e6228.

**Comment by nateberkopec** [comment]
@dwradcliffe done https://github.com/rubygems/rubygems.org/pull/1083/files#diff-e621685ac1c2689eaedaedf334c6123bL31

**Comment by arthurnn** [comment]
thanks @nateberkopec !

**Comment by sonalkr132** [comment]
> This will still redirect all requests to this application to the HTTPS url, which, as far as I can tell, was exactly what it was doing before (since everything inherits from ApplicationController).

Apologies for digging this up, however, this was not true. In `Api::BaseController` we had `skip_before_action :require_ssl` [[1](https://github.com/nateberkopec/rubygems.org/blob/be8d688dbb0d567aa57f752f538a1130df236022/app/controllers/api/base_controller.rb#L4)]. 
I doubt we will disable redirect now. I think we should add non-https host tho.
Related: https://github.com/rubygems/rubygems/issues/4191

**Pull request merged**
