### PR TITLE
Use ruby version 2.5.3

### PR DESCRIPTION
**Pull request by mjankowski**
Resolves https://github.com/rubygems/rubygems.org/issues/1780

### CODE REVIEW

**Comment by connorshea** [comment]
2.5.2 is out now, btw :)

https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-5-2-released/

**Comment by mjankowski** [comment]
I'll update with 2.5.3 once it hits my package manager - https://www.ruby-lang.org/en/news/2018/10/18/ruby-2-5-3-released/

**Comment by dwradcliffe** [comment]
If you rebase on master the build should be fixed

**Comment by dwradcliffe** [comment]
Thanks for your patience here. I will be merging this in the next few days. 
(And future updates won't require waiting for server changes 🎉)

**Comment by connorshea** [comment]
@dwradcliffe awesome! Thanks for you work on RubyGems ❤️ Happy new year!

**Pull request merged**
