### PR TITLE
Adding link to report abuse on gems

### PR DESCRIPTION
**Pull request by bradly**
This is based on the discussion in #608

### CODE REVIEW

**Comment by arthurnn** [comment]
At first look, code looks good. I wonder if we want a different UI for the report link tho. ?!?

**Comment by bradly** [comment]
@arthurnn Yeah, not sure. Is there a designer I can mention and have him/her review? Otherwise, I do think that having the link as-is is still an improvement  even if is not an ideal design, but I'm good either way :)

**Comment by dwradcliffe** [comment]
@acacheung

**Comment by bradly** [comment]
@acacheung Any design feedback? Here is a screenshot so you can easily see the new link "Report Abuse" at the bottom of the links section. http://cl.ly/image/3g2h2D2G3t3F

**Comment by arthurnn** [comment]
I will give this a merge, and we can make the UI better. At least if it is live people will see it and make it better...
thanks all

**Comment by qrush** [comment]
Fantastic. Ship it!

**Pull request merged**
