### PR TITLE
fill locales with script

### PR DESCRIPTION
**Pull request by dorianmariefr**

### CODE REVIEW

**Comment by dorianmariefr** [comment]
it's much simpler, looks like `i18n-tasks add-missing` tries to guess from my code which keys are missing and adds humanized values.

But I get a bunch of new keys I don't need and is pretty much incorrect.

Here I just add nil values for keys that are in the reference locale (en)

**Comment by sonalkr132** [comment]
This seems fine to me. I hope you were careful to not change any existing translation or there were no issue of fonts not present on your system.
I would also add doc about this script in contributing.md

**Comment by dorianmariefr** [comment]
@sonalkr132  ok, I've added a bit of documentation, would you rather I add the script and you run it on your machine?

**Comment by sonalkr132** [comment]
I did run it locally. The only change I got was that it added space after all the empty keys. Can we please update it not add space?
```diff
+++ b/config/locales/de.yml
@@ -1,35 +1,35 @@
 ---
 de:
   edit: Bearbeiten
-  failure_when_forbidden:
+  failure_when_forbidden: 
   feed_latest: RubyGems.org | Neueste Gems
   feed_subscribed: RubyGems.org | Abonnierte Gems
-  footer_about_html:
-  footer_sponsors_html:
-  footer_join_rt_html:
+  footer_about_html: 
+  footer_sponsors_html: 
+  footer_join_rt_html: 

```

**Review by sonalkr132 — CHANGES_REQUESTED** [review]
ping

**Comment by dorianmariefr** [comment]
weird, I don't have the extra spacing locally, maybe you are using a different YAML gem and/or version

I added a line to the script to remove extra spaces

**Review by sonalkr132 — APPROVED** [review]

**Comment by sonalkr132** [comment]
Great. thanks :+1: 
Another nice improvement could be to recommend running this script if test for i18n keys fails.

**Pull request merged**
