### PR TITLE
Add Ruby head to Travis build

### PR DESCRIPTION
**Pull request by nicolasleger**

### CODE REVIEW

**Comment by arthurnn** [comment]
Thanks for the PR.
Not sure why we would want test against ruby-head. rubygems.org is a server side code, so we control the environment, (different then when you are writing a gem/client). That said, we have 2 ruby builds, one which is the main one we use on production, and one level up, so we can know if we can upgrade or not.

**Comment by nicolasleger** [comment]
You're right. The advantage would be to anticipate further broken things but I agree that it might be too soon.

**Comment by sferik** [comment]
I would be :+1: adding it if [`allow_failures`](http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail) was set for that build.

**Comment by arthurnn** [comment]
Sounds good to me, @nicolasleger pourriez-vous ajouter le `ruby-head` à le `allow_failures` . Merci

**Comment by nicolasleger** [comment]
@sferik and @arthurnn Alright, done !

**Pull request merged**
