### PR TITLE
Update CI to Ubuntu 22.04.

### PR DESCRIPTION
**Pull request by simi**
~~:information_source: Originally I tried to upgrade to Ubuntu 22.04, but there were problems with OpenSSL 3.0. It seems some API was removed with proper replacement. I have asked at https://github.com/ruby/openssl/pull/480#issuecomment-1221416750 for more info.~~

~~For now, we can (at least) migrate to Ubuntu 20.04, since Ubuntu 18.04 is deprecated for GitHub Actions.~~

https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

### CODE REVIEW

**Comment by simi** [comment]
:information_source: blocked until new Alpine release with OpenSSL 3

**Comment by simi** [comment]
:information_source: last OpenSSL problem was fixed at https://github.com/ruby/openssl/pull/541 and is included in latest release. But I'm not still sure if there is any value in this PR. :thinking:

**Comment by simi** [comment]
I'm not sure it is worth it to add `openssl` into Gemfile manually. We will get last `openssl with next Ruby release as well (https://github.com/ruby/ruby/pull/6337). IMHO it is ok to wait for that and move to Ubuntu 22.04 at CI with next Ruby upgrade. WDYT?

**Comment by jenshenny** [comment]
Gotcha! Thanks for providing that info, I think we can wait for the next Ruby release then too 👍

**Comment by sonalkr132** [comment]
Unless this resolves a security issue in prod, we shouldn't have to update.

**Comment by simi** [comment]
I'll strip down this PR to just update the CI runners. OpenSSL would get pulled in in https://github.com/rubygems/rubygems.org/pull/3337/files (on both sides, into app as default gem and also into docker container using Alpine 3.17 if I understand it well).

**Comment by hsbt** [comment]
👍  There is only concern about Ubuntu 22.04 with Ruby 3.0. The current ruby version is 3.1, There is no reason to stay Ubuntu 20.04.

**Pull request merged**
