### PR TITLE
Add change log links to gem page

### LINKED ISSUE #578: Link to a change log from gem page
I think gem pages should include or at the very least link to change log information about releases (versions). 

Here's what it could look like: 
image

Note: I've edited this original post after the fact, so the comments from @evanphx and @gaurish are not really relevant anymore. Sorry.

### PR DESCRIPTION
**Pull request by olivierlacan**
This adds a new changelog column to the linksets table and displays
that change log alongside the existing linkset links.

image

This is a draft, there may be tests we haven't thought of updating with @jaymcgavren but we will if necessary.

Fixes #578

### CODE REVIEW

**Comment by kbrock** [comment]
:+1: to adding it to the metadata

**Comment by igrep** [comment]
:+1: I expect this feature to be merged! It'll make much easier to see a new version's change before updating the gem. :pray:

**Comment by olivierlacan** [comment]
Makes sense to me. Will update soon.

**Comment by kbrock** [comment]
@olivierlacan when this merges, can you double check that #724 adds `changelog_uri` key?

OTOH, if #724 goes through first, I will ping you so you can add the `changelog_uri` key to the new metadata hash.

**Comment by davefp** [comment]
@olivierlacan As a result of #610 a large chunk of the repo's history was re-written. Please rebase your PR so that it will merge cleanly. Thanks!

(There are further details on the blog: http://blog.rubygems.org/2015/02/01/rewriting-history.html)

**Comment by kbrock** [comment]
After 724 goes through, I'll rebase this one.

**Comment by olivierlacan** [comment]
@kbrock I'm going to entirely re-commit this PR with master so I can make it easily mergeable into #724 when that's done.

**Comment by kbrock** [comment]
@olivierlacan I was thinking that we would not add changelog in the form. Just read it out of the meta-data.

I think it would be great if the gemspec were the source for all gem metadata. Did you have something similar in mind?

**Comment by olivierlacan** [comment]
@kbrock Oh yeah, my bad. I'll nix that.

**Comment by olivierlacan** [comment]
@kbrock Just force-pushed a removal of the edit changelog input in the form.

**Comment by olivierlacan** [comment]
Rebased.

**Comment by indirect** [comment]
I am :+1: on this, reading a changelog link out of the gemspec metadata hash seems good to me.

**Comment by arthurnn** [comment]
I am also :+1: on this, however I would like us to finish https://github.com/rubygems/rubygems.org/issues/1127 first, before adding more links.

**Comment by kbrock** [comment]
@olivierlacan #1234 merged - will look into the best way of getting this in.

Do you care if there is a field on a form? Or just reading from gemset.metadata[:changelog_uri] is good enough for you?

**Comment by olivierlacan** [comment]
Weren't we trying to move away from allowing those fields to be edited on the site? I think the metadata is perfect.

**Comment by indirect** [comment]
👍

**Comment by olivierlacan** [comment]
Closing since we @kbrock made #1553 with no migration required.

**Pull request closed without merging**
