### PR TITLE
Rate limit gem push by api key and ip

### PR DESCRIPTION
**Pull request by sonalkr132**
No gem has crossed limits used here in last 6 months.
Comparing data dumps:
https://gist.github.com/sonalkr132/a324d2d64ae85e282dea6c699cd95861

[Data](https://rubygems.org/pages/data) for *download_this_gem* should be available tomorrow(14 Jan). Will verify that these limits would have been hit.

### CODE REVIEW

**Comment by sonalkr132** [comment]
@dwradcliffe do these limits[1][2] seem reasonable to you?

[1] 20 gem push per hour per ip
[2] 20 gem push per 10 min per user (api_key)

**Comment by segiddins** [comment]
[1] looks like it would be hit by something like all of the AWS gems, or even just a corporate network with a single public IP?

**Comment by sonalkr132** [comment]
Sorry @segiddins, I commented limits backward. Per ip limit is 20 push per 10 min.
One would need to check lb logs (:negative_squared_cross_mark: access) for more accurate limits.

In last 6 months, no gem has had more than 7 versions pushed under 10 min.

**Comment by sonalkr132** [comment]
just ip. I was hoping to use name too. Gem name is in the payload's gemspec, so we will either need to parse the payload redundantly in rack attack middleware or have this specific gem:ip rate limit logic in app code (`Pusher`).
Both solutions seem equally bad/unnecessary to me. IMHO, 20 push per 10 min per ip should be good enough limit to prevent abuse.

**Comment by segiddins** [comment]
`curl https://rubygems.org/names | sort | grep -Ee '^aws-sdk' | wc -l` has 180+ gems, so this might break amazon releasing new versions of the aws-sdk suite?

**Comment by sonalkr132** [comment]
Seems like they will be limited:
```
# select count(*) as num, date_trunc('minute',updated_at) as updated 
from rubygems where name ilike 'aws-sdk%' 
group by updated order by num desc;

 num |       updated       
-----+---------------------
  13 | 2018-11-20 22:16:00
  12 | 2018-11-20 22:24:00
  12 | 2018-11-20 22:18:00
  12 | 2018-11-20 22:20:00
   9 | 2018-11-20 22:22:00
   8 | 2018-11-20 22:21:00
   8 | 2018-11-20 22:19:00
   7 | 2018-11-20 22:17:00
   7 | 2018-11-20 22:23:00
   5 | 2018-11-20 22:15:00 # 93 push in 9 minutes following 22:15
   5 | 2018-11-28 01:47:00
   5 | 2018-11-26 10:26:00
```
20 push per ip per 10 min limit is in fact too low for the incident we are hoping to avoid:
```
# select id from rubygems where name ilike 'download_this%';
   id
--------
 180001

# select count(*) as num, date_trunc('minute', created_at) as created from versions 
where rubygem_id = 180001 group by created order by created desc;

 num |       created       
-----+---------------------
   2 | 2019-01-10 11:10:00
   1 | 2019-01-10 11:09:00
   1 | 2019-01-10 11:08:00
   2 | 2019-01-10 11:07:00
   1 | 2019-01-10 11:06:00
   1 | 2019-01-10 11:05:00
   1 | 2019-01-10 11:04:00
   2 | 2019-01-10 11:03:00
   1 | 2019-01-10 11:02:00
   1 | 2019-01-10 11:01:00
   2 | 2019-01-10 11:00:00 # 15 push in 10 min following 11:00
   1 | 2019-01-10 10:59:00
   2 | 2019-01-10 10:58:00
   1 | 2019-01-10 10:57:00
   2 | 2019-01-10 10:56:00
   1 | 2019-01-10 10:55:00
   1 | 2019-01-10 10:54:00
   2 | 2019-01-10 10:53:00
   1 | 2019-01-10 10:52:00
   2 | 2019-01-10 10:51:00
   1 | 2019-01-10 10:50:00
   2 | 2019-01-10 10:49:00
   1 | 2019-01-10 10:48:00
   1 | 2019-01-10 10:47:00
   2 | 2019-01-10 10:46:00
   1 | 2019-01-10 10:45:00
   2 | 2019-01-10 10:44:00
   1 | 2019-01-10 10:43:00
   1 | 2019-01-10 10:42:00
   1 | 2019-01-10 10:41:00
   1 | 2019-01-10 10:40:00 # 28 push in 20 min following 10:40
   2 | 2019-01-10 10:39:00
   1 | 2019-01-10 10:38:00
   2 | 2019-01-10 10:37:00
   1 | 2019-01-10 10:36:00
   2 | 2019-01-10 10:35:00
   1 | 2019-01-10 10:34:00
   2 | 2019-01-10 10:33:00
   1 | 2019-01-10 10:32:00
   2 | 2019-01-10 10:31:00
...
```
Not sure if it will help but we can optionally [send rate limit/quota headers to clients](https://github.com/kickstarter/rack-attack#ratelimit-headers-for-well-behaved-clients).

**Comment by sonalkr132** [comment]
I guess we need more opinion on this. IMHO, we can't accommodate all existing usage pattern (close to 100 push under 10 min for aws) and still have a rate limit which would prevent abuse.

Original proposed limit were much lower than what I have used here:
> do we have any kind of rate limiting on gem releases? maybe we should add something like one version every 2 minutes, max 10 versions a day or something?

cc: @indirect

**Comment by indirect** [comment]
I was trying to propose limits per gem name, not limits per IP or per client. I think we can either add the aws-sdk gems to an exemption list or make the client/IP limit much higher. How about:

Per name:
- 1 push per 2 minutes
- 10 pushes per 24 hours

Per IP:
- 100 pushes per 10 minutes
- 250 pushes per 24 hours

If we return status 429 with a message that tells them the limits, I think that seems fine? Anyone who is limited by that can open a ticket and we can either update the limits or add them to an exemption list.

**Comment by cjyclaire** [comment]
https://github.com/rubygems/rubygems.org/issues/2081

**Comment by simi** [comment]
:thinking: What about to introduce some kind of "verified" account status which can be enabled manually for now and do not enforce strict limits on those accounts? We can require 2FA on that kind of account to make it a little safer.

**Comment by sonalkr132** [comment]
we added gem push limit by IP with backoff. one on api_key not needed as of now.

**Pull request closed without merging**
