### PR TITLE
[WIP] Store downloads in timescale

### PR DESCRIPTION
**Pull request by segiddins**
Depends on https://github.com/crunchloop/timescaledb-rails/pull/58
RFC: https://github.com/rubygems/rfcs/pull/48

### CODE REVIEW

**Comment by jamessewell** [comment]
Is there any progress on this PR? I run Developer Advocacy at Timescale, and I'd love to help out anywhere I can! We ❤️ Ruby, and we ❤️ what RubyGems does for the ecosystem.

Looking at the [RFC](https://github.com/rubygems/rfcs/blob/ac826e97dd6573296390d2e8fa3c584b284412c8/text/0000-time-series-gem-downloads.md) drawbacks section there are several things I can assist with off the bat:

- We now have a Terraform provider ☁️
- I'm happy to chat about some sort of partnership (jsewell @ companyname)
- I'm happy to do ask an advocate to test the data compression and continuous aggregate performance on your data so you know we are good fit 😄

**Comment by segiddins** [comment]
@jamessewell I've had severely reduced hours to work on RubyGems things the past few months, and most of my time has been dedicated to more security-related work (mainly the OIDC stuff), as well as stability work. I'd like to pick this back up once I have full-time hours again to devote to RubyGems work.

**Comment by jonatas** [comment]
Hey folks, I see that we'll have a [hackathon day](https://rubycentral.org/news/a-look-back-at-rubyconf-2023-featuring-the-brand-new-community-day/) and I'd love to work on this one as I'm already a few years on the Timescaledb side and with RubyGems support, I think we could easily move it into a reviewable state.

**Comment by simi** [comment]
Hello @jonatas, currently this was put on hold. I'm available to hop on call and discuss current setup and possibilities. I would prefer smaller incremental contribution over one huge PR if possible. I'm happy to help. Feel free to ping me here or at [bundler Slack](https://bundler.io/).

**Comment by martinemde** [comment]
Closing this for now as there is other separate work on timescale. Re-open if needed.

**Pull request closed without merging**
