### PR TITLE
FastlyLogProcessorJob doesn't raise in tests.

### PR DESCRIPTION
**Pull request by simi**
- it fails silently and is retried

### CODE REVIEW

**Comment by simi** [comment]
Does it work this way currently?

There is this rescue block making job successful and no retry happens (at least if I understand it well).

https://github.com/rubygems/rubygems.org/blob/1a1aea1f3bf29cf4fc19a01c003a05325cc2ad5c/app/jobs/fastly_log_processor.rb#L34-L36

**Comment by segiddins** [comment]
It looks like that immediately re-raises...

**Comment by simi** [comment]
> 

Ahh, right. I'll check again.

**Comment by simi** [comment]
What about this @segiddins? It is inspired by exception testing at https://github.com/rails/rails/blob/20d87500a4568b175f1e06796572154a5a8d283d/activejob/test/cases/exceptions_test.rb.

**Review by segiddins — APPROVED** [review]

**Pull request merged**
