### PR TITLE
made edits to the "supporting" section

### PR DESCRIPTION
**Pull request by rubymorillo**
Hi team,

Per https://github.com/rubytogether/board/issues/5, I'm proposing updates to the "Supporting" section that clarifies the role of each major sponsor of RubyGems.org. This is one part of an ongoing effort to update messaging across RubyGems and Ruby Together. Thanks!

### CODE REVIEW

**Comment by rubymorillo** [comment]
cc @indirect

**Comment by sonalkr132** [comment]
closing in favor of #1722

**Comment by indirect** [comment]
@sonalkr132 because many people have said they were confused or unsure about this, I think it's a good idea to put this new, clearer explanation into both the readme and the site footer 👍

**Comment by sonalkr132** [comment]
Sorry I took #1722 same as this because text was same. my bad!
Thanks @rubymorillo for updating readme as well.

**Comment by adarsh** [comment]
Hey, just a note that I had already opened https://github.com/rubygems/rubygems.org/pull/1720 to address this issue and used the language we agreed to with @evanphx in this PR: https://github.com/rubytogether/board/pull/8.

In the discussion above, I proposed agreeing on one set of language and using it consistently across all the places one would look for it.

As such, I'm going to resolve the conflict in PR #1720 and propose we use that language here specifically.

**Pull request merged**
