### PR TITLE
Add api endpoint for gem metrics

### PR DESCRIPTION
**Pull request by sonalkr132**
~~Uses `ENV["HTTP_USER_AGENT']` set by bundler[[1](https://github.com/bundler/bundler/blob/master/lib/bundler/fetcher.rb#L170-L195)].
I am not sure why was the [previously proposed implementation](https://github.com/rubygems/rubygems.org/pull/1390) trying to read values of `params` when `ENV` is being set by bundler.~~

It is based on the bundler-api implementation[[2](https://github.com/bundler/bundler-api/blob/02c2633278edc81bf2e58bf9d7022b8607fd02e5/lib/bundler_api/agent_reporting.rb)][[3](https://github.com/bundler/bundler-api/blob/02c2633278edc81bf2e58bf9d7022b8607fd02e5/spec/agent_reporting_spec.rb)].

cc: @indirect

### CODE REVIEW

**Comment by indirect** [comment]
Awesome! 👍 Unfortunately, Bundler does not yet contain code that will make a request to this endpoint. Right now, the User-Agent header is being set on index and gem HTTP requests, which are usually served by Fastly. To collect metrics from existing versions of Bundler, we will need to add some extra Fastly log processing to the existing Shoryuken task. To collect metrics using this endpoint, we will need to add code to Bundler to contact the endpoint directly.

**Comment by sonalkr132** [comment]
> To collect metrics from existing versions of Bundler, we will need to add some extra Fastly log processing to the existing Shoryuken task.

I am sorry but [this example](https://github.com/rubygems/rubygems.org/blob/master/test/sample_logs/fastly-fake.log) log is the only fastly log I am familiar with. What does the log containing `USER_AGENT` look like? If I am provided with a similar example log, I can come up with something.

>  To collect metrics using this endpoint, we will need to add code to Bundler to contact the endpoint directly.

Was bundler going to start using `params` instead of `ENV`?

**Comment by indirect** [comment]
@sonalkr132 for actively reporting metrics from Bundler, to a metrics endpoint like this one, means that Bundler will need to use `params` instead of `ENV`. HTTP request headers are much more brittle than POST bodies are, and it's a lot harder to ensure that the data is always escaped and encoded properly. Headers also have much lower size limits. As a result of all of those things, the future Bundler metrics reporting will use `params` to talk to this endpoint.

For the requests Bundler is making right now, the headers are not being sent to this endpoint. Instead, Fastly is logging the User-Agent sent by Bundler with every request, and we are processing those logs [over here in this background job](https://github.com/rubygems/rubygems.org/blob/master/app/jobs/fastly_log_processor.rb). What I would like to do is add code to the background job that extracts the User-Agent information set by Bundler and sends that information to DataDog so we can graph it. 👍

...in the process of getting an example of the log line for you, it seems like we are not saving the log lines that come from Bundler 😱 Maybe we will have to fix that problem first before we can add something to the background job that records user agent info. 😢

**Comment by sonalkr132** [comment]
Updated it to use `params`. Let me know which other changes it may need.

**Comment by indirect** [comment]
Thanks for working on this! Maybe we can build a prototype of the client in a branch on the Bundler repo and test it out before we merge and ship this?

**Comment by sonalkr132** [comment]
@Akrabut is working on updated PR https://github.com/Akrabut/rubygems.org/pull/1

**Pull request closed without merging**
