### PR TITLE
Store & validate gemspec "new platform" on versions

### PR DESCRIPTION
**Pull request by segiddins**
So we stop adding new conflicts when multiple original platforms resolve to the same platform

See https://gist.github.com/segiddins/aab18915778e6159bafb8f9d1b8d42a8 for existing "duplicates"

### CODE REVIEW

**Review by indirect — APPROVED** [review]
this looks good to me. I'm not completely excited about the extra mostly-duplicate columns on our biggest table, but I don't know of a better way to handle this problem, so let's do it.

**Comment by simi** [comment]
Is there any new test failing with old behaviour? I do see only change on the returned status in tests. :thinking:

**Review by simi — APPROVED** [review]

**Comment by segiddins** [comment]
The tests I added last week for the CVE mostly cover the same things, the changed return status shows that it's now failing when validating the new version record, vs after that. But I added some more explicit tests around pusher saving platforms in versions, we didn't really have those yet

**Comment by simi** [comment]
> The tests I added last week for the CVE mostly cover the same things, the changed return status shows that it's now failing when validating the new version record, vs after that. But I added some more explicit tests around pusher saving platforms in versions, we didn't really have those yet

:muscle: looks good

**Pull request merged**
