### PR TITLE
Add the missing fields to the dependency api response

### PR DESCRIPTION
**Pull request by sonalkr132**
[Fields on bunlder-api](https://github.com/bundler/bundler-api/blob/master/lib/bundler_api/gem_info.rb#L50-L61)

I have checked the data dump, sha256 is same as checksum.

### CODE REVIEW

**Comment by dwradcliffe** [comment]
cc: @segiddins @indirect @maclover7

**Comment by dwradcliffe** [comment]
LGTM 👍

**Comment by segiddins** [comment]
Seems right!

**Comment by maclover7** [comment]
👍

**Pull request merged**
