### PR TITLE
update fog and excon gems

### PR DESCRIPTION
**Pull request by mockdeep**
This gets the specs passing, though there may be a need to test this on staging.

### CODE REVIEW

**Comment by davefp** [comment]
@mockdeep As a result of #610 a large chunk of the repo's history was re-written. Please rebase your PR so that it will merge cleanly. Thanks!

(There are further details on the blog: http://blog.rubygems.org/2015/02/01/rewriting-history.html)

**Comment by mockdeep** [comment]
Ha, rebase was an abortive effort. I just re-ran the bundle update.

**Comment by mockdeep** [comment]
Side note: we switched from `fog` to [`carrierwave-aws`](https://github.com/sorentwo/carrierwave-aws) recently and that seems to be working out so far. `fog` has a ton of unused dependencies.

**Comment by arthurnn** [comment]
I wonder if we need `fog` or even `carrierwave-aws` at all. Or if we could just use the aws gem to upload files, and some mock for tests.. Not sure how hard would that be, but indeed `fog` include way more things that we need.

**Comment by mockdeep** [comment]
Oh, yeah, looks like carrierwave isn't even a dependency. The AWS gem might be sufficient, then. I kind of feel like fog ought to make you require your dependencies manually.

**Comment by arthurnn** [comment]
@mockdeep We should try to use the AWS gem instead then, instead of upgrading the fog gem.
Fell free to open a PR for it.
thanks a lot

**Pull request closed without merging**
