### PR TITLE
Cleaning up locale files and enforcing consistency

### PR DESCRIPTION
**Pull request by GBH**
Currently locale files are a mess. None of them structurally match :en locale so it's hard to tell what is translated and what is not. This PR is an effort to clean everything up and make it very hard to screw it up in the future.

- Normalized :en locale without changing anything
- Cleaned up all other locales so they structurally match :en. Added missing keys, removed unused ones. :es was exceptionally bad. So line 123 in en.yml will have exactly same key for all locales.
- Used this script to help me: https://gist.github.com/GBH/de15af9cb51054c34b6ad947009584df but didn't commit it as it should not be needed going forward
- Added a integration test that enforces locale files structure: https://github.com/GBH/rubygems.org/blob/fix/i18n_cleanup/test/integration/i18n_test.rb 
it will complain if you have missing/extra keys in other locales compared to :en

This is only a cleanup. There might be unused keys in :en, but you'll need something like i18n-tasks gem to deal with this. This PR is a foundation for a more manageable locales.

Cheers

### CODE REVIEW

**Comment by dwradcliffe** [comment]
Thanks for the effort here! I like the idea of keeping things cleaned up, but this does duplicate the defaults into each file and doesn't make use of the default locale fallback. I wonder if it's better to leave out any items that are not yet translated?

**Comment by GBH** [comment]
If you leave out items not yet translated, how do you know they are not yet translated? It's way better to have untranslated duplicates present right there in the file. That way it's crystal clear that there's a string that needs to be dealt with. As you can see, even better maintained locale file is only about 80% complete. Couldn't have known that before.

**Comment by GBH** [comment]
Any interest in this PR? It's a lot of work to resolve conflicts every time locale file is getting changed on master. Once again, this method of keeping locale files clean is extracted from a few of my projects that have quite a few more i18n strings and it works wonderfully keeping everything in order.

**Comment by dwradcliffe** [comment]
Is it possible to set the not yet translated items to nil or something like that? So we have them in the locale file but it's obvious that they are not translated yet?

**Comment by GBH** [comment]
Yes, it seems if you have a fallback defined it will use that for keys that have blank values. Does it make sense to blow away english strings from other locales? Easy enough to do, but not really much of a point imo.

**Comment by dwradcliffe** [comment]
👍 awesome! It's fine to leave any that were there prior to this PR, but I don't want to add new english strings to other locales.

**Comment by GBH** [comment]
Done and done. Of course now you gotta reference en.yml to do the translating, but no more duplication of en strings anywhere.

**Comment by simi** [comment]
:heart:

**Comment by dwradcliffe** [comment]
@GBH Sorry for the delay here, one more fixup and then I'll try to get this merged asap.

**Comment by GBH** [comment]
Ok, good to go. Let's merge this.

**Pull request merged**
