### PR TITLE
[Indexer] Add support for RubyGems 2.5+

### PR DESCRIPTION
**Pull request by segiddins**
... This just cost me days of frustration

\c @arthurnn @dwradcliffe

### CODE REVIEW

**Comment by indirect** [comment]
:sob:

(can you explain what the effect of not having this change is, and what will work correctly once we merge this?)

**Comment by segiddins** [comment]
This means this app will actually work correctly when the user is running the latest version of RubyGems. It fails in super-strange ways without this fix on 2.6.4.

**Comment by segiddins** [comment]
I think if we re-run this on CI it'll pass

**Comment by segiddins** [comment]
What do you know, rebasing fixed the tests!

**Comment by indirect** [comment]
@homu r+

**Comment by indirect** [comment]
lol this repo doesn't have homu

**Comment by indirect** [comment]
wait what... I have just triple-confused myself. bah 😅

**Comment by arthurnn** [comment]
Make sense.. i remember changing those apis on rubygems client. 👍

**Comment by dwradcliffe** [comment]
BTW we are running 2.6.4 on all the servers now.

**Comment by segiddins** [comment]
Wahoo!

**Comment by arthurnn** [comment]
> BTW we are running 2.6.4 on all the servers now.

Nice, we probably can remove that if then.

**Comment by sonalkr132** [comment]
I will do it.

**Pull request merged**
