### PR TITLE
Bump elasticsearch-rails to 7.2.1 for import fix (but blocks using opensearch)

### PR DESCRIPTION
**Pull request by martinemde**
Fixes a problem with running the elasticsearch import rake task. ActiveRecord find_in_batches api requires being called with kwargs, but elasticsearch-rails was only fixed to send kwargs properly in 7.2.1.

### CODE REVIEW

**Comment by martinemde** [comment]
Looking at the test failure.

**Comment by martinemde** [comment]
Failure is test order dependent which is a little troubling. The failure looks possibly related to the elasticsearch and faraday upgrade, doesn't fail unless you use the seed `bin/rails test --seed 51142`

**Comment by martinemde** [comment]
I think this bug only happens when the tests try to refresh an index that doesn't exist. The failure happened when trying to trigger logging before suppressing the exception.

I was able to reproduce the failure one time when I did `gem update --system` before running the tests, then it only happens the first time.

I'm curious why something changed that altered whether or not the index was found. Is it going to change where the main rubygems.org index is stored?

**Comment by martinemde** [comment]
I fixed the index not existing in #3303.

**Comment by martinemde** [comment]
Hey @simi, it looks like you've done a lot of work with elasticsearch and searchkick. Replacing the import task referenced in the contributing docs (that is currently broken) is my main goal here. If #3199 is merged, searchkick replaces that command with a searchkick command. Can I help you get that across the finish line or should we do the minor upgrade here first?

**Comment by simi** [comment]
@martinemde I do plan to merge Searchkick soon. Are those gems in this update still OpenSearch compatible?

**Comment by simi** [comment]
It seems we can't upgrade after this https://github.com/elastic/elasticsearch-ruby/pull/1360 released with 7.14.

**Comment by martinemde** [comment]
Pushed a version locked to 7.13.3 before the change mentioned above.

**Comment by martinemde** [comment]
😬  Looks like the ruby 3 compatible version of elasticsearch-model (7.2.1) uses `transport.transport` which is not supported in 7.13.

It seems to me that if we are switching to opensearch, then we need a replacement version for open search or we have to use older versions and monkeypatch the kwargs incompatibility.

**Comment by martinemde** [comment]
I reverted to use 7.17, since it's simply broken on 7.13.3. I converted this to a draft because #3199 may inform how we progress and we may want to decide before merging this.

**Comment by simi** [comment]
elasticsearch-rails was removed at https://github.com/rubygems/rubygems.org/commit/01ee51b3228e4548e248b369d3694b4109cc1d31#diff-89cade48462044ee1b672dc5f4c3ec250fbd29effcd8932096a23c1283c6731fL158, closing

**Pull request closed without merging**
