### PR TITLE
Update database.yml.sample to support multiple databases

### PR DESCRIPTION
**Pull request by segiddins**
This is no functional change, the "primary" database is what we are already using

By being explicit, we allow adding other databases to each env in the future

### CODE REVIEW

**Comment by colby-swandale** [comment]
Is adding additional databases something we're actively working on at the moment? Though the change is small.. it feels just like this isn't necessary for now?

**Comment by segiddins** [comment]
Yes, it is something I am working towards for a (user facing) event log feature

**Review by martinemde — APPROVED** [review]
I've done this on another app. Looks right compared to that one :+1:

**Review by simi — APPROVED** [review]
_These mysterious PRs sometimes makes me wonder what's going to follow._

**Pull request merged**
