### PR TITLE
New fast builds based on Docker

### PR DESCRIPTION
**Pull request by jhsu802701**
Please note that the only change I made to the existing code was adding *.DS_Store to .gitignore.  All other changes involve the addition of new files.

The build_prep.sh script runs the ./script/setup script and starts Toxiproxy.  The build_fast.sh script provides instructions on how to proceed with the setup and testing process.  It explains to the user what's needed to run the script.  After the user presses Enter, it proceeds with starting Elasticsearch, setting up PostgreSQL, bundle install, database migrations, and running the tests.  The README-build_fast.md file explains in more detail how to set up Docker and quickly gain access to the development environment needed.

Developers are still free to build this app using the agonizingly slow and painful traditional way, and the instructions for doing so are unchanged.

### CODE REVIEW

**Comment by simi** [comment]
IMHO `.DS_Store` belongs to your [global gitignore](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore) since it is not project related.

**Comment by nateberkopec** [comment]
Can you elaborate on the use case for this? Are you attempting to run Rubygems.org without Ruby installed? As far as Rails apps go, Rubygems.org is pretty easy to set up in development.

**Comment by jhsu802701** [comment]
I know that most people have Ruby on Rails installed directly on the host OS.  That setup always worked poorly for me for these reasons:
1.  Installing Ruby on Rails manually takes a long time and requires babysitting long processes, such as installing the correct versions of Ruby and installing the correct versions of Rails.
2.  If my development environment behaved strangely, I faced the task of either troubleshooting things or reinstalling Ruby on Rails.  In either case, my productivity was held hostage until I resolved the issue.
3.  When it was time to deploy my project or transfer my work to another machine, I was bombarded with long cascades of error messages because my setup scripts/procedures weren't complete, and trying to remember every little thing necessary was a nightmare.  Some of my earliest Ruby gems were very buggy because I forgot to include certain essential gems in my gemspec file.

**Comment by jhsu802701** [comment]
I was using project-specific Vagrant boxes before I recently switched to project-specific Docker images.  (The Docker way bypasses the bootup process.  One can return to the initial conditions of the Docker image in a matter of seconds, compared to the minutes needed to rebuild a Vagrant box.)

The reasons I find Docker so indispensable are:
1.  Setting up the development environment is quick.  It only takes a few minutes to install Docker, and it only takes a few minutes to download the Docker image.  Because the correct version of Ruby is already provided in my project-specific Docker image, I never have to enter "rbenv install" and then endure a long wait for the correct version of Ruby.  Because the correct versions of Rails, Nokogiri, and pg are already provided, the "bundle install" step is much shorter.
2.  If anything strange happens, or if I think I accidentally broke Ruby on Rails, I'm only seconds away from returning to a fresh Ruby on Rails installation.  I know exactly what to expect from the original Docker image, and this gives me the control and predictability I need given how finicky Ruby on Rails can be.  This greatly aids the troubleshooting process, because it allows me to eliminate the possibility that a broken Ruby on Rails installation is at fault.  The culprit then must be either the source code or a missing dependency.
3.  Because I can reinstall Ruby on Rails willy-nilly, I can make sure that I know EXACTLY what it takes to build the project for deployment or for transferring my work to another machine.  The scripts used to build the Docker image double as giant cheat sheets.

**Comment by jhsu802701** [comment]
I created the Bash scripts build_fast.sh and build_prep.sh to minimize the need to babysit multi-step processes.  The build_prep.sh script runs the config/setup script that installs Toxiproxy and makes other preparations.  The build_fast.sh script starts off with a reminder of all of the conditions needed to run the tests, including the need to run the Redis server and Toxiproxy.  Pressing Enter continues the rest of the script, which takes care of setting up config/database.yml, setting up PostgreSQL, bundle install, database migrations, and running the tests.

Use of the custom Docker container and the build_fast.sh and build_prep.sh scripts streamlines the process of building or rebuilding the app.  Every step of the process is included.  Keeping on top of the build process is an essential part of of maintaining a project, and the ability to execute the entire build process in minutes instead of hours makes it more likely that this maintenance will get done.

**Comment by dwradcliffe** [comment]
I agree with @nateberkopec here. This is a pretty straightforward Rails app, and I don't think most people have had to spend many hours getting it setup. I applaud the desire to make it easier to get the development environment up and running easier, but I don't think this is the right direction.

Ruby is trivial to install in most cases these days, with your choice of ruby version managers.
It's not easy to "break" Ruby on Rails. Bundler and the Gemfile manage all the gem dependencies nicely.
In my experience, setting up docker from scratch has taken hours.

I'd be happy to link to these instructions/scripts in an external repository but I don't think we want to maintain this as part of this repository.

**Comment by jvanbaarsen** [comment]
Most people that want to contribute to Rubygems have ruby installed, but not most people have Docker installed.

Getting Docker running on OSX is not trivial, because you need a VM image running, which is taking up a lot of diskspace.

**Comment by simi** [comment]
@jvanbaarsen actually installing Docker on Win/OSX is trivial these days. https://www.docker.com/products/docker-toolbox

But I don't think this repository needs Dockerfile for developers.

**Comment by arthurnn** [comment]
I agree with @dwradcliffe . I ❤️  your work here, thanks a lot for helping out rubygems.org.
However I don't think providing a Docker install is the right direction. I want to try to leave the dev environment of this project as small as possible, so we dont need to run Vagrant/Boxen/Docker or anything like that. 

Thanks. What you could do is add this to a gist, and you can post to the mailing list the link to the gist, so if someone searches on how to do that, they will find the mailing list entry as well as your gist.

thanks again

**Pull request closed without merging**
