### PR TITLE
Moved off container based testing in Travis

### PR DESCRIPTION
**Pull request by RDIL**
This is deprecated and Travis advises everybody changes it.

### CODE REVIEW

**Comment by simi** [comment]
@RDIL any link for details?

**Comment by RDIL** [comment]
@simi glad you asked, here: 
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

**Comment by simi** [comment]
Isn't enough just remove it?

**Comment by RDIL** [comment]
That could work.

**Comment by dwradcliffe** [comment]
Oh interesting, I hadn't heard about this. Thanks!
For some reason the build is not working now though...

**Comment by RDIL** [comment]
It is a time-out issue.  I’ll rerun it.

**Comment by RDIL** [comment]
Should be ready for merge.

**Pull request merged**
