### PR TITLE
Update rails to 5.1.4

### PR DESCRIPTION
**Pull request by colby-swandale**
This PR updates Ruby on Rails to the latest version of 5.1.4. There were a few errors being raised when I ran the specs:

    ActionView::Template::Error: Cannot have a has_many :through association 'Rubygem#subscribers' which goes through 'Rubygem#subscriptions' before the through association is defined.

This is fixed by re-oredering the `has_many` relationships that were using the `through` option to be specified after the `through` relationship was specified.

The `test/integration/stats_test.rb` was also breaking due to URI library

    URI::InvalidURIError: bad URI(is not URI?): http://localhost/stats?page=%223\%22%3EXSS%22

To fix this i changed the test to use characters that the test is using but can be used in the URI.

Thanks

### CODE REVIEW

**Comment by colby-swandale** [comment]
Rails 5.2 is out now so this PR is not useful anymore.

**Comment by dwradcliffe** [comment]
😐 sorry Colby
We should try to get upgraded

**Comment by simi** [comment]
I think it is still valid PR. Migrate to 5.1 first will be useful before 5.2 upgrade. Do you any need help with current PR @colby-swandale @dwradcliffe? I can take a look.

**Comment by colby-swandale** [comment]
It will be easier to just go straight to 5.2

**Pull request closed without merging**
