### PR TITLE
Use delete instead of gsub from stripping protocol

### PR DESCRIPTION
**Pull request by JuanitoFatas**
Follow up of #1041, see https://github.com/rubygems/rubygems.org/pull/1041#issuecomment-129553825.

### CODE REVIEW

**Comment by sferik** [comment]
@JuanitoFatas :+1: Thanks :exclamation:

**Comment by dwradcliffe** [comment]
:+1:

**Comment by JuanitoFatas** [comment]
:relaxed:

**Comment by arthurnn** [comment]
:heart:

**Pull request merged**
