### PR TITLE
translation(ja): maintainer word change

### PR DESCRIPTION
**Pull request by okuramasafumi**
"保守者" -> "メンテナ"
Personally, I don't see and hear "保守者" very often. Instead we use "メンテナ" or "メンテナ−".
When I google like "Ruby 保守者" and "Ruby メンテナ", the number of the results is much bigger for the latter.

### CODE REVIEW

**Comment by simi** [comment]
Thanks @okuramasafumi. By any chance, would you mind to do review of https://github.com/rubygems/rubygems.org/pull/4779 if you have time? :pray:

**Comment by okuramasafumi** [comment]
@simi I reviewed #4779 and added some comments for minor fixes/improvements.
CI fails here but I guess it's not related to this change.

**Comment by simi** [comment]
let me restart CI, seems unrelated indeed

**Comment by simi** [comment]
Thanks again @okuramasafumi.

**Pull request merged**
