### PR TITLE
Upgrade to Clearance 1.10.1

### PR DESCRIPTION
**Pull request by derekprior**
Clearance 1.10 deprecates all clearance-provided password strategies
other than BCrypt. RubyGems is using the `BCryptMigrationToSHA1`
strategy and as such needs to add the
`clearance-deprecated_password_strategies` gem to avoid continue
deprecation messages.

Alternatively, RubyGems could switch to the `BCrypt` strategy and force
anyone not yet migrated to reset their passwords.

### CODE REVIEW

**Comment by derekprior** [comment]
TO be clear, Password Strategies themselves are not going away, it's just that as the Clearance maintainer I will not maintain them as part of clearance itself any longer.

**Comment by dwradcliffe** [comment]
So this extra gem has the password strategies now? And everything will still work the same with this PR?

**Comment by derekprior** [comment]
Yes, it has the password strategies, but I'm not guaranteeing they will work as is in Clearance 2.0 (though they may). We no longer want to offer blowfish or SHA1 as seemingly supported password strategies. Electing to use SHA1 is insecure.

I'd recommend that RubyGems itself move to stop supporting SHA1 passwords and just use the BCrypt strategy, but I'm not sure how big of a deal that is for you at this moment.

**Comment by dwradcliffe** [comment]
I'm not super familiar with the migration strategy. Is there an easy way to query the db and see how many users still haven't migrated?

**Comment by derekprior** [comment]
With the migration strategy, we check if the current `encrypted_password` value appears as though it is SHA1 by running this:

```ruby
def sha1_password?
  self.encrypted_password =~ /^[a-f0-9]{40}$/
end
```

IIRC, RubyGems is on MySQL? So I think this would do the trick in SQL form:

```SQL
SELECT count(*)
FROM users
WHERE encrypted_password RLIKE "^[a-f0-9]{40}$"
```

I have no idea how that will actually perform, so you'd probably want to run it on a local copy.

**Comment by dwradcliffe** [comment]
@derekprior We're actually using Postgres. Would that query still work?

**Comment by derekprior** [comment]
I think you'd use `similar to` in psql: http://www.postgresql.org/docs/9.3/static/functions-matching.html

**Comment by dwradcliffe** [comment]
Looks like we still have a significant number (about 70%) of users on SHA1.

I think we're ok to move forward here, but we just need to keep this in mind as we update these gems in the future.

**Comment by dwradcliffe** [comment]
Oh and this was what I used:

`SELECT count(*) FROM users WHERE encrypted_password SIMILAR TO '[a-f0-9]{40}';`

**Comment by arthurnn** [comment]
Right.. we can update and we the gem for now..
We probably should do something about force the users to migrate sooner. But thats another discussion.

thanks all

**Pull request merged**
