### PR TITLE
Bump rails to rc version

### PR DESCRIPTION
**Pull request by arthurnn**
cc @rafaelfranca @dwradcliffe @qrush @sferik

### CODE REVIEW

**Comment by dwradcliffe** [comment]
Can you link to the changelog?

**Comment by qrush** [comment]
Why the bump? I'd love to try out Rails 5 once the RC is out.

**Comment by arthurnn** [comment]
@qrush me too. I will make sure to upgrade once the RC is out..While we are not there, we need to keep updating our 4.2.x version to be as close as possible to 5.

**Comment by arthurnn** [comment]
* [Action Mailer CHANGELOG](https://github.com/rails/rails/blob/v4.2.6.rc1/actionmailer/CHANGELOG.md)
* [Action Pack CHANGELOG](https://github.com/rails/rails/blob/v4.2.6.rc1/actionpack/CHANGELOG.md)
* [Action View CHANGELOG](https://github.com/rails/rails/blob/v4.2.6.rc1/actionview/CHANGELOG.md)
* [Active Model CHANGELOG](https://github.com/rails/rails/blob/v4.2.6.rc1/activemodel/CHANGELOG.md)
* [Active Record CHANGELOG](https://github.com/rails/rails/blob/v4.2.6.rc1/activerecord/CHANGELOG.md)
* [Active Support CHANGELOG](https://github.com/rails/rails/blob/v4.2.6.rc1/activesupport/CHANGELOG.md)
* [Active Job CHANGELOG](https://github.com/rails/rails/blob/v4.2.6.rc1/activejob/CHANGELOG.md)
* [Railties CHANGELOG](https://github.com/rails/rails/blob/v4.2.6.rc1/railties/CHANGELOG.md)

**Comment by dwradcliffe** [comment]
:+1:

**Pull request merged**
