### PR TITLE
Github Codespace / Devcontainer

### PR DESCRIPTION
**Pull request by colby-swandale**
This Pull Request adds the configuration needed to create an automated development environment using Github Codespaces / Devcontainer. See https://github.com/rubygems/rubygems/pull/7133 for the full detailed description / reasoning.

### CODE REVIEW

**Comment by hsbt** [comment]
Is there reason why to use `alpine` image? Ruby core doesn't support alpine officially. I suggest to use debian image for this.

**Comment by simi** [comment]
@hsbt alpine is used in production for rubygems.org (https://github.com/rubygems/rubygems.org/blob/abdb1ff3f9cff06396c4d36a3195939666b9275a/Dockerfile#L6)

**Comment by hsbt** [comment]
Fmm, I see. It's better to switch debian image too.

**Comment by colby-swandale** [comment]
> Fmm, I see. It's better to switch debian image too.

I'm happy to investigate this, but request working on this in a future PR. The Ruby Alpine image has been in production for a long time, so we know the image works as intended for now. I'm also constrained for time a bit as I would like to have the Devcontainer / CodeSpace ready for RubyConf next week.

**Comment by colby-swandale** [comment]
I'm going to merge this for now. Feel free to tag me on any issues.

**Pull request merged**
