### PR TITLE
Add logit and travis as sponsers

### PR DESCRIPTION
**Pull request by sonalkr132**
I will remove bluebox when we add ruby together.

sponsers

### CODE REVIEW

**Comment by dwradcliffe** [comment]
@indirect do you have the RT logo?

**Comment by segiddins** [comment]
@dwradcliffe https://github.com/rubytogether/rubytogether.org/blob/master/public/images/ruby-together.png ?

**Comment by sonalkr132** [comment]
Updated!

**Comment by indirect** [comment]
Oh, could you use the logotype instead? . Sorry for the trouble!

**Comment by sonalkr132** [comment]
Its okay :smiley_cat:  Updated!

**Comment by dwradcliffe** [comment]
LGTM, thanks!

**Pull request merged**
