### PR TITLE
add cache headers for compact index

### PR DESCRIPTION
**Pull request by dwradcliffe**
@indirect @segiddins

### CODE REVIEW

**Comment by indirect** [comment]
@dwradcliffe just to make sure I'm reading this right, we're telling Fastly to keep the copy at the shield for 10 minutes, and telling end users to cache for 60 seconds?

**Comment by dwradcliffe** [comment]
Yep. The `3600` was what we had set in the `bundler-api`.

**Comment by indirect** [comment]
@dwradcliffe great 👍 clients like Bundler won't respect the 60 second time, but Fastly should be able to respond with 304 Not Modified immediately. In `bundler-api`, we have it set up to bust the Fastly cache for `/versions` and for `/info/NAME` when a new gem version is pushed. Is that still set up to happen here?

**Comment by dwradcliffe** [comment]
Yep:
https://github.com/rubygems/rubygems.org/blob/master/app/models/pusher.rb#L132
https://github.com/rubygems/rubygems.org/blob/master/lib/fastly.rb#L37-L41

**Comment by indirect** [comment]
Sweet. Thanks! @homu r+

**Pull request merged**
