### PR TITLE
Use `#latest_version` when loading the profile page rubygems

### LINKED ISSUE #4624: Display last released version
Hello 👋🏼 

When you visit your profile page, Which is the version displayed for each of your gems? It seems arbitrary 🤔?

Example (https://rubygems.org/profiles/markets):

Captura de pantalla 2024-04-18 a las 22 19 00

---

Captura de pantalla 2024-04-18 a las 22 20 47

## Steps to Reproduce
Visit any profile page, like: https://rubygems.org/profiles/markets
 
## Expected Behavior
Each gem should display last released version.

## Current Behavior
Not sure which version is displayed right now 🙏🏼, but 100% sure it's not the last one.

## Possible Solution
Just display last version ✔️

### PR DESCRIPTION
**Pull request by dancristianb**
Fixes #4624

This PR targets fixing the profile page gem versions issue described in #4624. I've pulled down a copy of the data using the instructions in https://github.com/rubygems/rubygems.org/blob/master/CONTRIBUTING.md#getting-the-data-dumps and tried it out locally. The fix seems to work correctly 👍 

I'm not sure if this is the best approach though 🤔 I also found that this is somewhat related to eager loading the `gem_download` association in https://github.com/rubygems/rubygems.org/blob/master/app/controllers/profiles_controller.rb#L12. 

So if on `master` I remove the `gem_download` eager load and stub out the `rubygem.downloads` call from the view (so I don't hit the `ActiveRecord::StrictLoadingViolationError` exception) I see the correct `invisible_captcha` `2.2.0` version (this is using the `most_recent_version` call). There's something happening with the scope there but I'm having trouble piecing it together 🤔 

```
diff --git a/app/controllers/profiles_controller.rb b/app/controllers/profiles_controller.rb
index 82a3c1a2d..2680413d4 100644
--- a/app/controllers/profiles_controller.rb
+++ b/app/controllers/profiles_controller.rb
@@ -9,7 +9,7 @@ class ProfilesController < ApplicationController

   def show
     @user = User.find_by_slug!(params[:id])
-    @rubygems = @user.rubygems_downloaded.includes(%i[most_recent_version gem_download]).strict_loading
+    @rubygems = @user.rubygems_downloaded.includes(%i[most_recent_version]).strict_loading
   end

   def me
diff --git a/app/views/profiles/_rubygem.html.erb b/app/views/profiles/_rubygem.html.erb
index c8fa121d2..df50829aa 100644
--- a/app/views/profiles/_rubygem.html.erb
+++ b/app/views/profiles/_rubygem.html.erb
@@ -7,7 +7,7 @@
       </a>
     </span>
     <p class="gems__gem__downloads__count">
-      <%= number_with_delimiter(rubygem.downloads) %>
+      <%#= number_with_delimiter(rubygem.downloads) %>
       <span class="gems__gem__downloads__heading">Downloads</span>
     </p>
     <% if local_assigns[:owners] %>
```

---

So this is what the page looks like before the PR updates

Screenshot 2024-04-21 at 14 05 05
Screenshot 2024-04-21 at 14 05 45

This is what the page looks like after the PR updates ✅

Screenshot 2024-04-21 at 14 06 35

### CODE REVIEW

**Review by segiddins — APPROVED** [review]

**Comment by markets** [comment]
Thanks @dancristianb 👏🏼 👏🏼 Nice introspection and explanation!

@segiddins @martinemde Do you think we can merge this one 🙏🏼? Current situation is really weird.

**Review by martinemde — APPROVED** [review]
Thanks for taking the time to figure this out and fix it.

**Comment by martinemde** [comment]
Deployed. Thanks again!

**Comment by markets** [comment]
Confirmed ✅ It works fine now in production 👌

Thank you so much @martinemde!

**Pull request merged**
