### PR TITLE
Removed the reserved names for the default gems of Ruby 3.0

### PR DESCRIPTION
**Pull request by hsbt**
This pull-request is a final approach for the Gemification of Ruby language.

@sonalkr132 Can you merge and deploy this? When you deploy it, Can you ping me too?

Regards,

### CODE REVIEW

**Comment by simi** [comment]
:thinking: any chance to make a list of vendored/pre-installed gems available as a constant i Ruby itself?

**Review by simi — APPROVED** [review]

**Comment by sonalkr132** [comment]
I will message you around the same time we did this the last time. 10am UTC.

**Comment by hsbt** [comment]
I'm ready to do it at 10am UTC.

**Comment by hsbt** [comment]
@sonalkr132 Sorry, Could you merge https://github.com/rubygems/rubygems.org/pull/2561 before deploying this?

**Pull request merged**
