### PR TITLE
Update navbar dropdown style [needs feedback]

### PR DESCRIPTION
**Pull request by davydovanton**
Hi all!
I decided to try to update navbar dropdown style. you can see screenshots below. On this screenshots you can see what we have now and what I suggest. I hope to hear your opinions and suggestions :yellow_heart: :green_heart: :heart:

### Now
screenshot 2015-02-18 01 57 33

### What I suggest
screenshot 2015-02-18 01 58 41

*P.S.: sorry, i think that i have some problems with fonts in my local server :cold_sweat:*

### CODE REVIEW

**Comment by arthurnn** [comment]
@acacheung what do you think?

**Comment by davydovanton** [comment]
@acacheung :wave:

**Comment by sferik** [comment]
:-1: I prefer the way it looks now to this new proposal. In the current version, the menu wiring looks like it’s connected to the top of the screen. With this proposal, they look like they’re floating in mid air. I also prefer the harder edge and flat look to the rounded corners and shadow. My 2¢.

**Comment by davydovanton** [comment]
@sferik thanks for feedback! :yellow_heart:

**Comment by sferik** [comment]
@davydovanton Thanks for submitting this patch. Much of visual design is a matter of taste and reasonable people can disagree on what looks better.

The main reason I put my thumb down on this pull request is that this doesn’t fixing a bug in the design, it overrides an intentional decision by our designer. You may disagree with this decision but I don’t think it makes sense to accept patches that change a small aspect of the design. We could go back and forth merging these types of pull requests forever. This would result in a disjointed design without really making any progress.

**Comment by arthurnn** [comment]
@sferik : good point.

@davydovanton thanks a lot for the PR.

I will close this, and if @acacheung decides this is better she can re-open this and merge it.

thanks all.

**Comment by davydovanton** [comment]
@arthurnn thanks for feedback :+1:

**Pull request closed without merging**
