### PR TITLE
Update ERD CI step

### PR DESCRIPTION
**Pull request by mercedesb**
This PR updates the ERD CI step to diff the ERD dot files (after removing whitespace) to account for differences in machine environments (available/installed Graphviz versions and fonts)

## Description
I noticed the ["Generate ERD" step fails](https://github.com/rubygems/rubygems.org/runs/6161724714?check_suite_focus=true) b/c the `config/database.yml` file is Git ignored. The ERD gem needs the database config in order to generate the diagram. After making all the updates to successfully generate the ERD in the CI environment, this step will always fail due to differences in local dev environments and the CI envrionment.

Ubuntu's available Graphviz versions are very different than the version devs install on their Macs resulting in differences in the generated SVGs. I also explored diffing the actual dot files with the instructions Graphviz uses to create the SVGs but even here there are differences in fonts and other non-deterministic instruction order which result in unreliable diff results.

Due to permissions, it doesn't seem feasible to generate and commit the ERD as part of an action.

Now we're doing a cli diff (instead of a git diff) and comparing the ERD's dot files (instructions passed to Graphviz) after we remove all horizontal whitespace. There's a dependent PR in the rails-erd repo to be able to configure fonts so that the fonts used in the dot file and SVG are deterministic.

### CODE REVIEW

**Comment by mercedesb** [comment]
🤔 Closing for now to keep thinking.  When running the ERD CI step on an Ubuntu runner, the version of Graphviz that is available and installed is different than what a contributor would have generated the diagram with locally and checked in. This causes the diff check to fail.

**Comment by simi** [comment]
A what a pitty :( Let's leave this opened for a whole. I'll try to find out some alternative before removing the step.

**Comment by simi** [comment]
Would you mind to pass me `bundle exec erd --filetype svg` and `bundle exec erd --filetype dot` outputs from your system to compare?

**Comment by mercedesb** [comment]
Not at all, want me to just email you at the address you have on your profile?

**Comment by simi** [comment]
You can join us at Bundler Slack as well http://slack.bundler.io/.

**Comment by mercedesb** [comment]
I opened [#378](https://github.com/voormedia/rails-erd/pull/378) in the rails-erd repo to optionally configure fonts. 

And then I massaged the diff command a little bit so that we're removing all horizontal whitespace before we sort and compare.  When I tested with the file generated on Fedora Linux with the one generated on Ubuntu, differences in whitespace popped up.

If the rails-erd PR gets merged, then this might (🤞 ) work

**Comment by mercedesb** [comment]
[#378](https://github.com/voormedia/rails-erd/pull/378) in rails-erd got merged. So if/when a new version of the gem is released, we can upgrade and see how it goes

**Review by simi — APPROVED** [review]

**Pull request merged**
