### PR TITLE
Fix totp_seed to be nil when removed

### PR DESCRIPTION
**Pull request by ericherscovich**
Contributes to #3800 

## What problem are you solving?
When the decoupling work was deployed on June 23 there was some changes in the data we're seeing in the MFA metrics

These changes were made to the MFA stats job https://github.com/rubygems/rubygems.org/pull/3821/files#diff-8aba141af6f18a886b563458548a210891325cdaab3398c3367b03a743d30762

Dashboard: https://app.datadoghq.com/dashboard/86p-6iq-ii4/logins?from_ts=1686499433879&to_ts=1689091433879&live=true

OTP Users increased by ~4k while non-mfa users decreased by ~4k. OTP and webauthn users increased by 10 while webauthn only users decreased by 10.

This occured due to `totp_seed` being set to `""` instead of nil on deletion. So if users had OTP enabled then disabled it, the stats job still considered them to have OTP enabled, as it only looks for `totp_seed: nil`. 

This was confirmed with the query:
```ruby
irb(main):002:0> User.where(mfa_seed: "").where(mfa_level: :disabled).count
=> 4372
```

## What approach did you choose and why?
Swapped the problematic line to now set to nil. Added a test as well to validate this.

Also, added a rake task to fix the attribute for users that are affected. 

## What should reviewers focus on?
Please take a gander at the rake task and confirm I set that up correctly 😄.

## After merging task ⚠️ 
There is a rake task included in this PR to fix the users that have totp_seed set incorrectly. This rake task, :totp_seed_nil_fix should be run after merging.

### CODE REVIEW

**Comment by jenshenny** [comment]
After the rake task is run, I think it's worth restricting the `totp_seed.blank?` check more to `totp_seed.nil?` https://github.com/rubygems/rubygems.org/blob/master/app/models/concerns/user_totp_methods.rb#L9

**Comment by ericherscovich** [comment]
> After the rake task is run, I think it's worth restricting the `totp_seed.blank?` check more to `totp_seed.nil?` https://github.com/rubygems/rubygems.org/blob/master/app/models/concerns/user_totp_methods.rb#L9

I agree, that makes sense.

**Comment by segiddins** [comment]
Could also add a length validation on the model when the attribute is non-nil?

**Review by jenshenny — APPROVED** [review]

**Comment by jenshenny** [comment]
> Could also add a length validation on the model when the attribute is non-nil?

Good callout! I assume this will be done after the rake task is run.

I'll merge this, @segiddins when this goes out to prod, would you be able to run the rake task `rake one_time:totp_seed_nil_fix`?

**Comment by segiddins** [comment]
Ran `rake one_time:totp_seed_nil_fix` on staging & prod

**Pull request merged**
