### PR TITLE
Rack-UTF8Sanitizer prevents invalid byte sequent in UTF-8 request exceptions

### PR DESCRIPTION
**Pull request by bf4**
https://github.com/whitequark/rack-utf8_sanitizer is precise,
performant, and is actively maintained.

Disclaimer: I'm a collaborator.

### CODE REVIEW

**Comment by dwradcliffe** [comment]
Assuming tests pass I like this. 👍

**Comment by segiddins** [comment]
Is there any way we could add a test for the exception this is fixing?

**Comment by indirect** [comment]
Maybe an integration test? But I'm not sure how easy it is to inject invalid UTF-8 into a request using the integration test framework.

**Comment by bf4** [comment]
@segiddins I could write a test if you want.  The gem is well-tested, if you'd like to rely on that.

**Comment by dwradcliffe** [comment]
Here's a real example of a failing request:
`/api/v1/dependencies?gems=vagrant,vagrant-login,vagrant-share,vagrant%ADvbguest`

@bf4 Can you write a test for this?

**Comment by bf4** [comment]
Sure!  

B mobile phone

**Comment by dwradcliffe** [comment]
Closing in favor of #1431

**Pull request closed without merging**
