### PR TITLE
Improve zh-{CN,TW} translations

### PR DESCRIPTION
**Pull request by 0x01f7**

### CODE REVIEW

**Comment by nateberkopec** [comment]
[Got some feedback on the Twitters here.](https://twitter.com/Argorak/status/684012053829423104)

**Comment by JuanitoFatas** [comment]
Looks good! :+1:

**Comment by lulalala** [comment]
As for the untranslated word in zh-TW, I suggest:

subscribe: 訂閱
unsubscribe: 取消訂閱
report_abuse: 舉報投訴
badge: 徽章

**Comment by 0x01f7** [comment]
> As for the untranslated word in zh-TW, I suggest:
>
> subscribe: 訂閱
> unsubscribe: 取消訂閱
> report_abuse: 舉報投訴
> badge: 徽章

@lulalala , follow your advice.

**Comment by JuanitoFatas** [comment]
Still :+1: after dd447d5.

**Comment by sindhri** [comment]
It looks good!

**Comment by arthurnn** [comment]
thanks everyone

**Pull request merged**
