### PR TITLE
Declare the version of ruby required in the Gemfile (via .ruby-version)

### PR DESCRIPTION
**Pull request by colby-swandale**
Quick quality of life update the adds the `ruby` declaration into our Gemfile to ensure everyone is using the same version of Ruby

### CODE REVIEW

**Comment by segiddins** [comment]
```
[!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - /app/.ruby-version. Bundler cannot continue.
```

needs to be copied in the Dockerfile along with the Gemfile.

**Comment by simi** [comment]
> ```
> [!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - /app/.ruby-version. Bundler cannot continue.
> ```
> 
> needs to be copied in the Dockerfile along with the Gemfile.

This is one of the problems why I don't think this should be suggested for projects with fixed version. Keeping this in Gemfile (in one place) seems better option.

**Comment by colby-swandale** [comment]
> > ```
> > [!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - /app/.ruby-version. Bundler cannot continue.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > needs to be copied in the Dockerfile along with the Gemfile.
> 
> This is one of the problems why I don't think this should be suggested for projects with fixed version. Keeping this in Gemfile (in one place) seems better option.

Currently, both the `Dockerfile` and `.ruby-version` are keeping their canonical Ruby version string. Adding the Gemfile into the mix feels unnecessary and makes the process of updating to new releases of Ruby too complex for us.

**Review by simi — APPROVED** [review]

**Review by segiddins — APPROVED** [review]

**Comment by martinemde** [comment]
Long term I think we should read the ruby version from the Gemfile.lock and allow this file to be missing.

**Pull request merged**
