### PR TITLE
Rails 4.2

### PR DESCRIPTION
**Pull request by arthurnn**
### Rails 4.2

687474703a2f2f7777772e7265616374696f6e676966732e636f6d2f722f766870792e676966

### What is in here:
- Bump of rails gem, and add `responders` gem as this was extracted away from rails 4.2
- Adjust a few tests to work with 4.2
- `authors` needs to be a `Type::Value.new` now, as 4.2 changed the casting logic.

review @evanphx @qrush @indirect @dwradcliffe @sferik

### CODE REVIEW

**Comment by sferik** [comment]
Looks good to me. Can we push to staging and do some manual testing there before going live?

**Comment by arthurnn** [comment]
@sferik i tested this in staging already.. pushing and downloading gems!

**Comment by arthurnn** [comment]
@sferik deployed to production.
thanks for reviewing it :heart:

**Comment by sferik** [comment]
@arthurnn Awesome! Thanks for getting us from Rails 3.2 all the way up to 4.2!

**Pull request merged**
