### PR TITLE
Disabling content security protection for /letter_opener requests in development

### PR DESCRIPTION
**Pull request by bradly**
This addresses the issue brought up in #4459

Before:
image

After:
image

Currently letter_opener_web gem is broken due to `style` and `script` tags from both the letter_opener_web views and email markup not including the content security protection nonce attribute.

I was able to partially fix by modifying the gem to use the Rails' view helpers instead of hardcoding `<script>` and `<style>` tags, but that only fixed the letter_opener_web layout and view code–rendering the mails themselves still had issues.

I tried various configurations of setting the csp in `config/initializers/letter_opener.rb`, but didn't have any luck. I was hoping something like `LetterOpenerWeb::Engine.config.content_security_policy_nonce_directives = []` would work, but it did not.

I ended up going with a middleware to set the header if the request starts with /letter_opener. The middleware is only included in the dev environment.

I think this could(should?) be a config option for letter_opener_gem, but this at least gets things working.

### CODE REVIEW

**Comment by colby-swandale** [comment]
Would we be able to add a conditional entry to `config/initializers/content_security_policy.rb` that permits the required resources?

**Comment by simi** [comment]
Thanks for opening this @bradly. Middleware seems working well, but it is overkill IMHO. 

This seems already bypassed in `config/initializers/letter_opener.rb`, but got broken with nonce generator (just wild guessing, probably by me at https://github.com/rubygems/rubygems.org/commit/7f8ef51cc61752d8c6c4c1745ccf78d8b1c9ed76 :sob:). Disabling CSP at all is possible in there as well which seems to resolve this problem. I wasn't able to find out how to disable only nonce generator. :shrug: 

```ruby
return unless Rails.env.development?

Rails.configuration.to_prepare do
  LetterOpenerWeb::ApplicationController.content_security_policy false
end
```

And IMHO we can change the logic of applying  this to check if `LetterOpenerWeb` is defined (since it is only in development gem group).

**Comment by bradly** [comment]
@ colby-swandale  @simi Thank you both for the feedback. I agree a lightwieght approach in the initializer would be better. Let me take another crack at that.

**Comment by martinemde** [comment]
@bradly I really appreciate you tackling this. I dropped that issue here because I didn't have time to fix it. Thank you!

**Comment by bradly** [comment]
@martinemde @simi I've simplified the code and verified it is working.

**Review by martinemde — APPROVED** [review]
Very simple, thank you!

**Review by segiddins — APPROVED** [review]

**Comment by simi** [comment]
Thanks @bradly!

**Pull request merged**
