### PR TITLE
Add SimpleCov gem

### PR DESCRIPTION
**Pull request by davidsilveira**
#1779 
I suggest you add Badges to the `README.md` file. 
I can't do this because I'm not an Admin.

### CODE REVIEW

**Comment by simi** [comment]
Looks ok to me, just rebase is needed.

**Comment by davidsilveira** [comment]
@simi I did a rebase right now ;) Could you check if everything is ok?

**Comment by simi** [comment]
Rubocop is unhappy about the quotes. Can you check CI and fix?

**Comment by davidsilveira** [comment]
@simi Now everything looks ok! ;)

**Comment by colby-swandale** [comment]
succeeded by #2170

**Pull request closed without merging**
