### PR TITLE
Rails 7.2.1 Upgrade

### PR DESCRIPTION
**Pull request by JuanVqz**
I was looking for a way to contribute, and I hope you find the Rails upgrade helpful.

The test suite is showing some messages like this.

```bash
Test is missing assertions: `test_: creating a new gemcutter processing incoming gems should work normally when things go well. ` /Users/juan/code/ombu/rubygems/rubygems.org/test/models/pusher_test.rb:44
```

It is due to a recent update in Rails that suggests we include at least one assertion in the test. We can work on them; however, it's not a blocker to upgrade Rails.

Update: Just discovered a PR that adds missing assertions
https://github.com/rubygems/rubygems.org/pull/5002

### CODE REVIEW

**Review by martinemde — APPROVED** [review]
Looks good. I think it's fine to merge with the test warnings since we have a PR that's almost ready that will fix them. Thanks for your help!

**Comment by simi** [comment]
Please not merge with warnings. :pray:

**Comment by JuanVqz** [comment]
I also ran some reports, that might help you to understand the application's state and prioritize some gem upgrades

1.[ bundle-audit](https://github.com/rubysec/bundler-audit#readme): No vulnerabilities found

```bash
➜  rubygems.org git:(rails-upgrade) ✗ bundle-audit
No vulnerabilities found
```
2. [bundle_report outdated](https://github.com/fastruby/next_rails?tab=readme-ov-file#bundle_report): 53 of 307 gems are out-of-date (17%)
```bash
➜  rubygems.org git:(rails-upgrade) ✗ bundle_report outdated
benchmark-ips 2.12.0: released Jan 12, 2015 (latest version, 2.14.0, released Jan 12, 2015)
bitarray 1.2.0: released Sep 13, 2018 (latest version, 1.3.1, released Feb 11, 2024)
rb-inotify 0.10.1: released Dec 24, 2019 (latest version, 0.11.1, released May 19, 2024)
get_process_mem 0.2.7: released Aug 27, 2020 (latest version, 1.0.0, released Jul 22, 2024)
simplecov-html 0.12.3: released Sep 23, 2020 (latest version, 0.13.1, released Sep  9, 2024)
awrence 1.2.1: released Feb 18, 2021 (latest version, 3.0.0, released May  6, 2024)
pry 0.14.1: released Apr 12, 2021 (latest version, 0.14.2, released Jan  9, 2023)
pwned 2.3.0: released Aug 30, 2021 (latest version, 2.4.1, released Aug 29, 2022)
version_gem 1.1.1: released Sep 19, 2022 (latest version, 1.1.4, released Mar 21, 2024)
cose 1.3.0: released Oct 28, 2022 (latest version, 1.3.1, released Aug 12, 2024)
tpm-key_attestation 0.12.0: released Feb 15, 2023 (latest version, 0.12.1, released Aug  5, 2024)
ruby-statistics 3.0.2: released Apr 17, 2023 (latest version, 4.0.1, released Aug 13, 2024)
jwt 2.7.1: released Jun  9, 2023 (latest version, 2.9.0, released Sep 15, 2024)
dogstatsd-ruby 5.6.1: released Sep  7, 2023 (latest version, 5.6.2, released Sep 20, 2024)
tilt 2.3.0: released Sep 14, 2023 (latest version, 2.4.0, released Jun 27, 2024)
unicode-display_width 2.5.0: released Oct  1, 2023 (latest version, 2.6.0, released Sep 13, 2024)
turbo-rails 1.5.0: released Oct 11, 2023 (latest version, 2.0.9, released Sep 18, 2024)
turbo_power 0.5.0: released Oct 15, 2023 (latest version, 0.6.2, released Jun  9, 2024)
hashdiff 1.1.0: released Dec 14, 2023 (latest version, 1.1.1, released Aug  2, 2024)
factory_bot 6.4.5: released Dec 30, 2023 (latest version, 6.5.0, released Sep  6, 2024)
childprocess 5.0.0: released Jan  7, 2024 (latest version, 5.1.0, released Aug  6, 2024)
rspec-core 3.13.0: released Feb  4, 2024 (latest version, 3.13.1, released Sep  3, 2024)
honeybadger 5.5.1: released Feb 26, 2024 (latest version, 5.16.0, released Sep 19, 2024)
yard 0.9.36: released Feb 29, 2024 (latest version, 0.9.37, released Sep  4, 2024)
sass-embedded 1.72.0: released Mar 13, 2024 (latest version, 1.79.3, released Sep 20, 2024)
sassc-embedded 1.70.1: released Mar 14, 2024 (latest version, 1.78.0, released Sep  3, 2024)
css_parser 1.17.1: released Apr  7, 2024 (latest version, 1.19.0, released Aug 23, 2024)
shoulda-context 3.0.0.rc1: released Apr 23, 2024 (latest version, 2.0.0, released Jun 13, 2020)
rubocop-ast 1.31.3: released Apr 29, 2024 (latest version, 1.32.3, released Sep  4, 2024)
phlex 1.10.2: released Apr 29, 2024 (latest version, 1.11.0, released Jul  6, 2024)
http-cookie 1.0.6: released Jun  1, 2024 (latest version, 1.0.7, released Aug 14, 2024)
parallel 1.25.1: released Jun  8, 2024 (latest version, 1.26.3, released Aug 16, 2024)
rspec-expectations 3.13.1: released Jun 13, 2024 (latest version, 3.13.3, released Sep  7, 2024)
rouge 4.3.0: released Jun 14, 2024 (latest version, 4.4.0, released Sep 17, 2024)
rubocop-performance 1.21.1: released Jun 16, 2024 (latest version, 1.22.1, released Sep 17, 2024)
rubocop-rails 2.25.1: released Jun 29, 2024 (latest version, 2.26.2, released Sep 21, 2024)
pagy 8.6.3: released Jul  3, 2024 (latest version, 9.0.9, released Sep  9, 2024)
semantic_logger 4.16.0: released Jul  4, 2024 (latest version, 4.16.1, released Sep  5, 2024)
rubocop-minitest 0.35.1: released Jul 10, 2024 (latest version, 0.36.0, released Aug 31, 2024)
parser 3.3.4.0: released Jul 10, 2024 (latest version, 3.3.5.0, released Sep  4, 2024)
good_job 3.99.1: released Jul 10, 2024 (latest version, 4.3.0, released Sep 14, 2024)
rubocop 1.65.0: released Jul 10, 2024 (latest version, 1.66.1, released Sep  4, 2024)
meta-tags 2.22.0: released Jul 15, 2024 (latest version, 2.22.1, released Sep 20, 2024)
libdatadog 11.0.0.1.0: released Jul 22, 2024 (latest version, 12.0.0.1.0, released Sep  4, 2024)
selenium-webdriver 4.24.0: released Aug 28, 2024 (latest version, 4.25.0, released Sep 20, 2024)
net-imap 0.4.15: released Aug 28, 2024 (latest version, 0.4.16, released Sep  4, 2024)
rexml 3.3.6: released Sep  3, 2024 (latest version, 3.3.7, released Sep  4, 2024)
aws-sdk-sqs 1.83.0: released Sep 11, 2024 (latest version, 1.84.0, released Sep 20, 2024)
avo 2.53.0: released Sep 11, 2024 (latest version, 3.12.0, released Sep  3, 2024)
aws-sdk-kms 1.91.0: released Sep 11, 2024 (latest version, 1.92.0, released Sep 20, 2024)
aws-sdk-core 3.206.0: released Sep 17, 2024 (latest version, 3.207.0, released Sep 20, 2024)
datadog-ci 1.5.0: released Sep 18, 2024 (latest version, 1.6.0, released Sep 20, 2024)
aws-sdk-s3 1.163.0: released Sep 18, 2024 (latest version, 1.164.0, released Sep 20, 2024)

0 gems are sourced from git
53 of the 307 gems are out-of-date (17%)
```

**Comment by JuanVqz** [comment]
> See #5064 which also runs the update task

Your PR also has the warnings in the tests, [CI logs](https://github.com/rubygems/rubygems.org/actions/runs/11000336844/job/30542510107?pr=5064#step:4:69)

**Comment by simi** [comment]
Most of the warnings are fixed in https://github.com/rubygems/rubygems.org/pull/5002. I'll merge that soon after small tweak.

**Comment by colby-swandale** [comment]
Any chance we can merge #5064 together with this PR?

**Pull request merged**
