### PR TITLE
Add more metrics to the admin dashboard

### PR DESCRIPTION
**Pull request by segiddins**
image

### CODE REVIEW

**Review by simi — APPROVED** [review]

**Comment by indirect** [comment]
Here's my list:
1. `User.count` (I think that's "Total Users"?)
2. `RubyGem.count` (I think that's "RubyGems (All)"?)
3. `Version.count` (all time, not created in the last month)
4. Failed request count and/or SLA results

Ideally, I would also be able to swap all of those together to other shorter timeframes:
- all time (doesn't have to be the default as long as it's an option)
- 1 month
- 1 year

Numbers that I'm not sure how to fit into the all/1mo/1yr paradigm are:

1. Total downloads number (from the homepage)
2. Req/sec over the last 1 month
3. Total requests served over the last 1 month
5. MB/sec over the last 1 month
6. MB total downloads over the last 1 month

**Comment by segiddins** [comment]
> Failed request count and/or SLA results

I'm not sure that's a thing we can query from the RubyGems db?

**Comment by segiddins** [comment]
> Version.count (all time, not created in the last month)

It's selectable, defaults to all time (same as Rubygem count)

**Comment by indirect** [comment]
I believe these have to come from Fastly and/or DataDog:

- Failed request count and/or SLA results
- Req/sec over the last 1 month
- Total requests served over the last 1 month
- MB/sec over the last 1 month
- MB total downloads over the last 1 month

And to be clear, I am happy to merge this PR and add more (including these items above) in a later PR.

**Review by indirect — APPROVED** [review]

**Pull request merged**
