### PR TITLE
Make username uniqueness case insensitive 

### PR DESCRIPTION
**Pull request by Mab879**
Don't allow theft of users by allowing a uppercase and lowercase version of the same username.

### CODE REVIEW

**Comment by davefp** [comment]
@Mab879 As a result of #610 a large chunk of the repo's history was re-written. Please rebase your PR so that it will merge cleanly. Thanks!

(There are further details on the blog: http://blog.rubygems.org/2015/02/01/rewriting-history.html)

**Comment by arthurnn** [comment]
Before merging this, we need to make sure we dont have any colliding handles already.
@dwradcliffe , can you run this on production DB, and tell me if it returns any result:
```
SELECT count(*), lower(handle)
FROM   users
GROUP  BY lower(handle)
HAVING count(*) > 1;
```

**Comment by kbrock** [comment]
How was this left?

@arthurnn @dwradcliffe Are there a lot of dups here?

If you want this, I can rebase / add tests.

**Comment by dwradcliffe** [comment]
@arthurnn Yes, lots of duplicates.

**Comment by arthurnn** [comment]
As we are have 658 dups, unfortunately we cannot merge this patch without deleting or changing those usernames.

Thanks anyways.

**Comment by dwradcliffe** [comment]
There's probably another way to do this for new users only. I think there is still value in preventing new users from picking usernames the "same" as existing.

**Comment by arthurnn** [comment]
@dwradcliffe yeah, however AFAIK, if we add this `validates_uniqueness_of`, it would fail to save one of those 658 records.
@Mab879 if you have another suggestion on how to tackle this, fell free to open a new PR.
thanks

**Pull request closed without merging**
