### PR TITLE
Remove version history model and table 

### PR DESCRIPTION
**Pull request by sonalkr132**
Attempt - II

My previous PR was roasted #1277:
> PG::DependentObjectsStillExist: ERROR:  cannot drop table version_histories because other objects depend on it

Hopefully this will work :pray: :construction_worker:

### CODE REVIEW

**Comment by simi** [comment]
Can you update https://github.com/rubygems/rubygems.org/blob/master/CONTRIBUTING.md#database-layout also? I think there's a rake task for that in https://github.com/rubygems/rubygems.org/blob/master/lib/tasks/gen_erd.rake.

**Comment by sonalkr132** [comment]
@simi thanks. I have updated it.

What do people think about using png instead of svg? With svg, everything gets smushed together and I am seeing columns types like `stringâ€Šâˆ— U` (in place of `string *`).
svg:
https://github.com/sonalkr132/rubygems.org/blob/force_r-version_history/doc/erd.svg

png:
erd

**Comment by simi** [comment]
I can see properly rendered svg on your lin, but it wasn't updated for a while.
I have no idea what's preferred here now. Do we need Doorkeeper and LogTicket in erd scheme?

*If we need to keep erd updated, we can add it to specs (I can contribute this).*

**Comment by dwradcliffe** [comment]
Yes let's keep it updated. Png is fine with me if it renders fine/better.

---
David Radcliffe

**Comment by sonalkr132** [comment]
@simi this is what svg looks on my computer.

screenshot from 2016-05-24 18-42-49

**Comment by simi** [comment]
Weird, browser and image viewer is ok with that. I think we can open new issue for this, since it is not related to this PR.


snimek z 2016-05-24 15-20-37

**Comment by dwradcliffe** [comment]
Ohhh! The problem is there is another table! The error message even says that, I just didn't notice. There is a `version_histories_import` table which is linked to the `version_histories` table. I have tested this on staging and it works. I'm going to merge this because I've already run this but we still need to remove the other table. @sonalkr132 can you send a new PR to remove the `version_histories_import` table?

**Comment by sonalkr132** [comment]
we are putting the table to peace :skull:  manual way.

**Pull request merged**
