### PR TITLE
Move sign_in_as method to a test helper

### LINKED ISSUE #4791: Refactor tests to cleanup redefined `sign_in_as`
Seems it is defined as needed in tests itself.

```
❤ grep -r "def sign_in_as" test/
test/integration/owner_test.rb:  def sign_in_as(user)
test/integration/rack_attack_test.rb:  def sign_in_as(user)
test/system/avo/events_test.rb:  def sign_in_as(user)
test/system/avo/oidc_api_key_roles_test.rb:  def sign_in_as(user)
test/system/avo/users_test.rb:  def sign_in_as(user)
test/system/avo/web_hooks_test.rb:  def sign_in_as(user)
test/system/avo/rubygems_test.rb:  def sign_in_as(user)
test/system/avo/versions_test.rb:  def sign_in_as(user)
test/system/avo/sendgrid_events_test.rb:  def sign_in_as(user)
test/system/avo/manual_changes_test.rb:  def sign_in_as(user)
test/system/avo/oidc_providers_test.rb:  def sign_in_as(user)
test/system/maintenance_tasks_test.rb:  def sign_in_as(user)
```

_Originally posted by @simi in https://github.com/rubygems/rubygems.org/pull/4744#discussion_r1615335385_

### PR DESCRIPTION
**Pull request by JuanVqz**
Closes #4791

Please, let me know if this is good enough or if there's anything else I need to do

### CODE REVIEW

**Comment by simi** [comment]
Hello @JuanVqz and thanks for the PR. It look good. Let's see what CI thinks about.

**Comment by simi** [comment]
@JuanVqz it seems some system test are failing and linter has some violaitons. Would you mind to fix those? You can run system tests using `bin/rails test:system` (they are skipped by default, that's rails default behaviour). For linter it should be enough to run `bin/rubocop -A` to let it fix the problem on its own.

**Comment by JuanVqz** [comment]
> @JuanVqz it seems some system test are failing and linter has some violaitons. Would you mind to fix those? You can run system tests using `bin/rails test:system` (they are skipped by default, that's rails default behaviour). For linter it should be enough to run `bin/rubocop -A` to let it fix the problem on its own.

Hey @simi thanks for the quick response, it should be fixed now

**Comment by martinemde** [comment]
@JuanVqz Thanks for the refactor!

**Pull request merged**
