### PR TITLE
Add comprehensive stats for good job

### PR DESCRIPTION
**Pull request by segiddins**
Both around the activejob lifecycle & the jobs we can see in the db every 15s

### CODE REVIEW

**Comment by simi** [comment]
@segiddins Can you share DB queries started by the job?

**Comment by simi** [comment]
Btw. I like the concept. Currently DJ stats are collected by https://github.com/rubygems/rubygems.org/blob/master/config/deploy/delayed_job_statsd.yaml.erb (https://github.com/dwradcliffe/delayed_job_statsd/blob/master/run.rb) if I understand it well. With GJ it seems easier to keep the logic within app itself. On the other side, is it really started each 15s or added to queue each 15s? Original approach was started 15s after each run.

**Comment by segiddins** [comment]
@simi output from running the job is (showing queries and statsd calls):

```
Performing GoodJobStatsDJob (Job ID: 2ac59960-7dae-4470-bcd2-06ebc7e97855) from GoodJob(default) enqueued at 
[StatsD] measure rails.perform_start.active_job.total_duration:0.43599987030029297 #queue:default #job_class:GoodJobStatsDJob #adapter:ActiveJob::QueueAdapters::GoodJobAdapter #env:development
[StatsD] histogram rails.perform_start.active_job.allocations:145 #queue:default #job_class:GoodJobStatsDJob #adapter:ActiveJob::QueueAdapters::GoodJobAdapter #env:development
[StatsD] increment rails.perform_start.active_job.success:1 #queue:default #job_class:GoodJobStatsDJob #adapter:ActiveJob::QueueAdapters::GoodJobAdapter #env:development
  GoodJob::Job Count (6.9ms)  SELECT COUNT(*) AS "count_all", "good_jobs"."queue_name" AS "good_jobs_queue_name", "good_jobs"."priority" AS "good_jobs_priority", serialized_params->>'job_class' AS "serialized_params_job_class" FROM "good_jobs" WHERE "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."finished_at" IS NULL AND (COALESCE(scheduled_at, created_at) > '2023-02-28 08:53:33.421220') AND ((serialized_params->>'executions')::integer < 2) GROUP BY "good_jobs"."queue_name", "good_jobs"."priority", serialized_params->>'job_class'      
  GoodJob::Job Count (0.8ms)  SELECT COUNT(*) AS "count_all", "good_jobs"."queue_name" AS "good_jobs_queue_name", "good_jobs"."priority" AS "good_jobs_priority", serialized_params->>'job_class' AS "serialized_params_job_class" FROM "good_jobs" WHERE "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."finished_at" IS NULL AND (COALESCE(scheduled_at, created_at) > '2023-02-28 08:53:33.433032') AND ((serialized_params->>'executions')::integer > 1) GROUP BY "good_jobs"."queue_name", "good_jobs"."priority", serialized_params->>'job_class'      
  GoodJob::Job Count (3.8ms)  SELECT COUNT(*) AS "count_all", "good_jobs"."queue_name" AS "good_jobs_queue_name", "good_jobs"."priority" AS "good_jobs_priority", serialized_params->>'job_class' AS "serialized_params_job_class" FROM "good_jobs" LEFT JOIN pg_locks ON pg_locks.locktype = 'advisory' AND pg_locks.objsubid = 1 AND pg_locks.classid = ('x' || substr(md5('good_jobs' || '-' || "good_jobs"."active_job_id"::text), 1, 16))::bit(32)::int AND pg_locks.objid = (('x' || substr(md5('good_jobs' || '-' || "good_jobs"."active_job_id"::text), 1, 16))::bit(64) << 32)::bit(32)::int WHERE "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."finished_at" IS NULL AND (COALESCE(scheduled_at, created_at) <= '2023-02-28 08:53:33.434894') AND "pg_locks"."locktype" IS NULL GROUP BY "good_jobs"."queue_name", "good_jobs"."priority", serialized_params->>'job_class'
  GoodJob::Job Count (1.2ms)  SELECT COUNT(*) AS "count_all", "good_jobs"."queue_name" AS "good_jobs_queue_name", "good_jobs"."priority" AS "good_jobs_priority", serialized_params->>'job_class' AS "serialized_params_job_class" FROM "good_jobs" LEFT JOIN pg_locks ON pg_locks.locktype = 'advisory' AND pg_locks.objsubid = 1 AND pg_locks.classid = ('x' || substr(md5('good_jobs' || '-' || "good_jobs"."active_job_id"::text), 1, 16))::bit(32)::int AND pg_locks.objid = (('x' || substr(md5('good_jobs' || '-' || "good_jobs"."active_job_id"::text), 1, 16))::bit(64) << 32)::bit(32)::int WHERE "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."finished_at" IS NULL AND "pg_locks"."locktype" IS NOT NULL GROUP BY "good_jobs"."queue_name", "good_jobs"."priority", serialized_params->>'job_class'
  GoodJob::Job Count (2.7ms)  SELECT COUNT(*) AS "count_all", "good_jobs"."queue_name" AS "good_jobs_queue_name", "good_jobs"."priority" AS "good_jobs_priority", serialized_params->>'job_class' AS "serialized_params_job_class" FROM "good_jobs" WHERE "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."finished_at" IS NOT NULL AND "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."error" IS NULL GROUP BY "good_jobs"."queue_name", "good_jobs"."priority", serialized_params->>'job_class'                                                  
  GoodJob::Job Count (0.5ms)  SELECT COUNT(*) AS "count_all", "good_jobs"."queue_name" AS "good_jobs_queue_name", "good_jobs"."priority" AS "good_jobs_priority", serialized_params->>'job_class' AS "serialized_params_job_class" FROM "good_jobs" WHERE "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."finished_at" IS NOT NULL AND "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."error" IS NOT NULL GROUP BY "good_jobs"."queue_name", "good_jobs"."priority", serialized_params->>'job_class'
  GoodJob::Job Maximum (0.7ms)  SELECT MAX(NOW() - COALESCE(scheduled_at, created_at)) AS "maximum_now_coalesce_scheduled_at_created_at", "good_jobs"."queue_name" AS "good_jobs_queue_name", "good_jobs"."priority" AS "good_jobs_priority", serialized_params->>'job_class' AS "serialized_params_job_class" FROM "good_jobs" WHERE "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."finished_at" IS NULL AND (COALESCE(scheduled_at, created_at) > '2023-02-28 08:53:33.452627') AND ((serialized_params->>'executions')::integer < 2) GROUP BY "good_jobs"."queue_name", "good_jobs"."priority", serialized_params->>'job_class'
  GoodJob::Job Maximum (0.4ms)  SELECT MAX(NOW() - COALESCE(scheduled_at, created_at)) AS "maximum_now_coalesce_scheduled_at_created_at", "good_jobs"."queue_name" AS "good_jobs_queue_name", "good_jobs"."priority" AS "good_jobs_priority", serialized_params->>'job_class' AS "serialized_params_job_class" FROM "good_jobs" WHERE "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."finished_at" IS NULL AND (COALESCE(scheduled_at, created_at) > '2023-02-28 08:53:33.454157') AND ((serialized_params->>'executions')::integer > 1) GROUP BY "good_jobs"."queue_name", "good_jobs"."priority", serialized_params->>'job_class'
  GoodJob::Job Maximum (0.7ms)  SELECT MAX(NOW() - COALESCE(scheduled_at, created_at)) AS "maximum_now_coalesce_scheduled_at_created_at", "good_jobs"."queue_name" AS "good_jobs_queue_name", "good_jobs"."priority" AS "good_jobs_priority", serialized_params->>'job_class' AS "serialized_params_job_class" FROM "good_jobs" LEFT JOIN pg_locks ON pg_locks.locktype = 'advisory' AND pg_locks.objsubid = 1 AND pg_locks.classid = ('x' || substr(md5('good_jobs' || '-' || "good_jobs"."active_job_id"::text), 1, 16))::bit(32)::int AND pg_locks.objid = (('x' || substr(md5('good_jobs' || '-' || "good_jobs"."active_job_id"::text), 1, 16))::bit(64) << 32)::bit(32)::int WHERE "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."finished_at" IS NULL AND (COALESCE(scheduled_at, created_at) <= '2023-02-28 08:53:33.455114') AND "pg_locks"."locktype" IS NULL GROUP BY "good_jobs"."queue_name", "good_jobs"."priority", serialized_params->>'job_class'
  GoodJob::Job Maximum (0.6ms)  SELECT MAX(NOW() - COALESCE(scheduled_at, created_at)) AS "maximum_now_coalesce_scheduled_at_created_at", "good_jobs"."queue_name" AS "good_jobs_queue_name", "good_jobs"."priority" AS "good_jobs_priority", serialized_params->>'job_class' AS "serialized_params_job_class" FROM "good_jobs" LEFT JOIN pg_locks ON pg_locks.locktype = 'advisory' AND pg_locks.objsubid = 1 AND pg_locks.classid = ('x' || substr(md5('good_jobs' || '-' || "good_jobs"."active_job_id"::text), 1, 16))::bit(32)::int AND pg_locks.objid = (('x' || substr(md5('good_jobs' || '-' || "good_jobs"."active_job_id"::text), 1, 16))::bit(64) << 32)::bit(32)::int WHERE "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."finished_at" IS NULL AND "pg_locks"."locktype" IS NOT NULL GROUP BY "good_jobs"."queue_name", "good_jobs"."priority", serialized_params->>'job_class'
  GoodJob::Job Maximum (0.7ms)  SELECT MAX(NOW() - COALESCE(scheduled_at, created_at)) AS "maximum_now_coalesce_scheduled_at_created_at", "good_jobs"."queue_name" AS "good_jobs_queue_name", "good_jobs"."priority" AS "good_jobs_priority", serialized_params->>'job_class' AS "serialized_params_job_class" FROM "good_jobs" WHERE "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."finished_at" IS NOT NULL AND "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."error" IS NULL GROUP BY "good_jobs"."queue_name", "good_jobs"."priority", serialized_params->>'job_class'
  GoodJob::Job Maximum (1.0ms)  SELECT MAX(NOW() - COALESCE(scheduled_at, created_at)) AS "maximum_now_coalesce_scheduled_at_created_at", "good_jobs"."queue_name" AS "good_jobs_queue_name", "good_jobs"."priority" AS "good_jobs_priority", serialized_params->>'job_class' AS "serialized_params_job_class" FROM "good_jobs" WHERE "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."finished_at" IS NOT NULL AND "good_jobs"."retried_good_job_id" IS NULL AND "good_jobs"."error" IS NOT NULL GROUP BY "good_jobs"."queue_name", "good_jobs"."priority", serialized_params->>'job_class'
[StatsD] gauge good_job.count:240 #state:succeeded #queue:default #priority:10 #job_class:GoodJobStatsDJob #env:development
[StatsD] gauge good_job.count:1 #state:succeeded #queue:default #priority:0 #job_class:ExampleJob #env:development
[StatsD] gauge good_job.count:3 #state:succeeded #queue:default #priority:0 #job_class:GoodJobStatsDJob #env:development
[StatsD] gauge good_job.count:5 #state:discarded #queue:default #priority:0 #job_class:GoodJobStatsDJob #env:development
[StatsD] gauge good_job.staleness:36562.127582 #state:succeeded #queue:default #priority:10 #job_class:GoodJobStatsDJob #env:development
[StatsD] gauge good_job.staleness:310429.726382 #state:succeeded #queue:default #priority:0 #job_class:ExampleJob #env:development
[StatsD] gauge good_job.staleness:27697.51059 #state:succeeded #queue:default #priority:0 #job_class:GoodJobStatsDJob #env:development
[StatsD] gauge good_job.staleness:28763.358538 #state:discarded #queue:default #priority:0 #job_class:GoodJobStatsDJob #env:development
Performed GoodJobStatsDJob (Job ID: 2ac59960-7dae-4470-bcd2-06ebc7e97855) from GoodJob(default) in 121.82ms
[StatsD] measure rails.perform.active_job.total_duration:121.66100025177002 #queue:default #job_class:GoodJobStatsDJob #adapter:ActiveJob::QueueAdapters::GoodJobAdapter #env:development
[StatsD] histogram rails.perform.active_job.allocations:23836 #queue:default #job_class:GoodJobStatsDJob #adapter:ActiveJob::QueueAdapters::GoodJobAdapter #env:development
[StatsD] increment rails.perform.active_job.success:1 #queue:default #job_class:GoodJobStatsDJob #adapter:ActiveJob::QueueAdapters::GoodJobAdapter #env:development
```

The cron job will only run 1 at a time, see https://github.com/bensheldon/good_job/#cron-style-repeatingrecurring-jobs, so it should be enqueued every 15s. Given runtime is super fast, im not too worried

**Comment by simi** [comment]
@segiddins my concern was about the time when queue is full of jobs. Than it could be delayed. But let's start with something.

**Pull request merged**
