### PR TITLE
Add Guard for faster test feedback

### PR DESCRIPTION
**Pull request by ktheory**
[Guard](https://github.com/guard/guard) is a test autorunner that allows a more seamless test feedback
loop during development.

How to use it:
1. Run `bundle exec guard`
2. Watch *all* tests run :turtle: 
3. Make a code change
4. Watch `guard` automatically run just the relevant tests :rabbit2: 
5. GOTO step 3 :repeat:

### CODE REVIEW

**Comment by nateberkopec** [comment]
I'm not a fan of adding gems to the `development` group that not every developer will use. Many people already have their own test-autorunners set up in their text editors/IDEs, some just prefer not to use these tools. On an open source project like rubygems.org, I feel it's inappropriate to force everyone to install a tool that only a minority of contributors will use.

That said, I want everyone and their grandma to contribute to rubygems.org, so you should have whatever tools you feel you need to do that. [There are ways with Bundler to load developer-specific gemfiles](https://github.com/manageiq/manageiq/blob/c0aa211f645c4b88d377d77d2028d4dedd43719f/Gemfile#L154-L160). I would be in favor of such an approach, if anything is to be done here.

**Comment by nateberkopec** [comment]
An alternative approach might be to add `Gemfile.dev` and `Gemfile.dev.lock` to `.gitignore`. 

Then you should be able to do this:

```
bundle config --local gemfile Gemfile.dev
```

...and you can do whatever you want in `Gemfile.dev`. I think there must be some some sane way to make one Gemfile `require` another so you don't have to copy everything over to `Gemfile.dev` too, but I don't recall.

**Comment by simi** [comment]
@nateberkopec that approach works only when Gemfile.lock is not part of the repository.

for example https://github.com/refinery/refinerycms/blob/d91d3fe9ac2d5f9e4142ca6e4c3e030bbb9f1362/Gemfile#L45-L47

*PS: I'm not fan of adding this also.*

**Comment by ktheory** [comment]
@nateberkopec, thanks for the suggestion. I certainly wouldn't want to force anyone to use `guard`, or exclude alternatives.

I'm trying to understand the harm in having a development dependencies that not everyone uses. Is the concern disk space? Or keeping the Gemfile small?

My motivation in this PR was to streamline the development process with an easy default convention, rather than expecting devs to configure it themselves.

Reflecting on my motivation, I realize that my preference is to have the following ready-to-go when I clone a new ruby project:

- test framework (minitest, rspec, etc)
- test autorunner (guard, minitest-autorunner, etc)
- debugger (pry, byebug, etc; I'd like to add one to rubygems.org too. :wink:)

Of course which test framework, etc will vary across ruby projects, but I'm comfortable following each project's conventions. Or maybe these aren't as widely useful as I suppose.

This is all to say, I think this PR still has value; though I'm comfortable using the `Gemfile.dev` approach if/when #1177 gets merged.

And I think #1177 is valuable regardless of this PR, since it allows more developer flexibility in general.

If #1177 is merged would we still add the [`Guardfile`](https://github.com/ktheory/rubygems.org/blob/2179d41e4929206c3d19320d9b0061826cc8ccd9/Guardfile) in this PR, or add it to `.gitignore` and devs would write their own?

**Comment by dwradcliffe** [comment]
One consideration, specific to this project, is that we vendor all gems. This does make me think twice before adding any gems, especially ones that are not used in production.

**Comment by arthurnn** [comment]
Does guard realods the entire environment?  Does it use Spring? does it implement something like spring to pre-load and fork after?

**Comment by ktheory** [comment]
Thanks for the discussion! :information_desk_person: 

Gonna close this out. On balance, adding `guard` is not a clear win (and I learned it's not as common a workflow as I'd assumed).

**Pull request closed without merging**
