### PR TITLE
Add previously missing german translations

### PR DESCRIPTION
**Pull request by CuddlyBunion341**
Many translations needed to be included previously on rubygems.org, especially on the landing page. This Pull Request is my attempt at translating the locales based on English and French translations, despite https://github.com/rubygems/rubygems.org/blob/master/CONTRIBUTING.md#acceptance mentioning that the community won't accept contributions without tests. In my understanding, this rule shouldn't affect configuration/locale files.

Thank you for considering this contribution!

CleanShot 2024-02-20 at 15 30 39@2x

### CODE REVIEW

**Comment by simi** [comment]
Hello @CuddlyBunion341 and thanks for the translations. I'll leave this open for few days to make it possible to another :de: speaking person to do review. Per my basic :de: language knowledge it looks ok.

No worries, tests are not needed for translations (should we update the template?).

**Comment by coorasse** [comment]
@CuddlyBunion341 might you involve somebody else at Renuo for a review? We have tons of german speakers ;)

**Comment by CuddlyBunion341** [comment]
I'll try my best to @coorasse.

**Review by ekyburz — COMMENTED** [review]
The german grammar looks great and I couldn't find any spelling mistakes.

**Pull request merged**
