### PR TITLE
Update to bundler 2.5.1 and add CHECKSUMS

### PR DESCRIPTION
**Pull request by martinemde**
There's a chance that we will have trouble during deploy, so maybe we should deploy this on its own.

### CODE REVIEW

**Comment by segiddins** [comment]
Mind if I also update the docker image, and have us on matching rubygems version as well?

**Comment by segiddins** [comment]
```
❯ BUNDLE_FROZEN=1 bundle
Cannot write a changed lockfile while frozen.
```

**Comment by martinemde** [comment]
@segiddins feel free to take this over if you want. I just wanted to get it started.

**Comment by martinemde** [comment]
Seems like we need to skip checksums for now.

**Pull request merged**
