### PR TITLE
Refactor the mailer content to specify the MFA implementation used (TOTP)

### PR DESCRIPTION
**Pull request by george-ma**
## What problem are you solving?
Closes https://github.com/Shopify/ruby-dependency-security/issues/331
Refactored the email content to specify the MFA implementation used (TOTP)

## What should reviewers focus on?
Not the biggest fan of the lengthiness of some of the content:

ie. the email subject
> TOTP multi-factor authentication disabled on RubyGems.org

and the content body
> (TOTP (Time-Based One-Time Password) multi-factor authentication)

but also just didn't like the way TOTP MFA looked (acronym overload), but I would be okay to change some/both of these if there any suggestions 😄

## Testing 🎩
Borrowing the testing instructions from a [previous PR](https://github.com/rubygems/rubygems.org/pull/3779) within the same section of code  (thanks @garyhtou):
1. Setup OTP MFA at http://localhost:3000/settings/edit
2. Go to http://localhost:3000/letter_opener and verify MFA Enabled mailer was sent
3. Disable OTP MFA at http://localhost:3000/settings/edit
4. Go to http://localhost:3000/letter_opener and verify MFA Disabled mailer was sent
---
Can also view the updated mailers individually through http://localhost:3000/rails/mailers
- Select "totp_disabled" / "totp_enabled"
<p align="center">
  <kbd>
    
    
  </kbd>
</p>

### CODE REVIEW

**Review by simi — APPROVED** [review]

**Comment by simi** [comment]
Thanks for the PR. Change looks good to me, but since I'm not native English speaker I'll leave this open for additional reviewer.

**Review by bettymakes — COMMENTED** [review]
👍 Looks good! Thanks for helping to refactor this George.

I'm torn on the email heading title as well. Not a fan of the double acronyms. TOTP is too long to spell out, I think we can still work with spelling out MFA. Here are some alternatives I thought of. What do you think about these options?

* TOTP Multi-factor Authentication Enabled
* Multi-factor Authentication Enabled: TOTP
* MFA Enabled: One-Time Password
  * I know I dropped the "Time-Based" part in this title. I figured it'd be an acceptable in-between since the email body notes that it's TOTP. 


<p align="center">
  <kbd>
    Mailer with heading: TOTP Multi-factor Authentication Enabled
  </kbd>
</p>

<p align="center">
  <kbd>
    Mailer with heading: Multi-factor Authentication Enabled: TOTP
  </kbd>
</p>


<p align="center">
  <kbd>
    Mailer with heading: MFA Enabled: One-Time Password
  </kbd>
</p>

**Comment by george-ma** [comment]
Email subject title changed to: `Authentication app enabled on RubyGems.org`

After some more discussions with Betty/Jenny, the rest of the email looks like this:
<p align="center">
  <kbd>
    
  </kbd>
</p>

let me know if this looks good! cc: @bettymakes

**Review by segiddins — APPROVED** [review]

**Comment by bettymakes** [comment]
Changes look good! 🚀

**Pull request merged**
