### PR TITLE
Add missing translation for zh-CN

### PR DESCRIPTION
**Pull request by coderliu**
- Fix missing translation
- Enrich zh-CN locale file

image
image
image

### CODE REVIEW

**Comment by coderliu** [comment]
TravisCI build failed with 
image
I think this has no relevance with my modification.

**Comment by coderliu** [comment]
Even this PR has been merged, there still a lot of  translation is missing, especially the email part.

If you are willing, when I have enough spare time, I will translate the email part.

**Comment by dwradcliffe** [comment]
> TravisCI build failed

If you rebase this PR on master this should be fixed.

**Comment by dwradcliffe** [comment]
Thanks for the pull request! We usually like to get at least one review before merging translation changes. (I'm unqualified to review this 😄)

**Comment by ecnelises** [comment]
I remember there're two existing PRs regarding zh-CN translation. (Although one is out of date)
https://github.com/rubygems/rubygems.org/pull/1712
https://github.com/rubygems/rubygems.org/pull/1797

**Comment by coderliu** [comment]
> I remember there're two existing PRs regarding zh-CN translation. (Although one is out of date)
> #1712
> #1797

As you said, #1712 is a little bit out dated.

#1797 is newer, but only contain one change in zh-CN which conflict with mine.

**Comment by ecnelises** [comment]
> #1797 is newer, but only contains one change in zh-CN which conflict with mine.

Yes, I'm just curious about how we choose one version.

**Comment by sonalkr132** [comment]
We haven't had any update on #1712 in a while for changes requested. @coderliu, it would super nice if you could cherry-pick changes form it and we can close that PR.

**Comment by coderliu** [comment]
> We haven't had any update on #1712 in a while for changes requested. @coderliu, it would super nice if you could cherry-pick changes form it and we can close that PR.

I will merge changes from #1712 by manual. Should I keep all changes in one commit?

**Comment by sonalkr132** [comment]
> Should I keep all changes in one commit?

yes, please.

**Comment by coderliu** [comment]
> > #1797 is newer, but only contains one change in zh-CN which conflict with mine.
> 
> Yes, I'm just curious about how we choose one version.

if you are talking about translation of `search_gem`, I think `搜索 Gem` is better than `寻找 Gem`. Because `advanced_search` was translated to `高级搜索`, `search_gem` should consistent with it, which means we had better translate `search`  to `搜索`.

**Comment by coderliu** [comment]
@sonalkr132 Updated.

**Comment by coderliu** [comment]
What are you waiting for ?

**Comment by sonalkr132** [comment]
> We usually like to get at least one review before merging translation changes. 

Sorry about delay in getting this merged. Perhaps @ecnelises can go over this and approve?

**Comment by ecnelises** [comment]
Yes, I can go through this.

**Comment by sonalkr132** [comment]
> #1803 There is no problem in these translations.

Thanks @bastengao

**Comment by ecnelises** [comment]
Sorry for the delay 😄 but I think I should add zh-CN translations on MFA after my PRs got merged.

**Pull request merged**
