### PR TITLE
[WIP] Use propshaft instead of sprockets

### PR DESCRIPTION
**Pull request by segiddins**

### CODE REVIEW

**Comment by indirect** [comment]
I like the idea of switching to propshaft! I don't really feel like the 5 npm packages we use justify using esbuild. Can we use [importmap-rails](https://github.com/rails/importmap-rails) and skip the entire JS build step, removing esbuild and jsbundling entirely?

Related, since we don't seem to actually have any Sass, can we switch to completely vanilla CSS files (with [regular-ass @import statements](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) if needed), and completely skip the Sass step?

If we do both of those things, we should be able to
1) avoid Node entirely for our assets and,
2) still use and update npm packages for JS,
which is (in my opinion) the main selling point of propshaft vs sprockets.

**Comment by hsbt** [comment]
> Related, since we don't seem to actually have any Sass, can we switch to completely vanilla CSS files (with [regular-ass @import statements](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) if needed), and completely skip the Sass step?

or to use [dartsass-rails](https://github.com/rails/dartsass-rails) and importmap-rails?

I have no strong opinion about jsbundling-rails/cssbundling-rails vs importmap-rails/dartsass-rails(or propshaft with sass).

**Comment by indirect** [comment]
Oh yeah, if we really need Sass we can use dartsass-rails and also skip Node 👍🏻 But if I'm reading this diff right, we don't currently use Sass, so I think we can get away with just plain CSS and no CSS compiler at all.

**Comment by simi** [comment]
The only sass file is https://github.com/rubygems/rubygems.org/blob/master/vendor/assets/stylesheets/github_buttons.css.scss, but that's actually css file if I understand it well.

I think the simple assets pipeline, same as generated with `rails new myapp -a propshaft --skip-hotwire`, will be enough. No need for compress, transpile, terser, ... Performance could be handled by HTTP/2 and gzip. We just need to ensure majority of browser accesses are able to continue using the page as is. IMHO that's ok since the CSS/JS features used currently are very conservative for 2023.

On the other side propshaft is new and having dev problems like https://github.com/rails/propshaft/issues/90. :thinking:

**Comment by indirect** [comment]
Closing this in favor of #4123.

**Pull request closed without merging**
