### PR TITLE
Enable HSTS for subdomains

### PR DESCRIPTION
**Pull request by segiddins**
Fixes TOB-RGM-4

Signed-off-by: Samuel Giddins <segiddins@segiddins.me>

### CODE REVIEW

**Comment by simi** [comment]
@segiddins are you 100% sure we need this on root domain?

**Comment by segiddins** [comment]
it's what the recommendation on the finding was

**Review by martinemde — APPROVED** [review]

**Comment by martinemde** [comment]
@simi what problem are you concerned may happen?

I can't imagine any subdomain of rubygems accepting http traffic and not wanting to upgrade it to https.

**Comment by martinemde** [comment]
We have a stored response that states the following:
> The `Strict-Transport-Security` header is not suitable for [rubygems.org] because it is intentionally accessible over both HTTP and HTTPS. If we ever migrate to 100% HTTPS on this domain, we'll consider enabling the header at that time.

**Comment by segiddins** [comment]
We definitely don't allow http on rubygems.org

```
❯ curl -I http://rubygems.org
HTTP/1.1 301 Moved Permanently
Connection: close
Content-Length: 0
Retry-After: 0
Location: https://rubygems.org/
Accept-Ranges: bytes
Date: Wed, 04 Dec 2024 00:03:20 GMT
Via: 1.1 varnish
X-Served-By: cache-sjc10033-SJC
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1733270601.544959,VS0,VE0
Server: RubyGems.org```

**Comment by martinemde** [comment]
What about `source "http://rubygems.org"`? Does that still work in old versions of bundler?

**Comment by martinemde** [comment]
It doesn't seem like there's any reason to block this. If there is something responding on http that we don't know about, then I'd rather find out about it.

**Pull request merged**
