### PR TITLE
Do not 404 in rack attack on invalid url.

### PR DESCRIPTION
**Pull request by simi**
:thinking: IMHO `protected route?` should just return true/false, not raise on invalid URL.

### CODE REVIEW

**Comment by sonalkr132** [comment]
We did have issue because of this when we tried to add `redirect` route to app. My main concern with adding rescue was that it may allow bypass of ratelimit in some weird way (my fear could be unfound). `recognize_path` raising `ActionController::RoutingError` is expected behaviour. I understand it is probably best if `protected route?` just returned `true/false`.
I guess @colby-swandale can take a call on this.

**Comment by simi** [comment]
@sonalkr132 we can also fallback to `true` to be super-safe in here.

**Comment by sonalkr132** [comment]
true as fallback could end up adding too many keys to our cache. we get lots of 404 at the moment(which we are planning to block on fastly).
false is probably fine, lets see what colby has to say. also, wouldn't adding following would mean `recognize_path` would stop raising this error?
`get '*unmatched_route', to: 'application#render_not_found'`

**Comment by simi** [comment]
Probably yes, I'll work on that in different PR.

Dne ne 3. 5. 2020 21:50 uživatel Aditya Prakash <notifications@github.com>
napsal:

**Pull request merged**
