### PR TITLE
Update rubocop from 0.46.0 to 0.47.1

### PR DESCRIPTION
**Pull request by sonalkr132**
Rails/SkipsModelValidations is disabled because we are skipping
validation consciously.
Security/MarshalLoad is disabled because these is no alternative.
Rails/FilePath cop recommends:
 Please use Rails.root.join('path', 'to') instead
Security/YAMLLoad cop recommends:
 Prefer using YAML.safe_load over YAML.load.
Lint/SafeNavigationChain cop recommends:
 Do not chain ordinary method call after safe navigation operator.

changelog: https://github.com/bbatsov/rubocop/blob/e8680418b351491e111a18cf5b453fc07a3c5239/CHANGELOG.md#0470-2017-01-16

**#UpdateTheCache**

### CODE REVIEW

**Comment by sonalkr132** [comment]
This has hit https://github.com/bundler/bundler/issues/5357#issuecomment-274742137. @dwradcliffe  we need to move to rubygems 2.6.9.

**Comment by segiddins** [comment]
👌🏻

**Comment by segiddins** [comment]
Please let's use 2.6.10

**Comment by dwradcliffe** [comment]
@sonalkr132 2.6.10 is being rolled out to production; rebase this on master.

**Comment by sonalkr132** [comment]
Done!
giphy 7

**Comment by arthurnn** [comment]
thanks

**Pull request merged**
