### PR TITLE
Remove autoprefixer-rails

### PR DESCRIPTION
**Pull request by arthurnn**
As far as I can tell we are not using `autoprefixer-rails`. Also all tests are green if we remote it.
It was added in here https://github.com/rubygems/rubygems.org/commit/9f0c284991e9f236c604cb04e221da70970fcbdd

@kirs thoughts?

review @sferik @qrush 

( I am not sure what that gem does, so please educate me )

### CODE REVIEW

**Comment by sferik** [comment]
This raises the question of what versions of what browsers we support. Not sure that’s ever been discussed. I could imagine this change breaking the UI without any tests failing. Curious what @qrush and @acacheung have to say.

**Comment by ai** [comment]
@arthurnn `autoprefixer-rails` is a CSS processor for Sprockets. When you load a gem, it atomatically will be added to Sprockets processors. So this gem is using by Sprockets to generate correct CSS.

If you will remove it, all prefixes in rubygems.org CSS will be removed too. Right now Rubygems.org CSS contains at least 102 `-webkit-` prefixes. I think your site will not be display correctly in current browsers.

**Comment by arthurnn** [comment]
thanks @ai @sferik

**Comment by kirs** [comment]
> Also all tests are green if we remote it.

Tests are green only because we have no coverage for compiled CSS.
They may remain green, but in fact CSS won't be processed properly and we may have troubles in some browsers.

By using Autoprefixer here we can avoid writing a lot of additional CSS (https://github.com/kirs/rubygems.org/commit/e153f2bb531ba733d833fb8a8112856a1034d11d)

**Comment by arthurnn** [comment]
:heart: thanks @kirs

**Pull request closed without merging**
