### PR TITLE
Replace try with safe operator

### PR DESCRIPTION
**Pull request by lucianosousa**
Improving method calls using ruby safe operator instead of try rails method

See few benchmarks:
https://gist.github.com/hopsoft/ae361319c54bbcb4f8e2
https://github.com/rubygems/rubygems.org/pull/1863#issuecomment-449686553

### CODE REVIEW

**Comment by sonalkr132** [comment]
Can you please add following to your commit message?
```
(local)
 > puts Benchmark.measure { rubygem.try(:name) }
  0.000000   0.000000   0.000000 (  0.000097)
 => nil 
2.3.5 :033 > puts Benchmark.measure { rubygem&.name }
  0.000000   0.000000   0.000000 (  0.000028)
 => nil 
```

**Comment by sonalkr132** [comment]
Can we please replace all occurrences of `try`?

**Comment by sonalkr132** [comment]
What issue with `linkset.try(short)` again? `short` is not defined until `alias_method short, long`?

**Comment by simi** [comment]
Is there any real (measurable) difference before and after this pull request?

**Comment by lucianosousa** [comment]
@sonalkr132 tried `linkset&.send(short)` but fails as:
`NoMethodError: undefined method 'changelog' for #<Linkset:0x00007fa32202a680>`
weird, tried also with `(short.to_sym)` and also fails. we can improve this later if we find some way to make it works fine.

@simi doesn't change a lot, but I would say it's better and consistent use a ruby method(safe operator) than a rails one(`try`), even rails itself uses `&.` in your internals

**Comment by sonalkr132** [comment]
Merged with a7d0b57fff414223f468de79b6785f38d8b01e3d. Thanks for PR.

**Pull request closed without merging**
