### PR TITLE
Add a developer-specific Gemfile.dev

### PR DESCRIPTION
**Pull request by nateberkopec**
Alternative to #1174 

Works great. You need a fairly recent version of Bundler for this to work.

### CODE REVIEW

**Comment by indirect** [comment]
Is it possible to use Bundler's optional groups instead? You could add Guard as an opt-in group and then anyone who wants it could install and use it.

**Comment by nateberkopec** [comment]
You could, but then everyone who wanted something added would have to open a PR for their own opt-in group. This PR avoids that problem, since anyone can put w/e they want into `Gemfile.dev`.

**Comment by indirect** [comment]
Yeah, that's a good point. I'm willing to try this and see how it turns out, and if it causes any problems with the main Gemfile.

**Comment by arthurnn** [comment]
I am not a big fan of a new Gemfile.dev file. Now we need to maintain two files :/

**Comment by simi** [comment]
I think there's no reason why this should be part of the codebase. Everyone can do it locally itself if needed. This looks more like Bundler feature that can be added (shortcut for `eval_gemfile(File.expand_path("Gemfile", __dir__))`.

**Comment by nateberkopec** [comment]
@arthurnn It's .gitignored, you're not maintaining anything (beyond merging this). I think it's a better long term maintenance solution b/c if someone wants a development gem you just tell them "add it to Gemfile.dev". The alternative is either merging in random development gems that some people want or not merging them and those people having a more difficult time in development.

**Comment by nateberkopec** [comment]
@simi this is true, perhaps I should write something about writing your own `Gemfile.dev`. 

I guess there isn't really any advantage in merging this into the project. I'll blag about this approach to developer-specific gems instead.

**Comment by arthurnn** [comment]
> @simi this is true, perhaps I should write something about writing your own Gemfile.dev.

👍 

Thanks everyone

**Pull request closed without merging**
