### PR TITLE
Update Support Section

### PR DESCRIPTION
**Pull request by adarsh**
Reason for Change
=================
* As a result of some confusion about how RubyGems.org is supported, the folks at [Ruby Together](rubytogether.org) and @evanphx worked on some language we can use broadly to help clarify things.

Changes
=======
* Add the same paragraph from [our RT discussion](https://github.com/rubytogether/board/issues/5) here in this `README.md`.

Minor
-----
* Rename `Supporting` section heading to `Support` to move from a "how you could support this project" to "how it's currently being supported". Interested in feedback on this angle.
* Add the Ruby Central logo.

### CODE REVIEW

**Comment by adarsh** [comment]
This is being held up by https://github.com/rubytogether/board/pull/9

**Comment by dwradcliffe** [comment]
@adarsh Is this still valid?

**Comment by adarsh** [comment]
@dwradcliffe yes, I believe it is still valid.

@indirect can double-confirm this for me.

**Comment by indirect** [comment]
As far as I know, no one is currently confused about how RubyGems.org is supported, but it seems fine to copy the wording arrived at in rubytogether/board#9. I've updated this PR with that wording, and if @dwradcliffe approves I think we're good to merge.

**Pull request merged**
