### PR TITLE
Improving footer translation

### PR DESCRIPTION
**Pull request by davichaves**
I improved the translation for the footer and translated it to portuguese. The missing translations for the footer are: de, es, fr, nl, zh-CN, zh-TW. If people could help me by translating to these languages that would be awesome 😄

### CODE REVIEW

**Comment by sonalkr132** [comment]
Hi @davichaves! Thanks for PR :+1: 

Can you please update nl, zh-CN, zh-TW as well?

**Comment by arthurnn** [comment]
not sure if @davichaves speaks nl, zh-CN, zh-TW to be able to update those files.
If a key is not found in a locale file, rails(i18n) would just fallback to english correct?
If that's the case, I think we can ship this and let native speakers translate the other versions.

**Comment by sonalkr132** [comment]
> not sure if @davichaves speaks nl, zh-CN, zh-TW to be able to update those files.

I understand :sweat_smile:
This PR removes `footer_about` and adds `about_p1`. We have [translation of `footer_about`](https://github.com/rubygems/rubygems.org/search?utf8=%E2%9C%93&q=footer_about) in nl, zh-CN, zh-TW, it should be changed to `about_p1`. Something very similar to https://github.com/rubygems/rubygems.org/pull/1511/commits/e884bbf55a471b55719dd2f1db8ce86c820f2571

**Comment by jvanbaarsen** [comment]
@davichaves Are you still working on this?

**Comment by dwradcliffe** [comment]
Closing since this is stale and needs to be rebased. Happy to get it merged if you still want to work on it. 😄

**Pull request closed without merging**
