### PR TITLE
Add Japanese translation

### PR DESCRIPTION
**Pull request by m1kit**
- Added ja.yml
- Reviewed by @igaiga

### CODE REVIEW

**Comment by dwradcliffe** [comment]
Thanks! Let's get a couple reviews done and then we can merge this.

**Comment by JuanitoFatas** [comment]
@igaiga could you review the translations? 🙇

**Comment by igaiga** [comment]
@JuanitoFatas No problem. LGTM. 👍

**Comment by m1kit** [comment]
Thank you👍

**Comment by sonalkr132** [comment]
Thanks @m1kit :smile:

**Pull request merged**
