### PR TITLE
add changelog link to rubygem linkset

### PR DESCRIPTION
**Pull request by farukaydin**
Related with #728, #324

cc: @sferik @qrush

### CODE REVIEW

**Comment by qrush** [comment]
Nice. I'd love for us to parse this out of the gemspec too.

**Comment by arthurnn** [comment]
Is this on part of the gemspec? cc @drbrain 
I am ok with us moving forward with this and do the parse in a next PR.
@dwradcliffe @qrush @sferik if you are all good with this change, I can take care of merging it, and deploying it and run the migration.

**Comment by arthurnn** [comment]
@olivierlacan thoughts?

**Comment by olivierlacan** [comment]
@arthurnn I'm pretty sure we have a nice PR idea where everything was moved to the serialized column instead of adding discrete columns for these new (and valuable) pieces of metadata. I'd be interested in going that way rather than adding yet another column because it seems unlikely we would query by it.

**Comment by kbrock** [comment]
I too want this in the serialized metadata column.
I really want changelog links in, but would prefer to go the route of #724 

Also, I promise to fix #728 once #724 merges.

**Comment by olivierlacan** [comment]
While testing https://github.com/rubygems/rubygems.org/pull/1104#issuecomment-155308394 I noticed that `linksets` SELECTs were consistently the worse performing queries from the rubygem GET endpoint. I'd really like to help @kbrock with that serialized metadata idea, I feel like that would improve the performance of the API endpoint by about a third on the SQL-side alone.

**Comment by arthurnn** [comment]
I will be closing this, as I think we should have this data as serialized metadata. We already have the metadata been populated from the gemspec, https://github.com/rubygems/rubygems.org/blob/71e4b50c6b3de8c6bee0efee3ef61f86388fc996/app/models/version.rb#L186
Thanks for the PR.

**Comment by olivierlacan** [comment]
:thumbs_up:

**Pull request closed without merging**
