### PR TITLE
Change hash rocket to hew hash syntax in all view files

### PR DESCRIPTION
**Pull request by davydovanton**

### CODE REVIEW

**Comment by simi** [comment]
How is this useful? I think this just pollutes git history. :( :-1:

**Comment by davydovanton** [comment]
I think, that it looks cleaner, but yes, maybe you're right

**Comment by arthurnn** [comment]
@davydovanton Thanks a lot for the PR :heart: and for caring about code style on rubygems.org .
Unfortunately, I agree with @simi as this makes git history a bit confusing :confused:  .

My rule is, when I am changing code around, I update the hash syntax, as I agree with you thats a better syntax. But a PR with updating only that, I dont think is a good idea.

Thanks again.

**Comment by davydovanton** [comment]
@simi @arthurnn thanks for review :purple_heart:

**Pull request closed without merging**
