### PR TITLE
Add API key stimulus controller and improve behavior

### PR DESCRIPTION
**Pull request by martinemde**
The form now helps you with exclusive scopes and auto-deselects the other checkboxes when exclusive scopes are chosen.

Screen recording:

https://github.com/rubygems/rubygems.org/assets/989/579bc430-d050-4895-9794-15d5312dd44d

### CODE REVIEW

**Comment by martinemde** [comment]
Oops, I'll fix the tests and request review again.

**Comment by martinemde** [comment]
The tests were failing because the edit form was distinct from the new form. I moved the duplicated form erb into a `_form.html.erb` partial and then fixed the missing or moved translation keys.

**Comment by simi** [comment]
@martinemde I think you have missed one case with I18n keys. I tried to fix it.

**Review by simi — APPROVED** [review]

**Comment by martinemde** [comment]
Ok, I took @colby-swandale's suggestion in another PR and tried to apply a more stimulus-y (stimulating? no) approach to this PR. It works the same now but the functionality is split up better. It's maybe even reusable (probably not).

**Comment by simi** [comment]
> The form now helps you with exclusive scopes and auto-deselects the other checkboxes when exclusive scopes are chosen.

Is that covered by tests currently?

> Edit: Wow this PR got big.

_That's usually caused by I18n files :). It seems looks reasonable size to me._

**Comment by martinemde** [comment]
> Is that covered by tests currently?

Good catch. The submit would still enforce exclusivity but I didn't add a test to make sure the JavaScript does what it should.

I'll get that added. Thank you.

**Review by segiddins — APPROVED** [review]

**Comment by martinemde** [comment]
Added test coverage for the exclusive checkbox behavior.

**Pull request merged**
