### PR TITLE
create a constant with pagination value

### PR DESCRIPTION
**Pull request by lucianosousa**
avoid duplicated values in the controller

### CODE REVIEW

**Comment by nateberkopec** [comment]
:+1: Is this value used anywhere else?

**Comment by lucianosousa** [comment]
Couldn't find it, but did look too deep.
I saw in a lot of places a pagination by 5 items.

**Comment by simi** [comment]
for example it is here also - https://github.com/rubygems/rubygems.org/blob/0fcc8b058a5ea4d0763f27846b6298c5459aac1c/app/controllers/rubygems_controller.rb#L14

**Comment by lucianosousa** [comment]
Should we create a constant for this value in application.rb or any other place?

**Comment by farukaydin** [comment]
:-1: on this. Although it's a kind of reducing duplication, it's not worth to change since we have different number of pagination and current version is sufficient enough to keep the codebase more readable.

Though, thanks for contributing rubygems.org :blue_heart: :heart:

**Comment by sonalkr132** [comment]
I think this makes sense, we should as few magic numbers as possible, even if it only 2/3 fewer.

> Should we create a constant for this value in application.rb

[application.rb](https://github.com/rubygems/rubygems.org/blob/master/config/application.rb#L40-L41) should be fine.

**Comment by jvanbaarsen** [comment]
@lucianosousa Are you still working on this? If not, can you please close the PR? That way the list of open PRs is kept organised with active ones only :-)

**Comment by lucianosousa** [comment]
@jvanbaarsen sorry being late here Sir. It's done!

**Comment by jvanbaarsen** [comment]
@dwradcliffe I think this is ready to merge :-)

**Comment by sonalkr132** [comment]
@lucianosousa can you please [squash](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history%23squash-commits-together&hl=en-IN) your commits?

**Comment by sonalkr132** [comment]
Merged as f5686b37c530a73f8f88991e4aadeeadec04caf3.

**Comment by lucianosousa** [comment]
cheers mates

**Pull request closed without merging**
