### PR TITLE
Include version_created_at in Rubygem payload.

### PR DESCRIPTION
**Pull request by tiegz**
Currently there's no timestamp returned from `https://rubygems.org/api/v1/activity/just_updated.json` to show when each version was pushed, even though it's a time-relative endpoint. You have to visit each version's endpoint to see when it was pushed. 

This adds a new `version_created_at` to Rubygem#payload so it's easier to see that gem's latest version timestamp.

Alternatively, we could also do what `Api::V1::TimeframeVersionsController` does and merge `version.as_json` into this endpoint's payload too.

Q: I don't see any tests for Rubygem/Version payload methods. Is it better to test this in the controller, or backfill those payload tests?

### CODE REVIEW

**Review by epfeen — APPROVED** [review]

**Comment by simi** [comment]
I have no strong opinion on this, but it would make it more merge friendly with some tests around.

**Comment by tiegz** [comment]
Just updated the rubygems payload test with this new field.

**Comment by sonalkr132** [comment]
Thanks @tiegz

**Comment by tiegz** [comment]
Thank you @sonalkr132 !

**Pull request merged**
