### PR TITLE
Change web fonts, speed up perceived load times by 75%

### PR DESCRIPTION
**Pull request by nateberkopec**
As discussed in #1095, Typekit represents a huge amount of the total page weight of Rubygems.org. This PR aims to change that, while minimizing impact on the visual look and feel of the site.

This PR:

* Removes Typekit
* Swaps Aktiv Grotesk, the current site font, with a single "accent" h1 header font (Raleway) and uses system fonts for all remaining text.

## Philosophy

I think open source should be accessible to everyone - whether you have a snappy high bandwidth connection or not. Ruby is a global phenomenon, and I want to encourage even more people to try Ruby by making sure that our infrastructure performs well for people with average global connection speeds.

## Changes

Aktiv Grotesk was previously used for all site text. *Excluding* h1s, I have changed this to Helvetica Neue (Arial on non-Mac platforms). Here is a side-by-side of Aktiv Grotesk vs Helvetica, Aktiv on top:

screen shot 2015-11-13 at 1 44 14 pm

The most visually distinctive typographic feature of the current design is the use of a light-weight font for h1s. I have retained that by swapping in Raleway, a similar humanist sans-serif. Here is a side-by-side of Aktiv Grotesk vs Raleway, Aktiv on top:

screen shot 2015-11-13 at 1 55 22 pm

[Here's a comparison of a Gem page](http://imgur.com/a/FruOD).

## Benefits

Taking this approach shaves almost 400KB off the total page weight (almost 70%). That sounds nice, but what is really compelling is its impact on first-time page loads and paint times.

For this test, I used Google Chrome's network throttling feature. The site was running in production mode. I assumed a 625KB/s (5mbps) connection for the average global user (this number is pulled from Akamai), and a 1.5 MB/s (12mbps) connection for the average US user (also Akamai). 

### Current Live Site

| | Time to First Paint | Time to Paint Text (fonts loaded) | Time to Full Load |
| --- | --- | --- | --- |
| US  | 3.56s | 3.83s | 3.96s |
| Worldwide | 7.41s | 7.59s | 8.20s |

### This Pull Request

| | Time to First Paint | Time to Paint Text (fonts loaded) | Time to Full Load |
| --- | --- | --- | --- |
| US  | 854ms | 1.16s | 1.78s |
| Worldwide | 1.60s | 2.42s | 3.96s |

It's worth noting that, because there is no longer any render-blocking javascript before the CSS in the HEAD tag, the impact on paint times is far greater, percentage wise, than the impact on total `load` event times.

These numbers may be even better in production, as my local setup is slightly gimped versus the live site because I'm not serving the site assets gzipped.

**The average worldwide connection sees nearly a 75% improvement in time to painting all the text to the screen with this change.** Time to paint is more important than time to load in this case - load times are slightly behind the entire page actually being rendered.

## Open Questions

* Can we get a designer to review this change from a visual standpoint?
* Also a design question - should we consider adding Segoe UI or Calibri to the font stack for Windows users? Those fonts offer considerably more weights than Arial, but look slightly different. **EDIT**: No, let's leave that for another day.
* I used Google Fonts because Google will intelligently serve the best font format to each User Agent (WOFF2 to Chrome/FF, WOFF to IE9 >, I think TrueType for all else). We *could* inline a WOFF version into the CSS instead, which would allow us to eliminate Google entirely. There may be a small performance benefit to this. **EDIT**: Also leave for another day.

### CODE REVIEW

**Comment by Onumis** [comment]
:clap: :clap: :clapper:

**Comment by RichiCoder1** [comment]
This is awesome, but could you not have simply moved the TypeKit javascript to a non-blocking position, and improved the font defaults so the pop-in wasn't as jarring?

**Comment by chills42** [comment]
Looks great! The only visual issue I see is with the gem version number in the title using raleway numbers.

**Comment by nateberkopec** [comment]
@RichiCoder1 Yes. However, we'd still be loading 14 different styles and weights of Aktiv Grotesk. So you wouldn't get the ~400kB page weight improvement you do here. Additionally, there aren't great fallback fonts for Windows or Android, and there is no appropriate fallback font for Linux.

@chills42 Good catch, Raleway appears prefer old-style baselines for numbers, rather than a modern "lining" style. [Whether or not this is a good thing is debatable](http://ux.stackexchange.com/questions/54740/what-is-the-appeal-of-old-style-numbers-and-why-do-modern-fonts-still-include-th). It's worth noting that the gem version number is intended to be in a light weight, so I think it's appropriate to keep it as Raleway. Whether or not we want lining numbers or old-style numbers, perhaps we can get a few more opinions on?

**Comment by gosukiwi** [comment]
I suggest using the default system font for each platform. 

`font-family: -apple-system, "Helvetica Neue", "Roboto", "Segoe UI", "Lucida Grande", sans-serif;`

Those are modern defaults for OS X, Android and Windows. [Medium](https://medium.com/@mwichary/system-shock-6b1dc6d6596f) uses that approach.

**Comment by bluebear94** [comment]
Yes for Segoe UI. No for Calibri (it looks ugly).

**Comment by arthurnn** [comment]
My intuition is to merge this right away, as this brings a big performance improvement and I like it 😸 .
I would like thoughts from @qrush first tho, before I merge, as he was more involved than me on the re-design of the website.
I am 👍 , and thanks a lot for the changes and tracing.

**Comment by nateberkopec** [comment]
Right, there's really only two open things:

* Should we change the main font stack to something other than what I've done? (Helvetica/Arial). I say *no*, as that was the original font stack, and changing the Windows fallback to something like Segoe or adding a more comprehensive fallback list is changing the original design too much. We can leave that issue for another day, it's orthogonal to the changes here really.
* Should we use lining numbers or old-style number for gem versions? Raleway uses "old-style" numbers by default: http://i.imgur.com/JooLgpm.png, note the baseline dropped on the 5. Changing this is a matter of setting [`font-variant-numeric`](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-numeric).

**Comment by qrush** [comment]
I have a few questions:

1) Anyone from Dockyard have an opinion on this, given they led the design? @acacheung @bcardarella
2) What's the non-Latin character support for Raleway look like? Thinking Cyrillic, Chinese, Japanese, etc etc...

In general I am :+1: for this though. I would agree to not drop the baseline and set `font-variant-numeric` if we can change that.

**Comment by nateberkopec** [comment]
@qrush Raleway is available in *Latin only*. If this is a hard requirement, we can definitely investigate an alternative. Raleway just happens to be one that I think looks the closest to Aktiv Grotesk. Roboto, for an example, has Cyrillic, Greek and Latin Extended. Google Fonts does not publish any fonts with Japanese or Chinese character sets.

Worth noting that Aktiv Grotesk, as served by Typekit, does not support Japanese or Chinese characters. Confirmed in my browser by swapping my locale and checking the font.

Will update with some screenshots of lining numbers and an alternative font with extended character support.

**Comment by bcardarella** [comment]
I am 100% for moving to webfonts over Typekit. I am not happy that we (DockYard) went with Typekit to begin with and have since completely ditched it in favor of webfonts for all of our client projects. The design desire of the typography is outweighed here by the overwhelming evidence that Typekit is a performance nightmare.

:+1:

**Comment by nateberkopec** [comment]
I've decided to roll with Roboto over Raleway for language support reasons. I do not believe we have a locale file yet that can take advantage of this, but also I don't want someone to add a locale later with special characters (for example, an Eastern European language like Czech) and then be frustrated to see it not work with Raleway. Roboto looks close enough (though I am willing to be told be a designer otherwise!)

Here's Roboto on the homepage:

screen shot 2015-11-23 at 2 40 42 pm

[Here's Roboto used to render the header of a gem's page](http://imgur.com/7AFibs4).

Advantages of swapping to Roboto: 

* Increases supportable languages to many Euro and non-European languages.
* We now have the same language support as we did when using Aktiv Grotesk.

Disadvantages of swapping to Roboto:

* We don't yet have a locale file that can fully utilize these character sets.
* This will increase font download size to about ~70kb in Firefox and in any other browsers that do not support [unicode-range](http://caniuse.com/#feat=font-unicode-range). Font download size is unaffected in Chrome and Opera, possibly Safari and IE, because those browsers can intelligently request which characters they need to render the page (they ignore the `subset` parameter in the Google Fonts URL in this PR). Total font download size is about ~10kb in these browsers. In any case, this is still a massive improvement over the current situation.
* It doesn't look *quite* as nice IMO as Raleway, but I'm willing to concede that it's probably bike shedding.

pinging @qrush

**Comment by simi** [comment]
@nateberkopec I think this can solve https://github.com/rubygems/rubygems.org/issues/732 also.

*ps.: I had an idea to translate rubygems.org into Czech. But everyone programming in Ruby can handle basic English in Czech republic, so I think it is not worth it.*

*ps2.: Czech is Central European language IMHO.*

**Comment by dwradcliffe** [comment]
LGTM
I would still like to use a font that we serve ourselves, eventually, but this is a huge improvement.

**Comment by nateberkopec** [comment]
@simi Yes, hopefully we can close #783 and #785 with this! And sorry, I'm a silly American, you should feel lucky I even know the Czech Republic is in Europe! :stuck_out_tongue_closed_eyes: 

@dwradcliffe I sympathize, but through doing this PR, I've become more and more impressed with Google Fonts. UA-specific font delivery and other optimizations make it really difficult to compete against from a perf perspective! Of course, since [Roboto is Apache licensed](https://github.com/google/roboto/blob/master/LICENSE), we have a lot more leeway on messing with it ourselves though.

**Comment by qrush** [comment]
Big :+1:. Let's try it out.

I'm still not sure what to do about RDoc in readmes, geez that screenshot is rough.

**Comment by dwradcliffe** [comment]
I'm going to merge this and we can try it out. It looks like it will be a huge improvement and we can iterate on it if we want. Thanks @nateberkopec!

**Comment by nateberkopec** [comment]
:+1: I'll reinvestigate remaining open font issues once it's deployed

**Comment by dwradcliffe** [comment]
Deployed to production!

**Comment by simi** [comment]
Thanks! #732 is fixed for me.

**Comment by nateberkopec** [comment]
Looks like, as I expected, this is doing even better in production! 

### Current Production

| | Time to First Paint | Time to Paint Text (fonts loaded) | Time to Full Load |
| --- | --- | --- | --- |
| US (1.5 MB/s)  | 350ms | 510ms | 1.05s |
| Worldwide (625 KB/s) | 704ms | 1.27s | 2.17s |

That's a staggering **90% improvement in time to paint!** About an entire order of magnitude!

**Comment by olivierlacan** [comment]
Hell yeah @nateberkopec :+1:

**Comment by qrush** [comment]
:tada:

victory

**Pull request merged**
