### PR TITLE
Update rails to remove mimemagic

### PR DESCRIPTION
**Pull request by sonalkr132**
https://weblog.rubyonrails.org/2021/3/26/marcel-upgrade-releases/

### CODE REVIEW

**Comment by arthurnn** [comment]
perfect

**Comment by arthurnn** [comment]
Do you want to do a deploy with out of this merge?

**Comment by sonalkr132** [comment]
Not really. We don't have anything major in staging as of now. Am I missing the reason to deploy without this?

**Comment by arthurnn** [comment]
i meant to deploy with this :)

**Pull request merged**
