### PR TITLE
Removed blacklist patterns for default gems of Ruby 2.5

### PR DESCRIPTION
**Pull request by hsbt**
It's part of a request for [Gemification Plan](https://bugs.ruby-lang.org/issues/5481). I've finished preparing to ship some default gems to rubygems.org from standard libraries. 

PS. Some gems have already reserved other users. I will ask to transfer its ownership after this pull request was deployed.

### CODE REVIEW

**Comment by dwradcliffe** [comment]
Sounds good, but can we transfer ownership before we merge this?

**Comment by hsbt** [comment]
@dwradcliffe I'm not sure to transfer ownership with blacklisted status. Example for https://rubygems.org/gems/webrick . I'm going to ask webrick owner named @nahi . He is a member of ruby core team :octocat:

**Comment by hsbt** [comment]
I got ownership of webrick from @nahi. I confirmed that we can transfer ownership under the blacklisted status.

As first, I'm going to ask about ownership to reserved gem authors.

**Comment by hsbt** [comment]
@dwradcliffe I summarized about reserved gems with this pull request.

### Reserved gems with blacklisted

 * csv
 * etc 
 * fileutils

Can you transfer ownership of above gems to me? These are already blacklist status, so their owner can not update it. It ownership already transferred to rubygems admins, I think.

PS. I'm ok that I ask these owners.

### Reserved gems without blacklisted

 * gdbm

I'm going to ask above [owner](https://github.com/presidentbeef/ffi-gdbm). I want you to mediate when the negotiations ended poorly 🙇

**Comment by dwradcliffe** [comment]
I have removed webrick from the blacklist https://github.com/rubygems/rubygems.org/commit/81c3c5019bd0719c21bfa577b503201664f8b1f8

**Comment by hsbt** [comment]
I got approvement to transfer request for gdbm. (It's out of scope for this pull request.

**Comment by sonalkr132** [comment]
`csv` doesn't have an owner and it seems unlikely that owner of `fileutils` will respond (worth trying tho). We will need to transfer those ownerships manually.
@tarcieri can help with transfer of [etc](https://rubygems.org/gems/etc/versions/0.2.0) :pray: .

**Comment by hsbt** [comment]
@sonalkr132 csv has following owner.

```
> curl https://rubygems.org/api/v1/gems/csv/owners.json
[{"id":95512,"handle":"jimflexton","email":"hans_adel@zoho.com"}]
```

Is it wrong information via rubygems API?

**Comment by sonalkr132** [comment]
> Is it wrong information via rubygems API?

No, that's correct. I must have checked it on my local env (it doesn't have owner info). Sorry :sweat_smile:

**Comment by tarcieri** [comment]
@hsbt I added you as an owner of the etc gem

**Comment by hsbt** [comment]
@tarcieri Thank you!

@dwradcliffe How about next action for `csv` and `fileutils` ? If it's my time, Please ping me.

**Comment by dwradcliffe** [comment]
`csv` only has one version and it is yanked, which means it's technically available.

@hsbt I'll ping you when I wake up in the morning and we'll get these 2 transferred to you.

**Comment by hsbt** [comment]
@dwradcliffe Thanks a lot. I'm waiting until your mention is coming. :octocat:

**Comment by dwradcliffe** [comment]
@hsbt Reviewing this PR again, is everything in here ready to be pushed if I merge this now?

**Comment by hsbt** [comment]
Thank you!

I registered all of the listed gems now.

**Pull request merged**
