### PR TITLE
Shift helper methods to fix cop failures

### PR DESCRIPTION
**Pull request by vachhanihpavan**
`app/helpers/rubygems_helper.rb` was exceeding 100 lines of code.
So, shifting a few methods around to avoid cop failures

### CODE REVIEW

**Comment by colby-swandale** [comment]
Could we instead update the Rubocop config to exclude the breaking rule for `app/helpers/rubygems_helper.rb`? Separating the RubyGems helper doesn't seem like the right solution to me.

**Comment by simi** [comment]
Isn't current max 350? https://github.com/rubygems/rubygems.org/blob/bec5aaaede64b97ec56eb2f7a91c46066e65c4a2/.rubocop.yml#L56-L57

**Comment by sonalkr132** [comment]
`Metrics/ModuleLength` is raising error. 
I personally prefer to refactor, 100 lines is good enough limit for a module doing too many things. 
Excluding this file isn't as bad i guess. @vachhanihpavan   please revert to whatever what you had used. sorry about hassle.

**Comment by simi** [comment]
100 seems too limiting, what about to extending that?

**Comment by sonalkr132** [comment]
100 lines limit has worked so far, which makes me believe it wasn't too limiting.
I would suggest exclude, with intention that we will clean it up when we get a chance. `nice_date_for` and `simple_markup` clearly don't belong in rubygems helper. This module needs refactor, it is just matter of time.

**Pull request closed without merging**
