### PR TITLE
Add record to track rubygem total downloads

### PR DESCRIPTION
**Pull request by sonalkr132**
80 rubygems seem to missing following record used to track total
downloads of a rubygem:
```
GemDownload.where(rubygem_id: rubygem.id, version_id: 0)
```
All of these gems have created at date before 2012, while we started
adding above record in 2016. We may have missed adding rubygem record
in backfill because they didn't to have any versions at the time.

We need to create rubygems record for unindexed rubygems as well,
since someone can start using these names in future. for example:
rexml was reserved name but now it is being used.

closes: #2401

### CODE REVIEW

**Comment by dwradcliffe** [comment]
I wonder if we could create them as needed in the stats processing instead?

**Comment by sonalkr132** [comment]
> I wonder if we could create them as needed in the stats processing instead?

Yes, we can definitely find a way with if statements to create the record in log processors. However, I am assuming this issue won't come up in future as `Rubygems` model has create hook and all the code we add in the processor will efficiently be dead code.

**Comment by sonalkr132** [comment]
Also, I forgot to mentions following todo:
```
# TODO: Remove this once we move to GemDownload only
after_create :create_gem_download
((source)[https://github.com/rubygems/rubygems.org/blob/master/app/models/rubygem.rb#L28))
```
Did we have plans to get rid of this rubygems record all together and use `GemDownload.where(rubygem_id: rubygem.id).sum(:count)` instead? We have n+1 for gem downloads in a few places, not sure if this will be a good idea.

**Comment by colby-swandale** [comment]
I agree with the one off approach to backfill the missing `GemDownload` records

**Pull request merged**
