### PR TITLE
Add multi-column index to Versions

### PR DESCRIPTION
**Pull request by nateberkopec**
Replaces #1770. @mjankowski pointed out that a multi-column index works great on this query, and it does!

### CODE REVIEW

**Comment by mjankowski** [comment]
Newer rails versions change the spacing to look like what your changes are now showing ... this is bound to happen after someone's migration ... but the spacing churn should hopefully be reduced in the future after it happens once.

**Comment by sonalkr132** [comment]
> the spacing churn should hopefully be reduced in the future after it happens once.

https://github.com/rails/rails/commit/df84e9867219e9311aef6f4efd5dd9ec675bee5c?short_path=1ed2907#diff-e0d63791fb8e00fc467e7c47b74fb6d6 Not the first time https://github.com/rubygems/rubygems.org/pull/1647 :crying_cat_face: 
I am also getting `id: :serial` on `rake db:drop db:create db:migrate`
``` diff
create_table "users", force: :cascade do |t|             
-    t.string   "email"                                             
-    t.string   "encrypted_password",        limit: 128
-    t.string   "salt",                      limit: 128
-    t.string   "token",                     limit: 128        
+  create_table "users", id: :serial, force: :cascade do |t| 
``` 
https://stackoverflow.com/questions/43786903/why-isnt-schema-rb-formatted-correctly-in-rails-5-1-0

**Comment by sonalkr132** [comment]
please rebase!

**Comment by simi** [comment]
I think `build_at` column is not used anymore in any query triggered in `versions#index` action. I think we can close this.

**Comment by sonalkr132** [comment]
Yeah, we stopped using `first_built_date` since #1504. Thanks for the PR, anyway.

**Pull request closed without merging**
