### PR TITLE
Expose gem metadata from the API

### PR DESCRIPTION
**Pull request by jimmycuadra**
This patch adds `Gem::Specification#metadata` as a saved attribute on rubygems.org's `Version` model and includes it in JSON and XML responses from the API. This can be very useful for building applications that use custom metadata associated with a gem. Currently, this data must be extracted from a `.gem` file directly, which involves filesystem operations that are much more error prone than simply getting the data from the rubygems.org API.

For some background on why I want this, please see http://www.jimmycuadra.com/posts/how-lita-io-uses-the-rubygems-and-rubygems-org-apis.

### CODE REVIEW

**Comment by indirect** [comment]
I am :+1: on this.

**Comment by arthurnn** [comment]
Would we have to run a data migration to update all old gems with this information? or are we ok to only have that for new gem versions?

**Comment by jimmycuadra** [comment]
Good question. I think backfilling the data would be ideal for consistency. That could be done in a separate step after this is rolled out, though.

**Comment by jimmycuadra** [comment]
If we're going backfill all existing gems, maybe it would be better not to expose metadata from the API endpoints yet, but to do that in a separate PR after all the data is filled in. That would make a three step process, like this:

1) Add the metadata field to `Version` and start persisting it for new gems. (This PR.)
2) Run a job to backfill metadata for all existing gems.
3) Start including the metadata in API responses.

Thoughts?

**Comment by davefp** [comment]
@jimmycuadra As a result of #610 a large chunk of the repo's history was re-written. Please rebase your PR so that it will merge cleanly. Thanks!

(There are further details on the blog: http://blog.rubygems.org/2015/02/01/rewriting-history.html)

**Comment by jimmycuadra** [comment]
Rebased.

**Comment by jimmycuadra** [comment]
Anything I can do to help push this forward?

**Comment by sferik** [comment]
Looks good to me.

**Comment by jimmycuadra** [comment]
Thanks, Erik! What do you folks want to do regarding backfilling data? I can submit another PR with an async job to do it. If I do, any ideas on the follow questions would be useful:

* How should I coordinate which gem versions need to be backfilled? Everything before a certain timestamp? Would that be the time when this PR gets deployed? How will I know when that is?
* Since there are a very large number of gem versions, should the job be segmented in some way for performance considerations or to make it resumable if it stops/fails part way through? How should the job be segmented?

**Comment by arthurnn** [comment]
This is how we did a backfill of a SHA256 of all gems, https://github.com/rubygems/rubygems.org/blob/f6656d97a68a9bac085fb6c0d40abba48f079f77/lib/tasks/gemcutter.rake#L31-L46 .

That took almost 1 week to finish, running 4 jobs in parallel. 
The checksum was important to be backfilled for security reasons, however I wonder if this is really necessary to backfill the DB. I would argue that we can only provide metadata for new gems and thats good enough. 

thoughts @sferik @dwradcliffe @qrush

**Comment by sferik** [comment]
I’m :+1: on backfilling the metadata. Most gems don’t have any metadata, so I think the job would go relatively quickly vs. #872, which updated every row in the `versions` table.

I can’t think of any downsides of backfilling the data.

**Pull request merged**
